# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Dictionaries
1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>
2. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>
3. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>
4. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries](https://stackoverflow.com/questions/25836376/how-to-get-the-inner-indexes-of-a-nested-dictionary-in-python).** <br><br>
5. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists. **Hint: Use `zip` function adn [this link](https://stackoverflow.com/questions/1024847/how-can-i-add-new-keys-to-a-dictionary).** <br><br>

In [8]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

In [9]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

#### ANSWER 1.1
First of all, we create three arrays, two for the even and odd numbers, and the other for the keys for the dictionary. After that, we convert that arrays for a list in order to have the inputs for the dictionary. Finally, we join the two list and convert the result in a dictionary, to get the requested.

In [2]:
import pandas as pd
import numpy as np

In [3]:
values_1 = np.arange (0, 2001, 2)
values_2 = np.arange (9001, 19000, 2)
keys = ['even_number','odd_numbers']


In [4]:
print(values_1)
print(values_2)
print(keys)

[   0    2    4 ... 1996 1998 2000]
[ 9001  9003  9005 ... 18995 18997 18999]
['even_number', 'odd_numbers']


In [5]:
list_values_1 = values_1.tolist()
list_values_2 = values_2.tolist()
total_list = [list_values_1, list_values_2]

In [6]:
final_output = dict( zip( keys, total_list ) )
final_output

{'even_number': [0,
  2,
  4,
  6,
  8,
  10,
  12,
  14,
  16,
  18,
  20,
  22,
  24,
  26,
  28,
  30,
  32,
  34,
  36,
  38,
  40,
  42,
  44,
  46,
  48,
  50,
  52,
  54,
  56,
  58,
  60,
  62,
  64,
  66,
  68,
  70,
  72,
  74,
  76,
  78,
  80,
  82,
  84,
  86,
  88,
  90,
  92,
  94,
  96,
  98,
  100,
  102,
  104,
  106,
  108,
  110,
  112,
  114,
  116,
  118,
  120,
  122,
  124,
  126,
  128,
  130,
  132,
  134,
  136,
  138,
  140,
  142,
  144,
  146,
  148,
  150,
  152,
  154,
  156,
  158,
  160,
  162,
  164,
  166,
  168,
  170,
  172,
  174,
  176,
  178,
  180,
  182,
  184,
  186,
  188,
  190,
  192,
  194,
  196,
  198,
  200,
  202,
  204,
  206,
  208,
  210,
  212,
  214,
  216,
  218,
  220,
  222,
  224,
  226,
  228,
  230,
  232,
  234,
  236,
  238,
  240,
  242,
  244,
  246,
  248,
  250,
  252,
  254,
  256,
  258,
  260,
  262,
  264,
  266,
  268,
  270,
  272,
  274,
  276,
  278,
  280,
  282,
  284,
  286,
  288,
  290,
  292,
  294,
  29

#### ANSWER 1.2
We use the "get" function to have the value of "brand" key in the "car" dictionary.

In [10]:
car.get("brand")

'Ford'

#### ANSWER 1.3
We use the "get" function to get all the values found in the dictionary keys.

In [11]:
car.values()

dict_values(['Ford', 'Mustang', 1964])

#### ANSWER 1.4
To get the max value of "friday" in "january" key of hr_sleep dictionary we use "max" function.

In [12]:
máximo_valor = max(hr_sleep["january"]["friday"])
máximo_valor

2

#### ANSWER 1.5
First we join the two lists into a single dictionary, and then add it as a new key.

In [13]:
hr_sleep['march'] = dict( zip( week1 , values2) )
hr_sleep

{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]},
 'february': {'saturday': 5, 'sunday': 10, 'monday': 8},
 'march': {'monday': [2, 3, 4], 'sunday': 8}}

## 1.2 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [3]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

#### ANSWER 2.1
With the "len" function we identify the number of elements in np1, =and with "%" operator we make a list with all even numbers in that range.
Afterwards, we use that list as the index so we can replace all even numbers with "100".

In [3]:
len(np1) #550
li= np.array(range(0, 549))
par=li[li%2==0]
print(par)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250
 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286
 288 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322
 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358
 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394
 396 398 400 402 404 406 408 410 412 414 416 418 420 422 424 426 428 430
 432 434 436 438 440 442 444 446 448 450 452 454 456 458 460 462 464 466
 468 470 472 474 476 478 480 482 484 486 488 490 49

In [4]:
np1 = np.array(np1)
np1[par] = 100
print(np1)

[100 201 100 203 100 205 100 207 100 209 100 211 100 213 100 215 100 217
 100 219 100 221 100 223 100 225 100 227 100 229 100 231 100 233 100 235
 100 237 100 239 100 241 100 243 100 245 100 247 100 249 100 251 100 253
 100 255 100 257 100 259 100 261 100 263 100 265 100 267 100 269 100 271
 100 273 100 275 100 277 100 279 100 281 100 283 100 285 100 287 100 289
 100 291 100 293 100 295 100 297 100 299 100 301 100 303 100 305 100 307
 100 309 100 311 100 313 100 315 100 317 100 319 100 321 100 323 100 325
 100 327 100 329 100 331 100 333 100 335 100 337 100 339 100 341 100 343
 100 345 100 347 100 349 100 351 100 353 100 355 100 357 100 359 100 361
 100 363 100 365 100 367 100 369 100 371 100 373 100 375 100 377 100 379
 100 381 100 383 100 385 100 387 100 389 100 391 100 393 100 395 100 397
 100 399 100 401 100 403 100 405 100 407 100 409 100 411 100 413 100 415
 100 417 100 419 100 421 100 423 100 425 100 427 100 429 100 431 100 433
 100 435 100 437 100 439 100 441 100 443 100 445 10

#### ANSWER 2.2
Arange function gives us an array with intergers in the established range. In the function we must include as the final element of the range a number 1 interger higher than the element we want our array to have ("0,9" when we want the elements from 0 to 8). Afterwards, reshape function gives us a matrix of indicated size.

In [5]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### ANSWER 2.3
First we create the Z array with arange function. Afterwards, we split the arrange into each of its elements, and then create 8 arrays with concatenate function, joining the elements into the desired output. Finally, we concatenate those new arrays into R.

In [59]:
Z =  np.arange(1, 11)
Z_split = np.array_split(Z,10)
Z_1 = np.concatenate(Z_split[0:4])
Z_3 = np.concatenate(Z_split[1:5])
Z_4 = np.concatenate(Z_split[2:6])
Z_5 = np.concatenate(Z_split[3:7])
Z_6 = np.concatenate(Z_split[4:8])
Z_7 = np.concatenate(Z_split[5:9])
Z_8 = np.concatenate(Z_split[6:10])

In [93]:
R = np.concatenate(([Z_1],[Z_2],[Z_3],[Z_4],[Z_5],[Z_6],[Z_7],[Z_8]))
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

#### ANSWER 2.4
Random.random function gives us a matrix of indicated dimensions with random numbers.

In [6]:
x = np.random.random((3,3,3))
print(x)

[[[0.18907951 0.72628963 0.59886715]
  [0.26478354 0.50264506 0.3497644 ]
  [0.12389655 0.94716331 0.03359332]]

 [[0.08607144 0.87424491 0.65337024]
  [0.76336101 0.31362882 0.22168691]
  [0.51242591 0.44124865 0.81115569]]

 [[0.36076647 0.29560988 0.06109902]
  [0.73831642 0.27354937 0.13292185]
  [0.12711205 0.2449337  0.72323656]]]


## Restricted Least Squares

Given the following equation:


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$


1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>
2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

In [4]:
import pandas as pd
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

In [5]:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

#### ANSWER 3.1
We create four elements. An array for de dependent variable named $y$, a matrix that contains al the independent variables named $x$, and a matrix and a vector for the restrictions, named $L$ and $r$ respectively.<br>
Using this elements we estimate the coefficients with the RLS method. This estimator is computed as the OLS estimator plus a restriction adjustment. We apply the formula for those two elements provided in the link that was shared.

In [6]:
y = np.log(ct)
x = np.column_stack([np.log(q), np.log(np.power(q,2)/2), np.log(q)*np.log(p1), np.log(q)*np.log(p2), np.log(q)*np.log(p3),
                     np.log(p1), np.log(p2), np.log(p3), np.power(np.log(p1),2)/2, np.power(np.log(p2),2)/2,
                     np.power(np.log(p3),2)/2, np.log(p1)*np.log(p2)/2, np.log(p1)*np.log(p3)/2, np.log(p2)*np.log(p3)/2])

In [7]:
L = np.vstack(([0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
               [0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
               [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.],
               [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1.],
               [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1.]))
r = np.array([1., 0., 0., 0., 0.])

In [8]:
beta_ols = np.linalg.inv(np.transpose(x)@x)@np.transpose(x)@y
rest_adj = - np.linalg.inv(np.transpose(x)@x)@np.transpose(L)@np.linalg.inv(L@np.linalg.inv(np.transpose(x)@x)@np.transpose(L))@(L@beta_ols-r)

In [9]:
beta_rls = beta_ols + rest_adj
print(beta_rls)

[-21.61994834  11.14456446   0.04441069   0.04392711  -0.0883378
   0.32795529  -0.04466282   0.71670753  -0.08310674  -0.17825496
   0.2726186    0.26699015  -0.18388341  -0.08873519]


#### ANSWER 3.2
We estimate the covariance matrix of the RLS estimator as the difference between the covariance matrix of the OLS estimator and an extra element that we can named "difference in the variances".<br>
Before that we estimate the regression residuals and the error variance, both are required components to compute the elements mentioned above. Again, all the formulas were taken from the link shared.

In [10]:
residual = y - x@beta_rls
error_variance = np.transpose(residual)@residual/(len(y)-len(beta_rls)-1+len(r))

In [11]:
variance_ols = error_variance*np.linalg.inv(np.transpose(x)@x)
difference_variance = error_variance*np.linalg.inv(np.transpose(x)@x)@np.transpose(L)@np.linalg.inv(L@np.linalg.inv(np.transpose(x)@x)@np.transpose(L))@L@np.linalg.inv(np.transpose(x)@x)

In [12]:
variance_rls = variance_ols - difference_variance
print(variance_rls)

[[ 1.54786253e+02 -7.76797801e+01  9.43932719e-02 -1.35684115e-01
   4.12908432e-02 -1.94071145e+01  1.02394789e+01  9.16763562e+00
   2.52849217e+00 -5.95747594e-01 -5.23562813e+00 -3.58418635e+00
   1.05569418e+00  4.17993395e+00]
 [-7.76797801e+01  3.89919245e+01 -5.04744781e-02  7.03387955e-02
  -1.98643174e-02  9.71687470e+00 -5.13543795e+00 -4.58143675e+00
  -1.26239133e+00  2.94886735e-01  2.61599063e+00  1.79174762e+00
  -5.29356283e-01 -2.08663435e+00]
 [ 9.43932719e-02 -5.04744781e-02  1.26229016e-03 -8.06722938e-04
  -4.55567219e-04 -3.10870921e-03  4.02670874e-03 -9.17999528e-04
  -1.01437868e-03  1.35082576e-03  1.09435247e-03  3.78952691e-04
   6.35425987e-04 -1.72977845e-03]
 [-1.35684115e-01  7.03387955e-02 -8.06722938e-04  1.44446058e-03
  -6.37737638e-04  1.12490656e-02 -1.34757351e-02  2.22666955e-03
  -7.28475235e-04  1.42858170e-04  9.91663404e-04  7.88640234e-04
  -6.01649997e-05 -9.31498405e-04]
 [ 4.12908432e-02 -1.98643174e-02 -4.55567220e-04 -6.37737638e-04
  

# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [2]:
# read REC0111 data
!pip install savReaderWriter

     ---------------------------------------- 50.9/50.9 MB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for savReaderWriter: filename=savReaderWriter-3.4.2-py3-none-any.whl size=51142030 sha256=7566765ca89435d9c168f1aab587fd36748aa5df034e8e893f292c85bad0eb8e
  Stored in directory: c:\users\dell\appdata\local\pip\cache\wheels\cb\a1\bf\2b0abba03732dda64bac1510f20b5d34cae4fe071dc0699336
Successfully built savReaderWriter


In [8]:
!pip install pyreadstat

     ---------------------------------------- 2.4/2.4 MB 5.4 MB/s eta 0:00:00


In [51]:
import numpy as np
import pandas as pd

In [65]:
import savReaderWriter as sav
rec1 = pd.read_spss( "C:/Users/DELL/Downloads/_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( "C:/Users/DELL/Downloads/_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [66]:
dict_varlabels

{'ID1': 'Año',
 'HHID': 'Identificación Cuestionario del Hogar',
 'CASEID': 'Identificación Cuestionario Individual',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V013': 'Edad actual por grupos de 5 años',
 'V014': 'Integridad de la información para la fecha de nacimiento ',
 'V015': 'Resultado entrevista individual',
 'V017': 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'V018': 'Columna del mes de la entrevista',
 'V019': 'Duración del calendario',
 'V019A': 'Número de columnas de calendario',
 'V020': 'Muestra alguna vez casada',
 'V021': 'Unidad de muestreo primar

### Answer 4.1
First, we select the 'CASEID' columna of the dataframe and check if the values of it are unique using .is_unique. It shows us a boolean showing that they all are unique values.

In [67]:
rec1['CASEID'].is_unique

True

### Answer 4.2
First, we define that rec1 is the dataframe that we are going to use. Then, we set 'CASEID' as the index of the index.

In [68]:
rec1.set_index('CASEID')
rec1

ID1             HHID              CASEID    V001  V002  V003  \
0      2019.0        000100201        000100201  2     1.0   2.0   2.0   
1      2019.0        000100201        000100201  3     1.0   2.0   3.0   
2      2019.0        000102801        000102801  2     1.0  28.0   2.0   
3      2019.0        000102801        000102801  6     1.0  28.0   6.0   
4      2019.0        000104801        000104801  2     1.0  48.0   2.0   
...       ...              ...                 ...     ...   ...   ...   
38330  2019.0        325406201        325406201  2  3254.0  62.0   2.0   
38331  2019.0        325406301        325406301  2  3254.0  63.0   2.0   
38332  2019.0        325407001        325407001  2  3254.0  70.0   2.0   
38333  2019.0        325407201        325407201  2  3254.0  72.0   2.0   
38334  2019.0        325407401        325407401  2  3254.0  74.0   2.0   

         V004    V007    V008  V009  ...  QD333_4  QD333_5  QD333_6  UBIGEO  \
0         1.0  2019.0  1434.0   4.0  ...       No       No       No  010101   
1         1.0  2019.0  1434.0   1.0  ...       No       No       No  010101   
2         1.0  2019.0  1434.0   6.0  ...       No       No       No  010101   
3         1.0  2019.0  1434.0   3.0  ...       No       No       No  010101   
4         1.0  2019.0  1434.0   5.0  ...       No       No       No  010101   
...       ...     ...     ...   ...  ...      ...      ...      ...     ...   
38330  3254.0  2019.0  1440.0  12.0  ...       No       No       No  250401   
38331  3254.0  2019.0  1440.0   6.0  ...       No       No       No  250401   
38332  3254.0  2019.0  1440.0   7.0  ...       No       No       No  250401   
38333  3254.0  2019.0  1440.0  12.0  ...       No       No       No  250401   
38334  3254.0  2019.0  1440.0  10.0  ...       No       No       No  250401   

        V022      V005          V190      V191  \
0        3.0  154803.0          Rico  1.234450   
1        3.0  154803.0          Rico  1.234450   
2        3.0  154803.0          Rico  1.295611   
3        3.0  154803.0          Rico  1.295611   
4        3.0  154803.0        Pobrer -0.256431   
...      ...       ...           ...       ...   
38330  249.0  244995.0  El más pobre -1.750187   
38331  249.0  244995.0  El más pobre -1.676861   
38332  249.0  459792.0  El más pobre -1.585333   
38333  249.0  459792.0  El más pobre -1.650159   
38334  249.0  244995.0  El más pobre -1.644720   

                                        mujeres12a49  NCONGLOME  
0                    Mujeres de 15 a 49 años de edad     7065.0  
1      Mujeres de 12 a 14 de edad, nunca embarazadas     7065.0  
2                    Mujeres de 15 a 49 años de edad     7065.0  
3                    Mujeres de 15 a 49 años de edad     7065.0  
4                    Mujeres de 15 a 49 años de edad     7065.0  
...                                              ...        ...  
38330                Mujeres de 15 a 49 años de edad    15783.0  
38331                Mujeres de 15 a 49 años de edad    15783.0  
38332                Mujeres de 15 a 49 años de edad    15783.0  
38333                Mujeres de 15 a 49 años de edad    15783.0  
38334                Mujeres de 15 a 49 años de edad    15783.0  

[38335 rows x 105 columns]

### Answer 3
First, we delimited the dataframe to those who are 15-30 years old using the 'V012' variable and then to those who live in Urban areas using the 'V102' variable.  All of this using conditionals in parenthesis so to respect the rank order. 

In [69]:
rec1 = rec1[(rec1['V012'] > 14 ) & (rec1['V012'] < 31 ) & (rec1['V102'] == 'Urbano')]
rec1

ID1             HHID              CASEID    V001   V002  V003  \
4      2019.0        000104801        000104801  2     1.0   48.0   2.0   
5      2019.0        000113601        000113601  2     1.0  136.0   2.0   
8      2019.0        000116701        000116701  1     1.0  167.0   1.0   
9      2019.0        000119101        000119101  1     1.0  191.0   1.0   
12     2019.0        000203001        000203001  2     2.0   30.0   2.0   
...       ...              ...                 ...     ...    ...   ...   
38162  2019.0        324202401        324202401  2  3242.0   24.0   2.0   
38163  2019.0        324202501        324202501  3  3242.0   25.0   3.0   
38164  2019.0        324203901        324203901  1  3242.0   39.0   1.0   
38165  2019.0        324204501        324204501  2  3242.0   45.0   2.0   
38170  2019.0        324206901        324206901  3  3242.0   69.0   3.0   

         V004    V007    V008  V009  ...  QD333_4  QD333_5  QD333_6  UBIGEO  \
4         1.0  2019.0  1434.0   5.0  ...       No       No       No  010101   
5         1.0  2019.0  1434.0  11.0  ...       No       No       No  010101   
8         1.0  2019.0  1434.0   6.0  ...       No       No       No  010101   
9         1.0  2019.0  1434.0   9.0  ...       No       No       No  010101   
12        2.0  2019.0  1432.0   5.0  ...       No       No       No  010101   
...       ...     ...     ...   ...  ...      ...      ...      ...     ...   
38162  3242.0  2019.0  1436.0   2.0  ...       No       No       No  250302   
38163  3242.0  2019.0  1436.0   5.0  ...       No       No       No  250302   
38164  3242.0  2019.0  1436.0   8.0  ...       No       No       No  250302   
38165  3242.0  2019.0  1436.0   5.0  ...       No       No       No  250302   
38170  3242.0  2019.0  1436.0  10.0  ...       No       No       No  250302   

        V022      V005          V190      V191  \
4        3.0  154803.0        Pobrer -0.256431   
5        3.0  154803.0      Más rico  1.435294   
8        3.0  154803.0      Más rico  1.672440   
9        3.0  154803.0        Pobrer  0.234148   
12       2.0   65298.0        Pobrer -0.196449   
...      ...       ...           ...       ...   
38162  248.0  203603.0        Pobrer -0.463931   
38163  248.0  567613.0        Pobrer -0.576118   
38164  248.0  567613.0  El más pobre -0.940013   
38165  248.0  203603.0  El más pobre -0.656011   
38170  248.0  567613.0        Pobrer -0.574662   

                          mujeres12a49  NCONGLOME  
4      Mujeres de 15 a 49 años de edad     7065.0  
5      Mujeres de 15 a 49 años de edad     7065.0  
8      Mujeres de 15 a 49 años de edad     7065.0  
9      Mujeres de 15 a 49 años de edad     7065.0  
12     Mujeres de 15 a 49 años de edad     7068.0  
...                                ...        ...  
38162  Mujeres de 15 a 49 años de edad    45556.0  
38163  Mujeres de 15 a 49 años de edad    45556.0  
38164  Mujeres de 15 a 49 años de edad    45556.0  
38165  Mujeres de 15 a 49 años de edad    45556.0  
38170  Mujeres de 15 a 49 años de edad    45556.0  

[12236 rows x 105 columns]

### Answer 4
First, we define the new column named 'Month' to get the name of month. After this, we condition its values to the ones in the V009 value and puts just use the first three letters of the month in this column using the function if and else. 

In [79]:
rec1['Month'] = ['JAN' if x==1 else 'FEB' if x==2 else 'MAR' if x==3 else 'APR' if x==4 else 'MAY' if x==5 else 'JUN' if x==6 else 'JUL' if x==7 else 'AUG' if x==8 else 'SEP' if x==9 else 'OCT' if x==10 else 'NOV' if x==11 else 'DEC' for x in rec1['V009']]
rec1

C:\Users\DELL\AppData\Local\Temp\ipykernel_19640\3029215485.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rec1['Month'] = ['JAN' if x==1 else 'FEB' if x==2 else 'MAR' if x==3 else 'APR' if x==4 else 'MAY' if x==5 else 'JUN' if x==6 else 'JUL' if x==7 else 'AUG' if x==8 else 'SEP' if x==9 else 'OCT' if x==10 else 'NOV' if x==11 else 'DEC' for x in rec1['V009']]


ID1             HHID              CASEID    V001   V002  V003  \
4      2019.0        000104801        000104801  2     1.0   48.0   2.0   
5      2019.0        000113601        000113601  2     1.0  136.0   2.0   
8      2019.0        000116701        000116701  1     1.0  167.0   1.0   
9      2019.0        000119101        000119101  1     1.0  191.0   1.0   
12     2019.0        000203001        000203001  2     2.0   30.0   2.0   
...       ...              ...                 ...     ...    ...   ...   
38162  2019.0        324202401        324202401  2  3242.0   24.0   2.0   
38163  2019.0        324202501        324202501  3  3242.0   25.0   3.0   
38164  2019.0        324203901        324203901  1  3242.0   39.0   1.0   
38165  2019.0        324204501        324204501  2  3242.0   45.0   2.0   
38170  2019.0        324206901        324206901  3  3242.0   69.0   3.0   

         V004    V007    V008  V009  ...  QD333_5  QD333_6  UBIGEO   V022  \
4         1.0  2019.0  1434.0   5.0  ...       No       No  010101    3.0   
5         1.0  2019.0  1434.0  11.0  ...       No       No  010101    3.0   
8         1.0  2019.0  1434.0   6.0  ...       No       No  010101    3.0   
9         1.0  2019.0  1434.0   9.0  ...       No       No  010101    3.0   
12        2.0  2019.0  1432.0   5.0  ...       No       No  010101    2.0   
...       ...     ...     ...   ...  ...      ...      ...     ...    ...   
38162  3242.0  2019.0  1436.0   2.0  ...       No       No  250302  248.0   
38163  3242.0  2019.0  1436.0   5.0  ...       No       No  250302  248.0   
38164  3242.0  2019.0  1436.0   8.0  ...       No       No  250302  248.0   
38165  3242.0  2019.0  1436.0   5.0  ...       No       No  250302  248.0   
38170  3242.0  2019.0  1436.0  10.0  ...       No       No  250302  248.0   

           V005          V190      V191                     mujeres12a49  \
4      154803.0        Pobrer -0.256431  Mujeres de 15 a 49 años de edad   
5      154803.0      Más rico  1.435294  Mujeres de 15 a 49 años de edad   
8      154803.0      Más rico  1.672440  Mujeres de 15 a 49 años de edad   
9      154803.0        Pobrer  0.234148  Mujeres de 15 a 49 años de edad   
12      65298.0        Pobrer -0.196449  Mujeres de 15 a 49 años de edad   
...         ...           ...       ...                              ...   
38162  203603.0        Pobrer -0.463931  Mujeres de 15 a 49 años de edad   
38163  567613.0        Pobrer -0.576118  Mujeres de 15 a 49 años de edad   
38164  567613.0  El más pobre -0.940013  Mujeres de 15 a 49 años de edad   
38165  203603.0  El más pobre -0.656011  Mujeres de 15 a 49 años de edad   
38170  567613.0        Pobrer -0.574662  Mujeres de 15 a 49 años de edad   

      NCONGLOME  Month  
4        7065.0    MAY  
5        7065.0    NOV  
8        7065.0    JUN  
9        7065.0    SEP  
12       7068.0    MAY  
...         ...    ...  
38162   45556.0    FEB  
38163   45556.0    MAY  
38164   45556.0    AUG  
38165   45556.0    MAY  
38170   45556.0    OCT  

[12236 rows x 106 columns]