# Parte 2 – Tipos de datos y estructuras de datos  
Este notebook contiene la **Parte 2** (preguntas 6–8) resueltas, con explicaciones breves y código ejecutable.


## 6. Declarar variables de distintos tipos y mostrar su tipo

Crea una variable para cada tipo: `int`, `float`, `string`, `bool`. Luego imprime el tipo con `type()`.


In [33]:
# 6) Variables y sus tipos
# int
entero = 42  

# float
flotante = 3.14159  

# string
cadena = "Hola grupo 7"

# bool
booleano = True           

# Impresion de las variables y sus tipos
print(entero, type(entero))
print(flotante, type(flotante))
print(cadena, type(cadena))
print(booleano, type(booleano))

42 <class 'int'>
3.14159 <class 'float'>
Hola grupo 7 <class 'str'>
True <class 'bool'>


## 7. Lista con elementos heterogéneos y operaciones

Crear una lista con:  
- Una cadena  
- Un valor booleano  
- Dos valores numéricos (cualquier tipo)  
- Una **lista de dos cadenas** con tus artistas musicales favoritos  

Luego:  
- Accede al primer y al último elemento  
- Agrega una nueva cadena  
- Elimina el valor booleano


In [2]:
# 7) Lista y operaciones
elementos = [
    "Python",           # cadena
    True,               # booleano
    2025,               # numérico
    3.14,               # numérico
    ["Alex Zurdo", "Redimidos"]  # lista de dos cadenas 
            ]

print(elementos)

['Python', True, 2025, 3.14, ['Alex Zurdo', 'Redimidos']]


In [3]:
elementos[-1]

['Alex Zurdo', 'Redimidos']

In [4]:
# Acceso al primer y último elemento
primer = elementos[0]
ultimo = elementos[-1]
print("Primer elemento:", primer)
print("Último elemento:", ultimo)



Primer elemento: Python
Último elemento: ['Alex Zurdo', 'Redimidos']


In [5]:
# Agregar una nueva cadena
elementos.append("nuevo elemento")
print("Tras append:", elementos)



Tras append: ['Python', True, 2025, 3.14, ['Alex Zurdo', 'Redimidos'], 'nuevo elemento']


In [6]:
# Eliminar el valor booleano (si está presente)
if True in elementos:
    elementos.remove(True)
print(elementos)

['Python', 2025, 3.14, ['Alex Zurdo', 'Redimidos'], 'nuevo elemento']


## 8. Tupla con distintos tipos y demostración de inmutabilidad

Define una tupla que contenga:  
- Una cadena  
- Un booleano  
- **Una tupla** con tres valores numéricos (de cualquier tipo)  

Explica por qué una tupla es **inmutable** e intenta modificar un elemento para mostrar el error.


In [7]:
# 8) Tuplas e inmutabilidad
tupla = ("Lima", False, (10, 20.5, -3))

print("Tupla original:", tupla)


Tupla original: ('Lima', False, (10, 20.5, -3))


In [8]:
explicacion = (
    "Las tuplas son inmutables: una vez creadas, no es posible realizar cambios, reasignar, agregar o eliminar sus elementos"
    "Esto permite que se usen como claves en diccionarios (si sus elementos también son inmutables)"
    " Algunos beneficios pueden ser que garantiza que su contenido no cambie accidentalmente."
)
print(explicacion)



Las tuplas son inmutables: una vez creadas, no es posible realizar cambios, reasignar, agregar o eliminar sus elementosEsto permite que se usen como claves en diccionarios (si sus elementos también son inmutables) Algunos beneficios pueden ser que garantiza que su contenido no cambie accidentalmente.


In [9]:
# Cuando intento de modificar (debe lanzar Ocurrió un error)
try:
    tupla[0] = "Cusco"
except:
    print("Ocurrió un error")

Ocurrió un error


## 9. Función `movie_summary(movies_dict)`

Dado un diccionario de películas con la forma:  
```python
movies = {
    "Inception": {"year": 2010, "genre": "Sci-Fi"},
    "Parasite": {"year": 2019, "genre": "Drama"},
    "Whiplash": {"year": 2014, "genre": "Drama"}
}
```
La función debe devolver una **lista** de oraciones:  
`"La película Inception pertenece al género Sci-Fi y se estrenó en 2010."`

In [10]:
# Declaración de variables

# definir movie
movies = {
    "Inception": {"year": 2010, "genre": "Sci-Fi"},
    "Parasite": {"year": 2019, "genre": "Drama"},
    "Whiplash": {"year": 2014, "genre": "Drama"}
}

# uso de la funcion movie_summary(movies)

def movie_summary(movies_dict):
    resumen = []
    for titulo, info in movies_dict.items():
        frase = f"La película {titulo} pertenece al género {info['genre']} y fue lanzada en {info['year']}."
        resumen.append(frase)
    return resumen


# Usar la función
for linea in movie_summary(movies):
    print(linea)

La película Inception pertenece al género Sci-Fi y fue lanzada en 2010.
La película Parasite pertenece al género Drama y fue lanzada en 2019.
La película Whiplash pertenece al género Drama y fue lanzada en 2014.


## 10. Usando NumPy , genere una matriz de 4x4 con números enteros aleatorios entre 1 y 100.
Luego calcule:

La media por columna

La suma de los valores en la diagonal principal

In [11]:
# 10) Cálculos con NumPy
import numpy as np

matriz = np.random.randint(1, 101, size=(4, 4))
print("Matriz 4x4 aleatoria:", matriz)

media_por_columna = matriz.mean(axis=0)
suma_diagonal = np.trace(matriz)

print("Media por columna:", media_por_columna)
print("Suma de la diagonal principal:", suma_diagonal)

Matriz 4x4 aleatoria: [[77 69  4 92]
 [13 61 92 75]
 [74  7 28 23]
 [29 47 75 48]]
Media por columna: [48.25 46.   49.75 59.5 ]
Suma de la diagonal principal: 214


In [12]:
# Pregunta 11

In [13]:
import pandas as pd
import numpy as np

In [14]:
#we create a list of grades 
grades = [15, 17, 20, 11, 13, 18, 19]
grades

[15, 17, 20, 11, 13, 18, 19]

In [15]:
#we create a list of students
students = ["Ana", "Jorge", "Valeria", "Luis", "María", "Carlos", "Sofía"]
students

['Ana', 'Jorge', 'Valeria', 'Luis', 'María', 'Carlos', 'Sofía']

In [16]:
#this scrop creates a DataFrame with the grades and students
grades_series = pd.Series(grades, index=students)
grades_series

Ana        15
Jorge      17
Valeria    20
Luis       11
María      13
Carlos     18
Sofía      19
dtype: int64

# Pregunta 12
## We calculate the average grade, highest and lowest student

In [35]:
#we calculate the average of the grades
average = grades_series.mean()
average

16.142857142857142

In [19]:
#we calculate the  student with the highest grade
highest_student = grades_series.idxmax()
highest_student

'Valeria'

In [20]:
highest_grade = grades_series.max()
highest_grade

20

In [21]:
#we calculate the student with the lowest grade 
lowest_student = grades_series.idxmin()
lowest_student

'Luis'

In [22]:
lowest_grade = grades_series.min()
lowest_grade

11

In [23]:
print("El promedio de notas es de", average)
print("La nota más alta", highest_grade, "es de", highest_student)
print("La nota más baja", lowest_grade, "es de", lowest_student)

El promedio de notas es de 16.142857142857142
La nota más alta 20 es de Valeria
La nota más baja 11 es de Luis


## Pregunta 13
 we create the a dictionary of countries and their capitals.

In [36]:

countries_capitals = {
    "Peru": "Lima",
    "Argentina": "Buenos Aires",
    "Brazil": "Brasilia",
    "Colombia": "Bogota",
    "Mexico": "Ciudad De Mexico",
    "Chile": "Santiago",
    "Ecuador": "Quito",
    "Bolivia": "La Paz",
    "Venezuela": "Caracas",
    "Uruguay": "Montevideo",
    "Paraguay": "Asuncion",
    "Canada": "Ottawa",
    "USA": "Washington",
    "France": "Paris",
    "Germany": "Berlin",
    "Italy": "Rome",
    "Spain": "Madrid",
    "Portugal": "Lisbon",
    "UK": "London",
    "Japan": "Tokyo" }
countries_capitals

{'Peru': 'Lima',
 'Argentina': 'Buenos Aires',
 'Brazil': 'Brasilia',
 'Colombia': 'Bogota',
 'Mexico': 'Ciudad De Mexico',
 'Chile': 'Santiago',
 'Ecuador': 'Quito',
 'Bolivia': 'La Paz',
 'Venezuela': 'Caracas',
 'Uruguay': 'Montevideo',
 'Paraguay': 'Asuncion',
 'Canada': 'Ottawa',
 'USA': 'Washington',
 'France': 'Paris',
 'Germany': 'Berlin',
 'Italy': 'Rome',
 'Spain': 'Madrid',
 'Portugal': 'Lisbon',
 'UK': 'London',
 'Japan': 'Tokyo'}

In [26]:
capitals_series = pd.Series(countries_capitals)
capitals_series

Peru                     Lima
Argentina        Buenos Aires
Brazil               Brasilia
Colombia               Bogota
Mexico       Ciudad De Mexico
Chile                Santiago
Ecuador                 Quito
Bolivia                La Paz
Venezuela             Caracas
Uruguay            Montevideo
Paraguay             Asuncion
Canada                 Ottawa
USA                Washington
France                  Paris
Germany                Berlin
Italy                    Rome
Spain                  Madrid
Portugal               Lisbon
UK                     London
Japan                   Tokyo
dtype: object

In [27]:
#we filter the data
filtered = capitals_series[capitals_series.str.len() > 6]
filtered

Argentina        Buenos Aires
Brazil               Brasilia
Mexico       Ciudad De Mexico
Chile                Santiago
Venezuela             Caracas
Uruguay            Montevideo
Paraguay             Asuncion
USA                Washington
dtype: object

In [28]:
print("      Todas las capitales")
print(capitals_series)

      Todas las capitales
Peru                     Lima
Argentina        Buenos Aires
Brazil               Brasilia
Colombia               Bogota
Mexico       Ciudad De Mexico
Chile                Santiago
Ecuador                 Quito
Bolivia                La Paz
Venezuela             Caracas
Uruguay            Montevideo
Paraguay             Asuncion
Canada                 Ottawa
USA                Washington
France                  Paris
Germany                Berlin
Italy                    Rome
Spain                  Madrid
Portugal               Lisbon
UK                     London
Japan                   Tokyo
dtype: object


In [29]:
print("Capitales con más de 6 letras")
print(filtered)

Capitales con más de 6 letras
Argentina        Buenos Aires
Brazil               Brasilia
Mexico       Ciudad De Mexico
Chile                Santiago
Venezuela             Caracas
Uruguay            Montevideo
Paraguay             Asuncion
USA                Washington
dtype: object


## Pregunta 14

We create the Serie "flowers"

In [37]:
flowers = pd.Series (["rosa", "girasol", "margarita", "dalia", "clavel", "jazmin", "orquidea", "lirio", "tulipan"])
print(".Flores diversas.")
flowers

.Flores diversas.


0         rosa
1      girasol
2    margarita
3        dalia
4       clavel
5       jazmin
6     orquidea
7        lirio
8      tulipan
dtype: object

In [31]:
#convertimos a mayúsculas
flowersmay = flowers.apply(str.upper)
flowersmay

0         ROSA
1      GIRASOL
2    MARGARITA
3        DALIA
4       CLAVEL
5       JAZMIN
6     ORQUIDEA
7        LIRIO
8      TULIPAN
dtype: object

In [32]:
print ("Flores diversas en mayúscula")
print (flowersmay)

Flores diversas en mayúscula
0         ROSA
1      GIRASOL
2    MARGARITA
3        DALIA
4       CLAVEL
5       JAZMIN
6     ORQUIDEA
7        LIRIO
8      TULIPAN
dtype: object
