## 9. Función `movie_summary(movies_dict)`

Dado un diccionario de películas con la forma:  
```python
movies = {
    "Inception": {"year": 2010, "genre": "Sci-Fi"},
    "Parasite": {"year": 2019, "genre": "Drama"},
    "Whiplash": {"year": 2014, "genre": "Drama"}
}
```
La función debe devolver una **lista** de oraciones:  
`"La película Inception pertenece al género Sci-Fi y se estrenó en 2010."`


In [17]:
# Declaración de variables

# definir movie
movies = {
    "Inception": {"year": 2010, "genre": "Sci-Fi"},
    "Parasite": {"year": 2019, "genre": "Drama"},
    "Whiplash": {"year": 2014, "genre": "Drama"}
}

# uso de la funcion movie_summary(movies)

def movie_summary(movies_dict):
    resumen = []
    for titulo, info in movies_dict.items():
        frase = f"La película {titulo} pertenece al género {info['genre']} y fue lanzada en {info['year']}."
        resumen.append(frase)
    return resumen


# Usar la función
for linea in movie_summary(movies):
    print(linea)


La película Inception pertenece al género Sci-Fi y fue lanzada en 2010.
La película Parasite pertenece al género Drama y fue lanzada en 2019.
La película Whiplash pertenece al género Drama y fue lanzada en 2014.


## 10. Usando NumPy , genere una matriz de 4x4 con números enteros aleatorios entre 1 y 100.
Luego calcule:

La media por columna

La suma de los valores en la diagonal principal


In [23]:
# 10) Cálculos con NumPy
import numpy as np

matriz = np.random.randint(1, 101, size=(4, 4))
print("Matriz 4x4 aleatoria:", matriz)

media_por_columna = matriz.mean(axis=0)
suma_diagonal = np.trace(matriz)

print("Media por columna:", media_por_columna)
print("Suma de la diagonal principal:", suma_diagonal)

Matriz 4x4 aleatoria: [[95 73  7 68]
 [89  2  9 61]
 [53 54 20 39]
 [92 83 41 84]]
Media por columna: [82.25 53.   19.25 63.  ]
Suma de la diagonal principal: 201
