# Assignment 1 – Part 2: Data Types and Data Structures

In [18]:
# P6

# Variables de distintos tipos
x_int = 10
x_float = 3.14
x_str = "Hola Python"
x_bool = True

print(type(x_int))
print(type(x_float))
print(type(x_str))
print(type(x_bool))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [19]:
# P7

# Lista con varios elementos
my_list = [
    "cadena de texto",
    False,
    42,
    7.5,
    ["Bad Bunny", "Shakira"]
]

# Acceder al primer y último elemento
print("Primer elemento:", my_list[0])
print("Último elemento:", my_list[-1])

# Agregar un nuevo string
my_list.append("Nuevo elemento")
print("Lista con nuevo elemento:", my_list)

# Eliminar el booleano
my_list.remove(False)
print("Lista sin el booleano:", my_list)

Primer elemento: cadena de texto
Último elemento: ['Bad Bunny', 'Shakira']
Lista con nuevo elemento: ['cadena de texto', False, 42, 7.5, ['Bad Bunny', 'Shakira'], 'Nuevo elemento']
Lista sin el booleano: ['cadena de texto', 42, 7.5, ['Bad Bunny', 'Shakira'], 'Nuevo elemento']


In [20]:
# P8

# Definición de tupla
my_tuple = (
    "Python",
    True,
    (1, 2, 3)
)

print("Mi tupla:", my_tuple)

# Explicación: una tupla es inmutable (no se puede cambiar después de creada).
# Intentar modificarla dará error:
try:
    my_tuple[0] = "Java"
except TypeError as e:
    print("Error al modificar la tupla:", e)

Mi tupla: ('Python', True, (1, 2, 3))
Error al modificar la tupla: 'tuple' object does not support item assignment


In [22]:
# P9

# Función movie_summary
def movie_summary(movies):
    summaries = []
    for title, info in movies.items():
        summaries.append("The movie {title} belongs to the {info['genre']} genre and was released in {info['year']}.")
    return summaries

movies = {
  "Inception": {"year": 2010, "genre": "Sci-Fi"},
  "Parasite": {"year": 2019, "genre": "Drama"},
  "Whiplash": {"year": 2014, "genre": "Drama"}
}

movie_summary(movies)

['The movie Inception belongs to the Sci-Fi genre and was released in 2010.',
 'The movie Parasite belongs to the Drama genre and was released in 2019.',
 'The movie Whiplash belongs to the Drama genre and was released in 2014.']

In [23]:
# P10

# Numpy: matriz 4x4 con enteros aleatorios
import numpy as np

matrix = np.random.randint(1, 101, size=(4, 4))
print("Matriz:\n", matrix)

# Media por columna
print("Media por columna:", matrix.mean(axis=0))

# Suma de la diagonal principal
print("Suma diagonal:", np.trace(matrix))

Matriz:
 [[52 42 43 14]
 [82  6 79 41]
 [42 23 31 41]
 [65 85  4 30]]
Media por columna: [60.25 39.   39.25 31.5 ]
Suma diagonal: 119
