# Assignment 1: Group 5

*Curso:* Fundamentos de Python

*Profesor:* Alexander Quispe  

*Fecha:* 24 de agosto de 2025  

---

## Integrantes:

- Lesly León  
- Susan Montalvo  
- Vivian Saurino  
- Esteban Quispitupa

## Parte 1

Repository maintainer: Susan Montalvo

1. Explain the difference between working on a branch and working directly on main. Why is it recommended to always use branches in collaborative projects? [1 pts]

Trabajar en main significa modificar directamente la rama principal, mientras que en un branch los cambios se realizan en paralelo y pueden incorporarse posteriormente, previa revisión. En ese sentido, es recomendable usar un branch, ya que evita afectar al main y facilita el trabajo colaborativo.

5. Explain in which cases a reviewer might reject the PR (e.g., code conflicts, formatting errors, failure to follow instructions, etc.).

Un revisor puede rechazar un Pull Request cuando detecta conflictos de código que impiden su integración al main, fallas en la ejecución del código, o cuando no se han seguido las instrucciones definidas para el proyecto. Asimismo, el rechazo puede darse si la documentación es insuficiente para comprender los cambios realizados, redundante o no aporta valor al desarrollo del repositorio.

## Parte 2

6. Declare a variable for each of the following types: int, float, string, and boolean.
Then print the type of each variable using the type() function.

In [3]:
an_int = 30

In [9]:
a_float = 2.50

In [11]:
a_string = "improve"

In [13]:
a_bool = True

In [17]:
print(type(an_int), type(a_float), type(a_string), type(a_bool))

<class 'int'> <class 'float'> <class 'str'> <class 'bool'>


7. Create a list with a string, a boolean, two numbers, and a sublist of two favorite artists; then access the first and last elements, add a string, and remove the boolean.

In [10]:
list = ["enero", True, 30, 1.8, ["Coldplay", "Adele"]]

Access the first element:

In [12]:
list[0]

'enero'

Access the last element:

In [14]:
list[-1]

['Coldplay', 'Adele']

Add a new string:

In [16]:
list.append("diciembre")
list

['enero', True, 30, 1.8, ['Coldplay', 'Adele'], 'diciembre']

Remove the boolean value:

In [18]:
list.remove(True)

In [33]:
list

['enero', 30, 1.8, ['Coldplay', 'Michael Jackson'], 'diciembre', 'diciembre']

8. Define a tuple, explain its immutability, and provide a demonstration of this property.

In [15]:
new_tupla = ("febrero", True, 18, 20.0, 1.5)

La tupla es inmutable porque, una vez creada, sus elementos no pueden modificarse, agregarse ni eliminarse. En caso de intentarlo, se generará un TypeError, indicando que la tupla no admite la asignación de elementos.

In [16]:
try:
    new_tupla[0] = "marzo"
except TypeError as e:
    print("Error al intentar modificar la tupla:", e)

Error al intentar modificar la tupla: 'tuple' object does not support item assignment


9. Write a Python function named movie_summary that takes as input a dictionary of movies, where each key is a movie title and each value is another dictionary containing the movie’s "year" and "genre".

In [7]:
movies = {
    "Grown Ups": {"year": 2010, "genre": "Comedy"},
    "Click": {"year": 2006, "genre": "Comedy"},
    "Just Go with It": {"year": 2011, "genre": "Comedy"}
}

def movie_summary(movies):
    summary_list = [] 
    for title, info in movies.items():
        sentence = f"The movie {title} belongs to the {info['genre']} genre and was released in {info['year']}."
        summary_list.append(sentence)
    return summary_list

result = movie_summary(movies)

for r in result:
    print(r)

The movie Grown Ups belongs to the Comedy genre and was released in 2010.
The movie Click belongs to the Comedy genre and was released in 2006.
The movie Just Go with It belongs to the Comedy genre and was released in 2011.


10. Using NumPy, generate a 4x4 matrix with random integers between 1 and 100.

In [8]:
!pip install numpy

In [9]:
import numpy as np
print(np.__version__)

2.1.3


In [10]:
import numpy as np

# Matriz 4x4 con enteros aleatorios entre 1 y 100
matrix = np.random.randint(1, 101, size=(4, 4))
print("Matriz generada:")
print(matrix)

# Media por columna
mean_per_column = np.mean(matrix, axis=0)
print("\nMedia por columna:")
print(mean_per_column)

# Suma de la diagonal principal
sum_diagonal = np.trace(matrix)
print("\nSuma de la diagonal principal:")
print(sum_diagonal)

Matriz generada:
[[90 70 21 64]
 [59 61 16 49]
 [14  3 79 78]
 [35 57 31 38]]

Media por columna:
[49.5  47.75 36.75 57.25]

Suma de la diagonal principal:
268


## Parte 3.

11. From the list of grades [15, 17, 20, 11, 13, 18, 19], create a Pandas Series assigning student names as the index 

In [4]:
import pandas as pd

In [5]:
grades = [15, 17, 20, 11, 13, 18, 19]
students = ["Estefania", "Antonella", "Viviana", "Henry", "Angel", "Lucía", "Katherin"]
grades_series = pd.Series(grades, index=students)
print("Aluumnos y notas:\n", grades_series)

Aluumnos y notas:
 Estefania    15
Antonella    17
Viviana      20
Henry        11
Angel        13
Lucía        18
Katherin     19
dtype: int64


12. Using the Series created in the previous step, calculate:

In [10]:
grades_series.mean()
print("promedio de notas:\n", grades_series.mean())

promedio de notas:
 16.142857142857142


In [11]:
print("Nota más alta:", grades_series.idxmax())
print("Nota más baja:", grades_series.idxmin())

Nota más alta: Viviana
Nota más baja: Henry


13. Create a Series from a dictionary of countries and their capitals. 
Filter and display only those countries whose capital has more than 6 letters.

In [13]:
countries_capitals = {"Peru": "Lima","Argentina": "Buenos Aires", "Chile": "Santiago", "Colombia": "Bogotá", "Mexico": "Ciudad de México"}
capitals_series = pd.Series(countries_capitals)
print("Países y capitales:\n", capitals_series, "\n")

Países y capitales:
 Peru                     Lima
Argentina        Buenos Aires
Chile                Santiago
Colombia               Bogotá
Mexico       Ciudad de México
dtype: object 



In [14]:
filtered_capitals = capitals_series[capitals_series.str.len() > 6]
print("Capitales con más de 6 letras:\n", filtered_capitals)

Capitales con más de 6 letras:
 Argentina        Buenos Aires
Chile                Santiago
Mexico       Ciudad de México
dtype: object


14. Create a Series containing several strings and convert all its elements to uppercase using the .apply(str.upper) method.


In [15]:
strings_series = pd.Series(["teclado", "mouse", "laptop", "impresora"])
print("strings_series:\n", strings_series)

strings_series:
 0      teclado
1        mouse
2       laptop
3    impresora
dtype: object


In [16]:
uppercase_strings=strings_series.apply(str.upper)
print("uppercasestrings_series:\n", uppercase_strings)

uppercasestrings_series:
 0      TECLADO
1        MOUSE
2       LAPTOP
3    IMPRESORA
dtype: object
