In [42]:
# Step 9 - Function movie_summary

movies = {
    "Grown Ups": {"year": 2010, "genre": "Comedy"},
    "Click": {"year": 2006, "genre": "Comedy"},
    "Just Go with It": {"year": 2011, "genre": "Comedy"}
}

def movie_summary(movies):
    summary_list = [] 
    for title, info in movies.items():
        sentence = f"The movie {title} belongs to the {info['genre']} genre and was released in {info['year']}."
        summary_list.append(sentence)
    return summary_list

result = movie_summary(movies)

for r in result:
    print(r)

The movie Grown Ups belongs to the Comedy genre and was released in 2010.
The movie Click belongs to the Comedy genre and was released in 2006.
The movie Just Go with It belongs to the Comedy genre and was released in 2011.


In [49]:
# Step 10 - NumPy
!pip install numpy

In [50]:
import numpy as np
print(np.__version__)

2.3.2


In [52]:
import numpy as np

# Matriz 4x4 con enteros aleatorios entre 1 y 100
matrix = np.random.randint(1, 101, size=(4, 4))
print("Matriz generada:")
print(matrix)

# Media por columna
mean_per_column = np.mean(matrix, axis=0)
print("\nMedia por columna:")
print(mean_per_column)

# Suma de la diagonal principal
sum_diagonal = np.trace(matrix)
print("\nSuma de la diagonal principal:")
print(sum_diagonal)

Matriz generada:
[[30 60 34  7]
 [82 29 11 64]
 [ 4 76  1 42]
 [ 4 88 30 41]]

Media por columna:
[30.   63.25 19.   38.5 ]

Suma de la diagonal principal:
101
