# 1 Assignment

## Excersice 1: Tuple

In [2]:
tuple1 = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
tuple2 = (10, 20, 30, 40, 50)

1. Print the first item of the `tuple1` object.

In [4]:
print ( "tuple1[0] =", tuple1 [0] )

tuple1[0] = apple


2. Print the last item of the `tuple1`

In [5]:
print ( "tuple1[-1] =", tuple1 [-1] )

tuple1[-1] = mango


3. Change the value "orange" for "pink grapefruit". Comment the output. **Hint: Is it possible?**

In [11]:
#Tuple objects are immutable. Once we have declared the contents of a tuple, we cannot modify its contents.
#For that reason, we cast it to a list to change the value.

list1 = list(tuple1)
i = list1.index("orange")
list1[i] = "pink grapefruit"
print(tuple(list1))

('apple', 'banana', 'cherry', 'pink grapefruit', 'kiwi', 'melon', 'mango')


4. Print the length of `tuple1`. 

In [3]:
print ( "tuple1[len] =", len (tuple1) )

tuple1[len] = 7


5. Sort `tuple2` in descending order.

In [4]:
sorted ( tuple2 , reverse = True )

[50, 40, 30, 20, 10]

6. Generate a new tuple object named as `tuple3` with the half values of `tuple2`.

In [5]:
tuple3 = tuple (tuple2i/2 for tuple2i in tuple2)
print ( tuple3 )

(5.0, 10.0, 15.0, 20.0, 25.0)


## Excersice 2: Lists

1. Show the indices of the np.nan values in the f_list list. We want to see this output: The indices 0, 1, 4, 7 have np.nan values. Hint: Use print function and f-strings to insert the indices values.

In [6]:
import numpy as np

In [7]:
f_list = ["Europe", np.nan , "America", "India", np.nan, "Pakistan", "np.nan"]

In [8]:
f2_list = [np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]

In [9]:
ind=[]
for i in range(0,len(f_list)):
    if f_list[i] is np.nan:
        ind.append(i)
print("The indices", ind, "have np.nan values")

The indices [1, 4] have np.nan values


In [10]:
ind=[]
for i in range(0,len(f2_list)):
    if f2_list[i] is np.nan:
        ind.append(i)
print("The indices", ind, "have np.nan values")

The indices [0, 1, 4, 7] have np.nan values


2. Replicate 4 times the values of the list `p2_list`. <br>
We expect an ouput like this <br>
`[ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]` **Hint: Use multiplication function in lists and see the output.**

In [21]:
p2_list = [ 2 , 3, 4, 5]

In [20]:
p2_list * 4

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]

**Another option:**

In [12]:
p2_list.extend(p2_list)
p2_list.extend(p2_list)

In [13]:
p2_list

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]

3. Print the length of f_list. Hint: Length function

In [14]:
print(len(f_list))

7


4. Print My teacher assistant is so boring. using text1 list. Hint: Use the join function


In [45]:
text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring.']

In [50]:
' '.join(text1)

'My teacher assistant is so boring.'

5. Print My TA is so boring, but is very funny. using text1 list.Hint: Use the join function, and extend method.

In [53]:
text1 = ['My', 'TA', 'is', 'so', 'boring,']
text2 = ['but', 'is', 'very', 'funny.']
text1.extend(text2)
' '.join(text1)

'My TA is so boring, but is very funny.'

6. Print
The max value of values1 is 86 and is located in the 0 index.
The min value of values1 is 0 and is located in the 7 index.
Hint: Use the f-string, min, and max functions.

In [59]:
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1 ] 

In [79]:
max_value = max(values1)
index_max = values1.index(max(values1))
min_value = min(values1)
index_min = values1.index(min(values1))

In [91]:
message1 = ( f"The max value of values1 is {max_value} and is located in the {index_max} index. ")
message2 = ( f"The min value of values1 is {min_value} and is located in the {index_min} index.")
print(message1, "\n")
print(message2, "\n")

The max value of values1 is 86 and is located in the 0 index.  

The min value of values1 is 0 and is located in the 7 index. 



## Excersice 3: Dictionaries

1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]` and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be store in a `list`.

In [3]:
import numpy as np
# Dict: Numbers
# Keys
Num = ['even_numbers','odd_numbers']
# Values
Range = [[np.arange(0,2002,2)], [np.arange(9001,19000,2)]]

# Return a dict:
Numbers = dict( zip( Num , Range ) )
print( Numbers )

{'even_numbers': [array([   0,    2,    4, ..., 1996, 1998, 2000])], 'odd_numbers': [array([ 9001,  9003,  9005, ..., 18995, 18997, 18999])]}


2. Check if `TA` is a key of your object created in exercise.

In [2]:
# New objetct:
Numb2 = Numbers.keys()
print( Numb2 )

# Check: TA is part of 
print( "TA" in Numb2 ) 
print( "even_numbers" in Numb2 )

dict_keys(['even_numbers', 'odd_numbers'])
False
True


3. Print the value of `brand` key of `car` dictionary.

In [3]:
# Dict:
car = {"brand": "Ford", "model": "Mustang", "year": 1964}

# Return the value of brand key:
car.get("brand")

'Ford'

4. Print all the the values of `brand` key of `car` dictionary.

In [4]:
# All the values of car dictionary:
car.values()

dict_values(['Ford', 'Mustang', 1964])

5. Print the max value of `friday` in `january` of `hr_sleep` dictionary.

In [5]:
# hr_sleep dict:
hr_sleep = {"january": {"wednesday": 7,
                        "thursday": 8,
                        "friday": [2, 2, 1, 2]},
            "february": {"saturday": 5,
                         "sunday": 10,
                         "monday": 8} }

# Return max value:
Hr_sleep1 = hr_sleep["january"]["friday"] 
Hr_sleep2 = max(Hr_sleep1)
print(Hr_sleep2)

2


6. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists.

In [6]:
# hr_sleep dict:
hr_sleep = {"january": {"wednesday": 7,
                        "thursday": 8,
                        "friday": [2, 2, 1, 2]},
            "february": {"saturday": 5,
                         "sunday": 10,
                         "monday": 8} }

# New key "march"
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

# Return dict with "march" key:
hr_sleep.update(march = dict(zip (week1 , values2) ))
print(hr_sleep)


{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]}, 'february': {'saturday': 5, 'sunday': 10, 'monday': 8}, 'march': {'monday': [2, 3, 4], 'sunday': 8}}


## Excersice 4: Numpy

1. Replace all the `even_numbers` in `np1` with 100.

In [109]:
np1 = np.arange( 200, 750)

In [111]:
print([x if x % 2 != 0 else 100 for x in np1])

[100, 201, 100, 203, 100, 205, 100, 207, 100, 209, 100, 211, 100, 213, 100, 215, 100, 217, 100, 219, 100, 221, 100, 223, 100, 225, 100, 227, 100, 229, 100, 231, 100, 233, 100, 235, 100, 237, 100, 239, 100, 241, 100, 243, 100, 245, 100, 247, 100, 249, 100, 251, 100, 253, 100, 255, 100, 257, 100, 259, 100, 261, 100, 263, 100, 265, 100, 267, 100, 269, 100, 271, 100, 273, 100, 275, 100, 277, 100, 279, 100, 281, 100, 283, 100, 285, 100, 287, 100, 289, 100, 291, 100, 293, 100, 295, 100, 297, 100, 299, 100, 301, 100, 303, 100, 305, 100, 307, 100, 309, 100, 311, 100, 313, 100, 315, 100, 317, 100, 319, 100, 321, 100, 323, 100, 325, 100, 327, 100, 329, 100, 331, 100, 333, 100, 335, 100, 337, 100, 339, 100, 341, 100, 343, 100, 345, 100, 347, 100, 349, 100, 351, 100, 353, 100, 355, 100, 357, 100, 359, 100, 361, 100, 363, 100, 365, 100, 367, 100, 369, 100, 371, 100, 373, 100, 375, 100, 377, 100, 379, 100, 381, 100, 383, 100, 385, 100, 387, 100, 389, 100, 391, 100, 393, 100, 395, 100, 397, 100, 399,

2. Create a 3x3 matrix with values ranging from 0 to 8. Hint: Use np.arange and np.reshape method.

In [10]:
h = np.arange(0,9,1)
h_2 = h.reshape(3, 3)
h_2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Consider an array Z = [1,2,3,4,5,6,7,8,9,10], generate an array R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]?.Hint: Use np.arange and np.concatenate

In [31]:
z = np.arange(1, 11)
print(z)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
group = 4
A=None

for i in range (len(z) - group + 1):
    M = np.asarray(z[i: i+group])
    
    if A is not None:
        A = np.concatenate((A, [M]), axis = 0)
    else:
        A = [M]
print(A)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


4. Create a 3x3x3 array with random values. Hint: Use np.random.random.

In [15]:
x = np.random.random((3,3,3))
print(x)

[[[6.34668167e-01 9.00286313e-01 3.82329302e-01]
  [1.52545569e-01 9.92760768e-01 2.02311070e-01]
  [1.71774843e-01 7.48361209e-02 6.01133029e-01]]

 [[3.16393135e-01 8.48151868e-01 6.03548055e-01]
  [4.60662762e-01 8.10539608e-06 8.23049257e-01]
  [8.16494924e-01 9.41291146e-01 8.10452008e-01]]

 [[6.80436620e-01 8.15158250e-01 9.30393401e-01]
  [2.73726178e-01 2.05981796e-01 9.48780429e-01]
  [4.42188098e-01 8.31847069e-01 4.36691336e-01]]]


5. Comment why this expression np.nan == np.nan is False. Hint: Use stackoverflow

In [22]:
np.nan==np.nan

False

In [23]:
(np.nan,)==(np.nan,)

True

6. Print the mean and standard deviation of np2. Hint: Use f-string, np.mean, and np.var methods.

In [34]:
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

In [43]:
np.mean(np2)

49.98157212489422

In [42]:
np.std(np2)

4.272628244263601

## Excersice 5: Restricted Least Squares

Get $\hat{\beta}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br>
For more information about restricted OLS [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).<br>


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$

Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the q, p1, p2, p3, CT numpies.

Get the covariance matrix $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$.

In [4]:
import pandas as pd
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

In [5]:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

## Solution
We consider for this problem the results of the parameters when we estimate an RLS.

Given the following equations:
\begin{eqnarray*}
Y &=&X\beta +\varepsilon  \\
L\beta  &=&r
\end{eqnarray*}

Based on: http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html

In [86]:
import numpy as np
# X data generation
n_data=ct.shape[0]
x0 = np.ones(n_data)
x1=np.log(q)
x2=0.5*np.log(q)**(2)
x3=np.log(q)*np.log(p1)
x4=np.log(q)*np.log(p2)
x5=np.log(q)*np.log(p3)
x6=np.log(p1)
x7=np.log(p2)
x8=np.log(p3)
x9=0.5*np.log(p1)**(2)
x10=0.5*np.log(p2)**(2)
x11=0.5*np.log(p3)**(2)
x12=0.5*np.log(p1)*np.log(p2)
x13=0.5*np.log(p1)*np.log(p3)
x14=0.5*np.log(p2)*np.log(p3)

X = np.hstack(( x0.reshape(-1, 1 ) , x1.reshape(-1, 1 ), x2.reshape(-1, 1 ), x3.reshape(-1, 1 ), x4.reshape(-1, 1 )
              , x5.reshape(-1, 1 ), x6.reshape(-1, 1 ), x7.reshape(-1, 1 ), x8.reshape(-1, 1 ), x9.reshape(-1, 1 )
              , x10.reshape(-1, 1 ), x11.reshape(-1, 1 ), x12.reshape(-1, 1 ), x13.reshape(-1, 1 ), x14.reshape(-1, 1 )))
X.shape

(158, 15)

In [87]:
Y=np.log(ct)

Given the last equation $\beta_ {ij} = \beta_ {ji}$, we replace this within the constraints that is: $ \beta_{21} = \beta_{12}; \beta_{31} = \beta_{13}$. Thus we construct the matrix L and r.

The restrictions that we will apply would be:
<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{12} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{13} + \beta_{23} + \beta_{33} &= 0 \\
\end{aligned}
$$

In [88]:
L= np.array([[0,0,0,0,0,0,1,1,1,0,0,0,0,0,0],[0,0,0,1,1,1,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,1,0,0,1,1,0]
             ,[0,0,0,0,0,0,0,0,0,0,1,0,1,0,1],[0,0,0,0,0,0,0,0,0,0,0,1,0,1,1]])
r= np.array([[1],[0],[0],[0],[0]])

The solution, we get it from
$$
\left[ 
\begin{array}{c}
\widehat{\beta }^{\left( RLS\right) } \\ 
\lambda 
\end{array}
\right] =\left[ 
\begin{array}{cc}
X^{T}X & L^{T} \\ 
L & 0
\end{array}
\right] ^{-1}\left[ 
\begin{array}{c}
X^{T}Y \\ 
r
\end{array}
\right] 
$$

$$
\left[ 
\begin{array}{c}
\widehat{\beta }^{\left( RLS\right) } \\ 
\lambda 
\end{array}
\right] =\underset{A}{\underbrace{\left[ 
\begin{array}{cc}
\underset{a11}{\underbrace{X^{T}X}} & \underset{a12}{\underbrace{L^{T}}} \\ 
\underset{a21}{\underbrace{L}} & \underset{a22}{\underbrace{0}}
\end{array}
\right] }}^{-1}\underset{B}{\underbrace{\left[ 
\begin{array}{c}
\underset{b1}{\underbrace{X^{T}Y}} \\ 
\underset{b2}{\underbrace{r}}
\end{array}
\right] }}
$$

In [131]:
a11 = np.dot(np.transpose(X),X)
a12 = np.transpose(L)
a21 = L
a22 = np.zeros( (L.shape[0], L.shape[0]) )
A1=np.hstack((a11,a12))
A2=np.hstack((a21,a22))
A=np.vstack((A1,A2))

In [132]:
b1 = np.dot(np.transpose(X),Y)
b2 = r
B=  np.vstack(( b1.reshape(-1, 1 ) , b2.reshape(-1, 1 ) ))

In [197]:
C=np.dot(np.linalg.inv(A),B)
Beta_RLS=C[0:15,:]
Beta_RLS

array([[-7.11120012e+00],
       [ 4.61367984e-01],
       [ 5.99553935e-02],
       [-4.35440193e-03],
       [ 3.67779793e-02],
       [-3.24235773e-02],
       [ 2.15566348e-01],
       [ 4.02923025e-01],
       [ 3.81510627e-01],
       [-8.71224059e-03],
       [ 5.15567521e-03],
       [-1.53016764e-02],
       [-5.87255553e-03],
       [ 1.45847961e-02],
       [ 7.16880313e-04]])


Finally, the variance is obtained 
$$
Var\left( \widehat{\beta }^{\left( RLS\right) }\right) =\sigma ^{2}\left[
X^{T}X\right] ^{-1}-\sigma ^{2}\left[ X^{T}X\right] ^{-1}L^{T}\left( L\left(
X^{T}X\right) ^{-1}L^{T}\right) ^{-1}L\left( X^{T}X\right) ^{-1}
$$
Where, we obtain the estimator of the variance error $\sigma ^{2}\,$as
follows:

$$
\hat{\sigma}_{RLS}^{2}=\frac{\widehat{\varepsilon }^{T}\widehat{\varepsilon }%
}{N-\left( k+1-M\right) }=\frac{\left( Y^{\ast }-Y\right) ^{T}\left( Y^{\ast
}-Y\right) }{147}
$$

In [161]:
VarB=np.linalg.inv(X.T@X)-np.linalg.inv(X.T@X)@L.T@np.linalg.inv(L@np.linalg.inv(X.T@X)@L.T)@L@np.linalg.inv(X.T@X)
#The variance and covariance matrix is multiplied by sigma (=VarB*sig2).
#We will estimate this value below.


###  Standard error of regression
Calculate the standard error of the regression. We divide by `(N-(k+1-M))`, because the Expectation of the sum of squares is `(N-(k+1-M))*sigma^2`.

In [204]:
y_actual=Y.reshape(-1, 1 )
y_pred = X@Beta_RLS
sr2 = ( (1 / (n_data - (X.shape[1]+1-L.shape[0]))) * (y_pred - y_actual).T  @ (y_pred - y_actual))
sr = np.sqrt(sr2)
sr

array([[0.1392342]])

In [196]:
#Then, the final version of our variance and covariance matrix will be:
VarB_RLS=VarB*sr2
VarB_RLS

array([[ 8.78260485e+00, -9.95223038e-02,  2.12941289e-04,
         1.62246665e-02, -2.28766621e-02,  6.65199568e-03,
        -3.15716255e+00,  1.66996176e+00,  1.48720080e+00,
         4.10382792e-01, -9.51497250e-02, -8.50890861e-01,
        -5.83061964e-01,  1.72679172e-01,  6.78211689e-01],
       [-9.95223038e-02,  1.65749023e-02, -7.21155928e-05,
        -3.01395818e-03,  2.34901433e-03,  6.64943853e-04,
         1.26188338e-02, -1.52539948e-02,  2.63516091e-03,
         1.64913955e-03, -3.02065020e-03, -1.36294772e-03,
         4.28146606e-06, -1.65342102e-03,  3.01636873e-03],
       [ 2.12941289e-04, -7.21155928e-05,  2.08059021e-05,
        -1.69226122e-05, -2.48091097e-06,  1.94035232e-05,
        -3.90015592e-05,  1.55322602e-04, -1.16321043e-04,
         2.58166025e-05,  6.36477100e-05, -9.99149723e-05,
        -9.46896424e-05,  6.88730399e-05,  3.10419324e-05],
       [ 1.62246665e-02, -3.01395818e-03, -1.69226122e-05,
         6.05392704e-04, -3.76088827e-04, -2.29303877