# 1 Assignment

# 1.1 Tuple
1. Print the first item of the `tuple1` object. **Hint: Use indexing**<br><br>
2. Print the last item of the `tuple1` object.**Hint: Use indexing**<br><br>
3. Change the value "orange" for "pink grapefruit". Comment the output. **Hint: Is it possible?** <br><br>
4. Print the length of `tuple1`. **Hint: Length function**<br><br>
5. Sort `tuple2` in descending order. **Hint: [Try this code](https://stackoverflow.com/questions/3453085/what-is-double-colon-in-python-when-subscripting-sequences)**<br><br>
6. Generate a new tuple object named as `tuple3` with the half values of `tuple2`. **Hint: Use auxiliary variables.**<br><br>

In [5]:
tuple1 = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
tuple1

('apple', 'banana', 'cherry', 'orange', 'kiwi', 'melon', 'mango')

In [6]:
tuple2 = (10, 20, 30, 40, 50)
tuple2

(10, 20, 30, 40, 50)

In [18]:
## 1. Print the first item of the tuple1 object. Hint: Use indexing

print(tuple1[0])

apple


In [19]:
## 2. Print the last item of the tuple1 object.Hint: Use indexing

print(tuple1[-1])

mango


In [27]:
## 3. Change the value "orange" for "pink grapefruit". Comment the output. Hint: Is it possible?

tuple1 = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
tuple1
tuple1_lista=list(tuple1)
tuple1_lista
tuple1_lista[3] = "pink grapefruit"
print(tuple1_lista)
tuple1=tuple(tuple1_lista)
tuple1

## Yes, it is possible, but first it has to become a list, make the modifications there and then return it to tuple.

['apple', 'banana', 'cherry', 'pink grapefruit', 'kiwi', 'melon', 'mango']


('apple', 'banana', 'cherry', 'pink grapefruit', 'kiwi', 'melon', 'mango')

In [3]:
## 4. Print the length of tuple1. Hint: Length function

tuple2 = ("apple", "banana", "cherry", "pink grapefruit", "kiwi", "melon", "mango")
print(len(tuple2))

7


In [8]:
## 5. Sort tuple2 in descending order. Hint: Try this code

tuple2 = (10, 20, 30, 40, 50)
tuple2[::-1]

(50, 40, 30, 20, 10)

In [9]:
## 6. Generate a new tuple object named as tuple3 with the half values of tuple2. Hint: Use auxiliary variables.

tuple3 = tuple(int(i/2) for i in tuple2)
tuple3


(5, 10, 15, 20, 25)

## 1.2 Lists
1. Show the indices of the `np.nan` values  in the `f_list` list. We want to see this output: `The indices 0, 1, 4, 7 have np.nan values.` **Hint: Use print function and [f-strings](https://realpython.com/python-f-strings/) to insert the indices values.**<br><br>

2. Replicate 4 times the values of the list `p2_list`. We expect an ouput like this: `[ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]`.  **Hint: Use multiplication function in `lists`and see the output.**<br><br>
3. Print the length of `f_list`. **Hint: Length function**<br><br>
4. Print `My teacher assistant is so boring.` using `text1` list. **Hint: Use the [`join` function](https://stackoverflow.com/questions/493819/why-is-it-string-joinlist-instead-of-list-joinstring)**<br><br>
5. Print `My TA is so boring, but is very funny.` using `text1` list.**Hint: Use the `join` function, and `extend` method.**<br><br>
6. Print <br>
`The max value of values1 is 86 and is located in the 0 index. ` <br>
`The min value of values1 is 0 and is located in the 7 index. ` <br> **Hint: Use the `f-string`, `min`, and `max` functions.**


In [5]:
import numpy as np

In [ ]:
f_list = [np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]

In [ ]:
text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring.']

In [ ]:
p2_list = [ 2 , 3, 4, 5 ]

In [ ]:
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1 ] 

In [21]:
## 1. Show the indices of the np.nan values in the f_list list. We want to see this output: The indices 0, 1, 4, 7 have np.nan values. Hint: Use print function and f-strings to insert the indices values.

import numpy as np

f_list = [np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ] 
x=[p for p, v in enumerate(f_list) if v is np.nan]
f"The indices, {x} have np.nan values."

'The indices, [0, 1, 4, 7] have np.nan values.'

In [24]:
## 3. Replicate 4 times the values of the list p2_list. We expect an ouput like this: [ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]. Hint: Use multiplication function in listsand see the output.

p2_list = [ 2 , 3, 4, 5 ]
p2_list*4

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]

In [25]:
## 3. Print the length of f_list. Hint: Length function
print(len(p2_list))

4


In [27]:
## 4. My teacher assistant is so boring. using text1 list. Hint: Use the join function
text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring.']
print(" ".join(text1))

My teacher assistant is so boring.


In [43]:
##5. Print My TA is so boring, but is very funny. using text1 list.Hint: Use the join function, and extend method.

text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring.']
text1[1] = "TA"
text1[2] = "\b"
text1[5] = "boring,"
b=" but is very funny."
print(" ".join(text1) + b)


My TA  is so boring, but is very funny.


In [53]:
##6. Print 
## The max value of values1 is 86 and is located in the 0 index.
## The min value of values1 is 0 and is located in the 7 index.
## Hint: Use the f-string, min, and max functions.

values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1 ] 
a1=max(values1)
a2=values1.index(a1)
b1=min(values1)
b2=values1.index(b1)
c = f"The max value of values1 is {a1} and is located in the {a2} index."
d = f"The min value of values1 is {b1} and is located in the {b2} index."
c

'The max value of values1 is 86 and is located in the 0 index.'

In [54]:
d

'The min value of values1 is 0 and is located in the 7 index.'

## 1.3 Dictionaries
1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>
2. Check if `TA` is a key of your object created in exercise 1. **Hint: Generate an object with the keys of your dictionary and check the statement using [`in` function](https://stackoverflow.com/questions/1602934/check-if-a-given-key-already-exists-in-a-dictionary). Do not use `if` function. Use `print` function.** <br><br>
3. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>
4. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>
5. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries](https://stackoverflow.com/questions/25836376/how-to-get-the-inner-indexes-of-a-nested-dictionary-in-python).** <br><br>
6. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists. **Hint: Use `zip` function adn [this link](https://stackoverflow.com/questions/1024847/how-can-i-add-new-keys-to-a-dictionary).** <br><br>

In [ ]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

In [ ]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

In [68]:
## 1. Create a dictionary with two keys: even_numbers and odd_numbers. The first key should have all the even numbers in this range [0, 2000], and the second key must have all the odd numbers in this range [9000, 19000]. The values should be stored in a list. Hint: Use the np.arange, zip, and np.tolist() functions.

even_numbers = np.arange(0,2001)
odd_numbers = np.arange(9000,19001)
lista = dict( zip( even_numbers , odd_numbers ) )
## Pendiente

In [ ]:
## 2. Check if TA is a key of your object created in exercise 1. Hint: Generate an object with the keys of your dictionary and check the statement using in function. Do not use if function. Use print function.

## Pendiente

In [69]:
## 3. Print the value of brand key of car dictionary. Hint: Use the get method.

car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

a = car.get('brand')
print(a)


Ford


In [72]:
## 4. Print all the the values of brand key of car dictionary. Hint: Use the values method.

b = car.values()
print(b)

## Consultar.


dict_values(['Ford', 'Mustang', 1964])


In [93]:
## 5. Print the max value of friday in january of hr_sleep dictionary. Hint: Indexing in nested dictioanries.

hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

a = hr_sleep.get('january')
b = a.get("friday")
c = max(b)
c
hr_sleep

{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]},
 'february': {'saturday': 5, 'sunday': 10, 'monday': 8}}

In [97]:
## 6. Add march key to the hr_sleep dictionary using week1 and values2 Python lists. Hint: Use zip function adn this link.

hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

march = dict.fromkeys(week1, values2)
hr_sleep.update( {"march":march} )
hr_sleep

{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]},
 'february': {'saturday': 5, 'sunday': 10, 'monday': 8},
 'march': {'monday': [[2, 3, 4], 8], 'sunday': [[2, 3, 4], 8]}}

## 1.4 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [ ]:
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

In [119]:
## 1. Replace all the even_numbers in np1 with 100. Hint: Use indexing in arrys and this filer.

np1 = np.arange( 200, 750 )
np1[np1%2 == 0] = 100 
np1


array([100, 201, 100, 203, 100, 205, 100, 207, 100, 209, 100, 211, 100,
       213, 100, 215, 100, 217, 100, 219, 100, 221, 100, 223, 100, 225,
       100, 227, 100, 229, 100, 231, 100, 233, 100, 235, 100, 237, 100,
       239, 100, 241, 100, 243, 100, 245, 100, 247, 100, 249, 100, 251,
       100, 253, 100, 255, 100, 257, 100, 259, 100, 261, 100, 263, 100,
       265, 100, 267, 100, 269, 100, 271, 100, 273, 100, 275, 100, 277,
       100, 279, 100, 281, 100, 283, 100, 285, 100, 287, 100, 289, 100,
       291, 100, 293, 100, 295, 100, 297, 100, 299, 100, 301, 100, 303,
       100, 305, 100, 307, 100, 309, 100, 311, 100, 313, 100, 315, 100,
       317, 100, 319, 100, 321, 100, 323, 100, 325, 100, 327, 100, 329,
       100, 331, 100, 333, 100, 335, 100, 337, 100, 339, 100, 341, 100,
       343, 100, 345, 100, 347, 100, 349, 100, 351, 100, 353, 100, 355,
       100, 357, 100, 359, 100, 361, 100, 363, 100, 365, 100, 367, 100,
       369, 100, 371, 100, 373, 100, 375, 100, 377, 100, 379, 10

In [122]:
## 2. Create a 3x3 matrix with values ranging from 0 to 8. Hint: Use np.arange and np.reshape method.

np3 = np.arange(0, 9).reshape ((3,3))
print (np3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [126]:
## 3. Consider an array Z = [1,2,3,4,5,6,7,8,9,10], generate an array R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]?.Hint: Use np.arange and np.concatenate

Z = np.arange(1, 11)

## Pendiente.

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [128]:
## 4. Create a 3x3x3 array with random values. Hint: Use np.random.random.

np.random.random_sample((3,3))


array([[0.90350744, 0.35732862, 0.6991168 ],
       [0.30321064, 0.16842733, 0.03701425],
       [0.74209758, 0.30592888, 0.96719963]])

In [ ]:
## 5. Comment why this expression np.nan == np.nan is False. Hint: Use stackoverflow.

## Pendiente.

In [134]:
## 6. Print the mean and standard deviation of np2. Hint: Use f-string, np.mean, and np.var methods.

np2 = np.random.normal( 50 , 4, 300)
a = np.mean(np2)
b = np.std(np2)

print(a)
print(b)


49.865805953513444
3.967538484063314


## Restricted Least Squares

Given the following equation:


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} ln^2q+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q1}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$


1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>
2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

In [3]:
import pandas as pd
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

In [4]:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

In [27]:
## 1. Get the estimated beta vector from the equation

# There are 15 independent variables (counting the constant) and 6 specified restrictions. 
# The last restriction can be made redundant by appliying it to the third, fourth, and fifth restrictions, meaning there are effectively 5 restrictions. 
L = np.array( ( [ 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0 ],
                [ 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], 
                [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0 ], 
                [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1 ], 
                [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1 ] ) )

rr = [ 1, 0, 0, 0, 0 ]



In [39]:
logct = np.log(ct)
logq = np.log(q)
loglogq = np.square(logq)
logp1 = np.log(p1)
logp2 = np.log(p2)
logp3 = np.log(p3)
logqp1 = np.multiply(logq, logp1)
logqp2 = np.multiply(logq, logp2)
logqp3 = np.multiply(logq, logp3)
loglogp1 = np.square(logp1)
loglogp2 = np.square(logp2)
loglogp3 = np.square(logp3)
logp1logp2 = np.multiply(logp1, logp2)
logp1logp3 = np.multiply(logp1, logp3)
logp2logp3 = np.multiply(logp2, logp3)
const = np.ones((len(ct), 1))

x_mat = np.column_stack([const, logq, loglogq * .5, logqp1, logqp2, logqp3, logp1, logp2, logp3, loglogp1 * .5, loglogp2 * .5, loglogp3 * .5, logp1logp2 * .5, logp1logp3 * .5, logp2logp3 * .5])

In [29]:
logct.shape

(158,)

In [30]:
x_mat.shape

(158, 15)

In [40]:
xtx_inv = np.linalg.inv(np.dot(np.transpose(x_mat), x_mat))
beta_ols = np.dot(xtx_inv, np.dot(np.transpose(x_mat), logct))
RA_1 = np.dot(xtx_inv, np.transpose(L))
RA_2 = np.linalg.inv(np.linalg.multi_dot([L, xtx_inv, np.transpose(L)]))
RA_3 = np.dot(L, beta_ols) - np.array(rr)
RA = RA_1.dot(RA_2).dot(RA_3)
beta_rls = beta_ols - RA
print(pd.DataFrame(beta_rls, 
                   index = ["const", "logq", "log^2q", "logqlogp1", "logqlogp2", "logqlogp3", "logp1", "logp2", "logp3", 
                            "log^2p1", "log^2p2", "log^2p3", "logp1logp2", "logp1logp3", "logp2logp3"], 
                   columns = ["Restricted Beta"]))



            Restricted Beta
const             -7.111200
logq               0.461368
log^2q             0.059955
logqlogp1         -0.004354
logqlogp2          0.036778
logqlogp3         -0.032424
logp1              0.215566
logp2              0.402923
logp3              0.381511
log^2p1           -0.008712
log^2p2            0.005156
log^2p3           -0.015302
logp1logp2        -0.005873
logp1logp3         0.014585
logp2logp3         0.000717


In [48]:
y_fit = np.dot(x_mat, beta_rls)
resid = np.array(logct) - y_fit

sigma2_rls = np.sum(resid**2) / (len(logct) - (len(beta_rls) - len(rr)))

D_mat = np.identity(len(beta_rls)) - RA_1.dot(RA_2).dot(L)
rls_vcov = sigma2_rls * D_mat.dot(xtx_inv)

print(pd.DataFrame(rls_vcov, 
                   index = ["const", "logq", "log^2q", "logqlogp1", "logqlogp2", "logqlogp3", "logp1", "logp2", "logp3", "log^2p1", "log^2p2", "log^2p3", "logp1logp2", "logp1logp3", "logp2logp3"], 
                   columns = ["const", "logq", "log^2q", "logqlogp1", "logqlogp2", "logqlogp3", "logp1", "logp2", "logp3", "log^2p1", "log^2p2", "log^2p3", "logp1logp2", "logp1logp3", "logp2logp3"]))

               const      logq    log^2q  logqlogp1  logqlogp2  logqlogp3  \
const       8.485895 -0.096160  0.000206   0.015677  -0.022104   0.006427   
logq       -0.096160  0.016015 -0.000070  -0.002912   0.002270   0.000642   
log^2q      0.000206 -0.000070  0.000020  -0.000016  -0.000002   0.000019   
logqlogp1   0.015677 -0.002912 -0.000016   0.000585  -0.000363  -0.000222   
logqlogp2  -0.022104  0.002270 -0.000002  -0.000363   0.000654  -0.000291   
logqlogp3   0.006427  0.000642  0.000019  -0.000222  -0.000291   0.000513   
logp1      -3.050502  0.012193 -0.000038  -0.001377   0.005099  -0.003722   
logp2       1.613544 -0.014739  0.000150   0.001701  -0.006121   0.004419   
logp3       1.436958  0.002546 -0.000112  -0.000324   0.001022  -0.000697   
log^2p1     0.396519  0.001593  0.000025  -0.000480  -0.000333   0.000813   
log^2p2    -0.091935 -0.002919  0.000061   0.000562   0.000057  -0.000619   
log^2p3    -0.822145 -0.001317 -0.000097   0.000574   0.000461  -0.001035   