# 1 Assignment

## 1.1 Tuple

In [1]:
tuple1 = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
tuple2 = (10, 20, 30, 40, 50)

1. Print the first item of the `tuple1` object. **Hint: Use indexing**<br><br>

In [6]:
print( f"This is the first item: {tuple1[0]}.")

This is the first item: apple.


2. Print the last item of the `tuple1` object.**Hint: Use indexing**<br><br>

In [173]:
var1 = tuple1[-1]
print( f"This is the last item: {var1}.")

This is the last item: mango.


3. Change the value "orange" for "pink grapefruit". Comment the output. **Hint: Is it possible?** <br><br>

In [8]:
# It is not possible. Tuples are not mutable objects.
tuple1[ 3 ] = "pink grapefruit"

TypeError: 'tuple' object does not support item assignment

4. Print the length of `tuple1`. **Hint: Length function**<br><br>

In [10]:
print( f"The length of tuple1 is { len( tuple1 ) }" )

The length of tuple1 is 7


5. Sort `tuple2` in descending order. **Hint: [Try this code](https://stackoverflow.com/questions/3453085/what-is-double-colon-in-python-when-subscripting-sequences)**<br><br>

In [13]:
print( tuple2 )
print( tuple2[ ::-1 ] )

(10, 20, 30, 40, 50)
(50, 40, 30, 20, 10)


6. Generate a new tuple object named as `tuple3` with the half values of `tuple2`. **Hint: Use auxiliary variables.**<br><br>

In [22]:
import numpy as np

In [168]:
tuple3 = tuple( np.array( list( tuple2 ) ) * 0.5 )
tuple3

(5.0, 10.0, 15.0, 20.0, 25.0)

## 1.2 Lists

In [2]:
import numpy as np

In [26]:
f_list = [np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]

In [65]:
text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring.']

In [28]:
p2_list = [ 2 , 3, 4, 5 ]

In [29]:
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1 ] 

1. Show the indices of the `np.nan` values  in the `f_list` list. We want to see this output: `The indices 0, 1, 4, 7 have np.nan values.` **Hint: Use print function and [f-strings](https://realpython.com/python-f-strings/) to insert the indices values.**<br><br>

In [178]:
print( f'''The indices {f_list.index(np.nan)}, 
      { f_list[1:].index(np.nan) + 1 } , 
      { f_list[2:].index(np.nan) + 2 }, 
      { f_list[5:].index(np.nan) + 5 } have np.nan values.''' )

The indices 0, 
      1 , 
      4, 
      7 have np.nan values.


2. Replicate 4 times the values of the list `p2_list`. We expect an ouput like this: `[ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]`.  **Hint: Use multiplication function in `lists`and see the output.**<br><br>

In [43]:
p2_list * 4

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]

3. Print the length of `f_list`. **Hint: Length function**<br><br>

In [44]:
print( len( f_list) )

8


4. Print `My teacher assistant is so boring.` using `text1` list. **Hint: Use the [`join` function](https://stackoverflow.com/questions/493819/why-is-it-string-joinlist-instead-of-list-joinstring)**<br><br>

In [180]:
print( ' '.join( text1 ) )
print(text1)

My teacher assistant is so boring.
['My', 'teacher', 'assistant', 'is', 'so', 'boring.']


5. Print `My TA is so boring, but is very funny.` using `text1` list.**Hint: Use the `join` function, and `extend` method.**<br><br>

In [74]:
text4 = [ text1[0] ] + ['TA'] + text1[3:-1]

text4.extend( ['boring,', 'but', 'is', 'very', 'funny.'] )

print( ' '.join( text4 ) )

6. Print <br>
`The max value of values1 is 86 and is located in the 0 index. ` <br>
`The min value of values1 is 0 and is located in the 7 index. ` <br> **Hint: Use the `f-string`, `min`, and `max` functions.**

In [80]:
print(f"The max value of values1 is {max(values1)} and is located in the {values1.index(max(values1))} index. \n The min value of values1 is {min(values1)} and is located in the {values1.index(min(values1))} index.")

The max value of values1 is 86 and is located in the 0 index. 
 The min value of values1 is 0 and is located in the 7 index.


## 1.3 Dictionaries

In [86]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>

In [95]:
# group10 answer
even_numbers=np.arange(2,2001,2).tolist()
odd_numbers=np.arange(9001,19000,2).tolist()
lists=[even_numbers,odd_numbers]
keys=["even_numbers","odd_numbers"]

dict_1 = dict( zip( keys, lists ) )
dict_1

{'even_numbers': [2,
  4,
  6,
  8,
  10,
  12,
  14,
  16,
  18,
  20,
  22,
  24,
  26,
  28,
  30,
  32,
  34,
  36,
  38,
  40,
  42,
  44,
  46,
  48,
  50,
  52,
  54,
  56,
  58,
  60,
  62,
  64,
  66,
  68,
  70,
  72,
  74,
  76,
  78,
  80,
  82,
  84,
  86,
  88,
  90,
  92,
  94,
  96,
  98,
  100,
  102,
  104,
  106,
  108,
  110,
  112,
  114,
  116,
  118,
  120,
  122,
  124,
  126,
  128,
  130,
  132,
  134,
  136,
  138,
  140,
  142,
  144,
  146,
  148,
  150,
  152,
  154,
  156,
  158,
  160,
  162,
  164,
  166,
  168,
  170,
  172,
  174,
  176,
  178,
  180,
  182,
  184,
  186,
  188,
  190,
  192,
  194,
  196,
  198,
  200,
  202,
  204,
  206,
  208,
  210,
  212,
  214,
  216,
  218,
  220,
  222,
  224,
  226,
  228,
  230,
  232,
  234,
  236,
  238,
  240,
  242,
  244,
  246,
  248,
  250,
  252,
  254,
  256,
  258,
  260,
  262,
  264,
  266,
  268,
  270,
  272,
  274,
  276,
  278,
  280,
  282,
  284,
  286,
  288,
  290,
  292,
  294,
  296,
 

2. Check if `TA` is a key of your object created in exercise 1. **Hint: Generate an object with the keys of your dictionary and check the statement using [`in` function](https://stackoverflow.com/questions/1602934/check-if-a-given-key-already-exists-in-a-dictionary). Do not use `if` function. Use `print` function.** <br><br>

In [182]:
print( "TA" in dict_1.keys() )

False


3. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>

In [87]:
# group 10 Aws
a = car.get("brand")
print( a )

Ford


4. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>

In [93]:
print( list( car.values() )[ 0 ] )

Ford


5. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries](https://stackoverflow.com/questions/25836376/how-to-get-the-inner-indexes-of-a-nested-dictionary-in-python).** <br><br>

In [118]:
max( hr_sleep[ 'january' ][ 'friday' ] )

2

6. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists. **Hint: Use `zip` function adn [this link](https://stackoverflow.com/questions/1024847/how-can-i-add-new-keys-to-a-dictionary).** <br><br>

In [120]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

In [121]:
march = dict( zip( week1 , values2 ) )
hr_sleep['march'] = march
hr_sleep

{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]},
 'february': {'saturday': 5, 'sunday': 10, 'monday': 8},
 'march': {'monday': [2, 3, 4], 'sunday': 8}}

## 1.4 Numpy

In [133]:
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>

In [134]:
np1[ np1 % 2 == 0 ] = 100
np1

array([100, 201, 100, 203, 100, 205, 100, 207, 100, 209, 100, 211, 100,
       213, 100, 215, 100, 217, 100, 219, 100, 221, 100, 223, 100, 225,
       100, 227, 100, 229, 100, 231, 100, 233, 100, 235, 100, 237, 100,
       239, 100, 241, 100, 243, 100, 245, 100, 247, 100, 249, 100, 251,
       100, 253, 100, 255, 100, 257, 100, 259, 100, 261, 100, 263, 100,
       265, 100, 267, 100, 269, 100, 271, 100, 273, 100, 275, 100, 277,
       100, 279, 100, 281, 100, 283, 100, 285, 100, 287, 100, 289, 100,
       291, 100, 293, 100, 295, 100, 297, 100, 299, 100, 301, 100, 303,
       100, 305, 100, 307, 100, 309, 100, 311, 100, 313, 100, 315, 100,
       317, 100, 319, 100, 321, 100, 323, 100, 325, 100, 327, 100, 329,
       100, 331, 100, 333, 100, 335, 100, 337, 100, 339, 100, 341, 100,
       343, 100, 345, 100, 347, 100, 349, 100, 351, 100, 353, 100, 355,
       100, 357, 100, 359, 100, 361, 100, 363, 100, 365, 100, 367, 100,
       369, 100, 371, 100, 373, 100, 375, 100, 377, 100, 379, 10

2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>

In [137]:
np.arange( 0, 9 ).reshape( 3, 3 )

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>

In [138]:
Z = np.arange(1, 11)
print (Z)


a = np.array([Z [0:4]])
b = np.array([Z [1:5]])
c = np.array([Z [2:6]])
d = np.array([Z [3:7]])
e = np.array([Z [4:8]])
f = np.array([Z [5:9]])
g = np.array([Z [6:10]])
np.concatenate((a,b,c,d,e,f,g), axis=0)

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>

In [139]:
np.random.random_sample((3,3))

array([[0.01114603, 0.83273772, 0.18437936],
       [0.80055485, 0.30878051, 0.52540756],
       [0.88477865, 0.1263509 , 0.70447372]])

5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>

https://numpy.org/doc/stable/user/misc.html

https://www.gormanalysis.com/blog/python-numpy-for-your-grandma-3-5-nan/#:~:text=NumPy%20designed%20nan%20so%20that,nan%20returns%20True.&text=This%20is%20because%20equivalence%20between,values%20is%20not%20well%20defined.&text=It's%20important%20to%20note%20that,inside%20an%20array%20of%20floats.

NumPy designed nan so that `nan == nan` returns `False`, but `nan != nan` returns `True`.

6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [142]:
print( f"Mean: {np.mean(np2)}\n Std: {np.std(np2)}" )

Mean: 50.30808635769349
 Std: 3.9348499756154482


## Restricted Least Squares

Given the following equation:


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$


1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>
2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

In [152]:
import pandas as pd
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

In [153]:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

To get $\hat{\boldsymbol \beta }^{(RLS)}$ we need to define the restriction coefficients matrix $\boldsymbol L $ and the restrictions vector $\boldsymbol r $. Before doing that, let’s replace the sixth restriction into the previous ones to get rid of subscripts

$$
\begin{aligned}
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{12} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{13} + \beta_{23} + \beta_{33} &= 0 \\
\end{aligned}
$$

Now with the new set of restrictions lets define $\boldsymbol{L}$ and $\boldsymbol{r}$, please note that we are working with the $1/2$ factor into the data and not with the coefficients

$$\boldsymbol{L} \boldsymbol{\beta} = \boldsymbol{r}$$
\begin{equation}
\begin{bmatrix}
0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 1 & 1 & 1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 0 & 1 & 1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 1 & 0 & 1 & 1 \\
\end{bmatrix} 
\begin{bmatrix}
\beta_{0} \\ 
\beta_{q} \\ 
\beta_{qq} \\
\beta_{q1} \\
\beta_{q2} \\
\beta_{q3} \\
\beta_{1} \\
\beta_{2} \\
\beta_{3} \\
\beta_{11} \\
\beta_{22} \\
\beta_{33} \\
\beta_{12} \\
\beta_{13} \\
\beta_{23} \\
\end{bmatrix} =
\begin{bmatrix}
1 \\
0 \\
0 \\
0 \\
0 
\end{bmatrix}
\end{equation}

With those definitions we can calculate $\hat{\boldsymbol{\beta}}^{(RLS)}$:

$$
\hat{\boldsymbol{\beta}}^{(RLS)} =\hat{\boldsymbol{\beta}}^{(OLS)} - \left( \boldsymbol{X}^\top \boldsymbol{X} \right)^{-1} \boldsymbol{L}^\top \left( \boldsymbol{L}\left( \boldsymbol{X}^\top \boldsymbol{X} \right)^{-1} \boldsymbol{L}^\top \right)^{-1} \left( \boldsymbol{L}\widehat{\boldsymbol{\beta}}^{(OLS)} - \boldsymbol{r} \right)
$$

In [165]:
# Variables transformation for equation
y = np.log(ct) # lnCT
c = np.ones(len(y)) # Constant
xq = np.log(q) # lnq
xqq = np.log(q)*np.log(q) # lnq^2
xq1 = np.log(q)*np.log(p1) # lnq*lnp_1
xq2 = np.log(q)*np.log(p2) # lnq*lnp_2
xq3 = np.log(q)*np.log(p3) # lnq*ln_3
x1 = np.log(p1) # lnp_1
x2 = np.log(p2) # ln_p2
x3 = np.log(p3) # ln_p3
x11 = 0.5*np.log(p1)*np.log(p1) # 0.5ln2p_1
x22 = 0.5*np.log(p2)*np.log(p2) # 0.5ln2p_2
x33 = 0.5*np.log(p3)*np.log(p3) # 0.5ln2p_3
x12 = 0.5*np.log(p1)*np.log(p2) # lnp_1*lnp_2
x13 = 0.5*np.log(p1)*np.log(p3) # lnp_1*lnp_3
x23 = 0.5*np.log(p2)*np.log(p3) # lnp_2*lnp_3

# Defining matrices 
X = np.asarray([c, xq,  xqq, xq1, xq2,
                xq3, x1,  x2,  x3,  x11, 
                x22, x33, x12, x13, x23]).T

L = np.array(([0,0,0,0,0,0,1,1,1,0,0,0,0,0,0],
              [0,0,0,1,1,1,0,0,0,0,0,0,0,0,0],
              [0,0,0,0,0,0,0,0,0,1,0,0,1,1,0],
              [0,0,0,0,0,0,0,0,0,0,1,0,1,0,1],
              [0,0,0,0,0,0,0,0,0,0,0,1,0,1,1]))

r = np.array([1, 0, 0, 0, 0])

# beta OLS
β_ols = np.linalg.inv(X.T @ X) @ (X.T @ y)
# beta RLS
β_rls = β_ols - np.linalg.inv(X.T @ X) @ L.T @ np.linalg.inv( L @ np.linalg.inv(X.T @ X) @ L.T) @ (L @ β_ols - r )


# label of coefficients
betas = ["beta_0", "beta_q", "beta_qq", "beta_q1", "beta_q2",
          "beta_q3", "beta_1", "beta_2", "beta_3", "beta_11",
          "beta_22", "beta_33", "beta_12", "beta_13", "beta_23"]

# results
print('----------------------------------------------------')
print('\t\t Table of Results\t')
print('----------------------------------------------------')
print('Parameter',' \t','OLS', ' \t\t', 'RLS')
print('----------------------------------------------------')
for i in range(len(betas)):
    print(betas[i], ' \t',round(β_ols[i],3),'  \t', round(β_rls[i],3))
print('----------------------------------------------------')

----------------------------------------------------
		 Table of Results	
----------------------------------------------------
Parameter  	 OLS  		 RLS
----------------------------------------------------
beta_0  	 -76.259   	 -7.111
beta_q  	 -1.08   	 0.461
beta_qq  	 0.026   	 0.03
beta_q1  	 0.131   	 -0.004
beta_q2  	 0.059   	 0.037
beta_q3  	 0.04   	 -0.032
beta_1  	 14.718   	 0.216
beta_2  	 -0.895   	 0.403
beta_3  	 6.381   	 0.382
beta_11  	 -1.539   	 -0.009
beta_22  	 -0.074   	 0.005
beta_33  	 -0.327   	 -0.015
beta_12  	 0.325   	 -0.006
beta_13  	 -1.144   	 0.015
beta_23  	 -0.048   	 0.001
----------------------------------------------------


Get the covariance matrix $\mathbb{V}{\rm ar} \left(\hat{\boldsymbol{\beta}}^{(RLS)} \right)$

We can get de RLS estimator covariance matrix by the following equation
$$
\begin{aligned}
\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right) 
&= \sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1} - \sigma^2 \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}  \mathbf{L}^\top \left( \mathbf{L}\left( \mathbf{X}^\top \mathbf{X} \right)^{-1} \mathbf{L}^\top \right)^{-1}  \mathbf{L} \left( \mathbf{X}^\top  \mathbf{X}\right)^{-1}
\end{aligned}
$$

In [167]:
# Defining errors and variance
res = y - X @ β_ols
sigma_sqr = ( res.T @ res) / (len(y)-(len(X[0])+1))

# getting var_beta_rls
var_β_rls = sigma_sqr * np.linalg.inv(X.T @ X) - sigma_sqr * np.linalg.inv(X.T @ X) @ L.T @ np.linalg.inv( L @ np.linalg.inv(X.T @ X) @ L.T) @ L @ np.linalg.inv(X.T @ X)

# showing var-cov coef. matrix
vbr = pd.DataFrame(var_β_rls)
vbr.columns = betas
vbr.index = betas
vbr

beta_0    beta_q   beta_qq   beta_q1   beta_q2   beta_q3    beta_1  \
beta_0   7.648283 -0.086668  0.000093  0.014129 -0.019922  0.005793 -2.749398   
beta_q  -0.086668  0.014434 -0.000031 -0.002625  0.002046  0.000579  0.010989   
beta_qq  0.000093 -0.000031  0.000005 -0.000007 -0.000001  0.000008 -0.000017   
beta_q1  0.014129 -0.002625 -0.000007  0.000527 -0.000328 -0.000200 -0.001241   
beta_q2 -0.019922  0.002046 -0.000001 -0.000328  0.000590 -0.000262  0.004595   
beta_q3  0.005793  0.000579  0.000008 -0.000200 -0.000262  0.000462 -0.003354   
beta_1  -2.749398  0.010989 -0.000017 -0.001241  0.004595 -0.003354  1.037901   
beta_2   1.454277 -0.013284  0.000068  0.001534 -0.005516  0.003983 -0.531437   
beta_3   1.295121  0.002295 -0.000051 -0.000292  0.000921 -0.000629 -0.506464   
beta_11  0.357380  0.001436  0.000011 -0.000432 -0.000300  0.000732 -0.141017   
beta_22 -0.082861 -0.002631  0.000028  0.000506  0.000052 -0.000558  0.041095   
beta_33 -0.740994 -0.001187 -0.000044  0.000517  0.000415 -0.000933  0.279112   
beta_12 -0.507756  0.000004 -0.000041  0.000222  0.000332 -0.000553  0.189517   
beta_13  0.150377 -0.001440  0.000030  0.000211 -0.000032 -0.000179 -0.048500   
beta_23  0.590617  0.002627  0.000014 -0.000728 -0.000383  0.001111 -0.230612   

           beta_2    beta_3   beta_11   beta_22   beta_33   beta_12   beta_13  \
beta_0   1.454277  1.295121  0.357380 -0.082861 -0.740994 -0.507756  0.150377   
beta_q  -0.013284  0.002295  0.001436 -0.002631 -0.001187  0.000004 -0.001440   
beta_qq  0.000068 -0.000051  0.000011  0.000028 -0.000044 -0.000041  0.000030   
beta_q1  0.001534 -0.000292 -0.000432  0.000506  0.000517  0.000222  0.000211   
beta_q2 -0.005516  0.000921 -0.000300  0.000052  0.000415  0.000332 -0.000032   
beta_q3  0.003983 -0.000629  0.000732 -0.000558 -0.000933 -0.000553 -0.000179   
beta_1  -0.531437 -0.506464 -0.141017  0.041095  0.279112  0.189517 -0.048500   
beta_2   0.309258  0.222179  0.070338 -0.002296 -0.154323 -0.111183  0.040845   
beta_3   0.222179  0.284285  0.070679 -0.038800 -0.124789 -0.078334  0.007655   
beta_11  0.070338  0.070679  0.020010 -0.007440 -0.037810 -0.025190  0.005180   
beta_22 -0.002296 -0.038800 -0.007440  0.025888 -0.005723 -0.012085  0.019525   
beta_33 -0.154323 -0.124789 -0.037810 -0.005723  0.090825  0.067179 -0.029369   
beta_12 -0.111183 -0.078334 -0.025190 -0.012085  0.067179  0.052227 -0.027037   
beta_13  0.040845  0.007655  0.005180  0.019525 -0.029369 -0.027037  0.021857   
beta_23  0.113478  0.117134  0.032630 -0.013802 -0.061456 -0.040142  0.007512   

          beta_23  
beta_0   0.590617  
beta_q   0.002627  
beta_qq  0.000014  
beta_q1 -0.000728  
beta_q2 -0.000383  
beta_q3  0.001111  
beta_1  -0.230612  
beta_2   0.113478  
beta_3   0.117134  
beta_11  0.032630  
beta_22 -0.013802  
beta_33 -0.061456  
beta_12 -0.040142  
beta_13  0.007512  
beta_23  0.053944