# GROUP 5 
___

### *Members:* 

* Sandra Gutiérrez 
* Ana Paula 
* Daniel
* Sandra Martínez Gutiérrez

# 1 Assignment

## 1.1 Tuple

In [128]:
tuple1 = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
tuple2 = (10, 20, 30, 40, 50)

1. Print the first item of the `tuple1` object. **Hint: Use indexing**<br><br>

In [129]:
tuple1[0]

'apple'

2. Print the last item of the `tuple1` object.**Hint: Use indexing**<br><br>

In [130]:
tuple1[len(tuple1)-1]

'mango'

In [131]:
tuple1[-1] #the simple way

'mango'

3. Change the value "orange" for "pink grapefruit". Comment the output. **Hint: Is it possible?** <br><br>

In [132]:
## We can't change an element in a tuple. Error says:'tuple' object does not support item assignment

tuple1[3] = "pink grapefruit"

TypeError: 'tuple' object does not support item assignment

In [75]:
tuple1_list = list(tuple1)
tuple1_list

['apple', 'banana', 'cherry', 'orange', 'kiwi', 'melon', 'mango']

In [78]:
tuple1_list[3] = "pink grapefruit"
tuple3 = tuple(tuple1_list)
tuple3

('apple', 'banana', 'cherry', 'pink grapefruit', 'kiwi', 'melon', 'mango')

4. Print the length of `tuple1`. **Hint: Length function**<br><br>

In [79]:
len(tuple1)

7

5. Sort `tuple2` in descending order. **Hint: [Try this code](https://stackoverflow.com/questions/3453085/what-is-double-colon-in-python-when-subscripting-sequences)**<br><br>

In [80]:
tuple_list2 = list(tuple2) # created a list from tuple2
tuple_list2

[10, 20, 30, 40, 50]

In [81]:
tuple_list2.sort(reverse=True)
tuple2sort = tuple_list2
tuple2sort

[50, 40, 30, 20, 10]

6. Generate a new tuple object named as `tuple3` with the half values of `tuple2`. **Hint: Use auxiliary variables.**<br><br>

In [82]:
list2 = list(tuple2)
list2

[10, 20, 30, 40, 50]

In [83]:
list3 = []
for i in list2:
    a = i/2
    list3 += [a]  
tuple3 = tuple(list3)
tuple3

[5.0, 10.0, 15.0, 20.0, 25.0]


## 1.2 Lists

In [133]:
import numpy as np

f_list = [np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]

text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring.']

values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1 ] 

1. Show the indices of the `np.nan` values  in the `f_list` list. We want to see this output: `The indices 0, 1, 4, 7 have np.nan values.` **Hint: Use print function and [f-strings](https://realpython.com/python-f-strings/) to insert the indices values.**<br><br>

In [504]:
## We create a loop to get the index of the "np.nan" values:
 
# First, we create an empty variable to append the index of the values that are not "np.nan"
indices = []

for i in range(0,len(f_list)):
    indices.append(f_list.index(f_list[i]))
print(indices)

[0, 0, 2, 3, 0, 5, 6, 0]


In [524]:
# Now, we want to have all the values different to zero so that we can create a new variable that contains those missing values
aux = [elemento for elemento in indices if elemento != 0]
res = [ele for ele in range(len(indices)) if ele not in aux]
res

[0, 1, 4, 7]

In [528]:
print( f"The indices {str(res)} have np.nan values" )

The indices [0, 1, 4, 7] have np.nan values


2. Replicate 4 times the values of the list `p2_list`. We expect an ouput like this: `[ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]`.  **Hint: Use multiplication function in `lists`and see the output.**<br><br>

In [88]:
p2_list = [2,3,4,5]
p2_list.extend(p2_list * 4)
print(p2_list)

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]


3. Print the length of `f_list`. **Hint: Length function**<br><br>

In [89]:
len(f_list)

8

4. Print `My teacher assistant is so boring.` using `text1` list. **Hint: Use the [`join` function](https://stackoverflow.com/questions/493819/why-is-it-string-joinlist-instead-of-list-joinstring)**<br><br>

In [90]:
text1 = ["My", "teacher", "assistant", "is", "so", "boring."]
print(" ".join(text1))

My teacher assistant is so boring.


5. Print `My TA is so boring, but is very funny.` using `text1` list.**Hint: Use the `join` function, and `extend` method.**<br><br>

In [91]:
text1[5] = "boring,"
text2= ["but is very funny."]
text1.extend(text2)
print(" ".join(text1))

My teacher assistant is so boring, but is very funny.


6. Print <br>
`The max value of values1 is 86 and is located in the 0 index. ` <br>
`The min value of values1 is 0 and is located in the 7 index. ` <br> **Hint: Use the `f-string`, `min`, and `max` functions.**

In [92]:
print(f"""The max value of values1 is {max(values1)} and is located in the {values1.index(max(values1))} index.
The min value of values1 is {min(values1)} and is located in the {values1.index(min(values1))} index.""")

The max value of values1 is 86 and is located in the 0 index.
The min value of values1 is 0 and is located in the 7 index.


## 1.3 Dictionaries
1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>

In [163]:
import numpy as np

In [164]:
even_numbers = np.arange(0,2000,2).tolist()
even_numbers

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [165]:
odd_numbers = list(range(9000, 19000))[1::2]
odd_numbers

[9001,
 9003,
 9005,
 9007,
 9009,
 9011,
 9013,
 9015,
 9017,
 9019,
 9021,
 9023,
 9025,
 9027,
 9029,
 9031,
 9033,
 9035,
 9037,
 9039,
 9041,
 9043,
 9045,
 9047,
 9049,
 9051,
 9053,
 9055,
 9057,
 9059,
 9061,
 9063,
 9065,
 9067,
 9069,
 9071,
 9073,
 9075,
 9077,
 9079,
 9081,
 9083,
 9085,
 9087,
 9089,
 9091,
 9093,
 9095,
 9097,
 9099,
 9101,
 9103,
 9105,
 9107,
 9109,
 9111,
 9113,
 9115,
 9117,
 9119,
 9121,
 9123,
 9125,
 9127,
 9129,
 9131,
 9133,
 9135,
 9137,
 9139,
 9141,
 9143,
 9145,
 9147,
 9149,
 9151,
 9153,
 9155,
 9157,
 9159,
 9161,
 9163,
 9165,
 9167,
 9169,
 9171,
 9173,
 9175,
 9177,
 9179,
 9181,
 9183,
 9185,
 9187,
 9189,
 9191,
 9193,
 9195,
 9197,
 9199,
 9201,
 9203,
 9205,
 9207,
 9209,
 9211,
 9213,
 9215,
 9217,
 9219,
 9221,
 9223,
 9225,
 9227,
 9229,
 9231,
 9233,
 9235,
 9237,
 9239,
 9241,
 9243,
 9245,
 9247,
 9249,
 9251,
 9253,
 9255,
 9257,
 9259,
 9261,
 9263,
 9265,
 9267,
 9269,
 9271,
 9273,
 9275,
 9277,
 9279,
 9281,
 9283,
 9285,

In [179]:
mydictionary = {'even_numbers': even_numbers, 
                'odd_numbers': odd_numbers}
mydictionary

{'even_numbers': [0,
  2,
  4,
  6,
  8,
  10,
  12,
  14,
  16,
  18,
  20,
  22,
  24,
  26,
  28,
  30,
  32,
  34,
  36,
  38,
  40,
  42,
  44,
  46,
  48,
  50,
  52,
  54,
  56,
  58,
  60,
  62,
  64,
  66,
  68,
  70,
  72,
  74,
  76,
  78,
  80,
  82,
  84,
  86,
  88,
  90,
  92,
  94,
  96,
  98,
  100,
  102,
  104,
  106,
  108,
  110,
  112,
  114,
  116,
  118,
  120,
  122,
  124,
  126,
  128,
  130,
  132,
  134,
  136,
  138,
  140,
  142,
  144,
  146,
  148,
  150,
  152,
  154,
  156,
  158,
  160,
  162,
  164,
  166,
  168,
  170,
  172,
  174,
  176,
  178,
  180,
  182,
  184,
  186,
  188,
  190,
  192,
  194,
  196,
  198,
  200,
  202,
  204,
  206,
  208,
  210,
  212,
  214,
  216,
  218,
  220,
  222,
  224,
  226,
  228,
  230,
  232,
  234,
  236,
  238,
  240,
  242,
  244,
  246,
  248,
  250,
  252,
  254,
  256,
  258,
  260,
  262,
  264,
  266,
  268,
  270,
  272,
  274,
  276,
  278,
  280,
  282,
  284,
  286,
  288,
  290,
  292,
  294,
  2

In [181]:
mydictionary.keys()

dict_keys(['even_numbers', 'odd_numbers'])

2. Check if `TA` is a key of your object created in exercise 1. **Hint: Generate an object with the keys of your dictionary and check the statement using [`in` function](https://stackoverflow.com/questions/1602934/check-if-a-given-key-already-exists-in-a-dictionary). Do not use `if` function. Use `print` function.** <br><br>

In [190]:
a = 'TA' in mydictionary
print(f""" 'TA' is not a key in our dictionary 'mydictionary'. When tested, result was: {str(a)}""")

 'TA' is not a key in our dictionary 'mydictionary'. When tested, result was: False


3. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>

In [191]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

In [198]:
a = car.get('brand')
print(f""" The value of 'brand' key of 'car' dictionary is {str(a)} """)

 The value of 'brand' key of 'car' dictionary is Ford 


4. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>

In [380]:
values = car.values()

# Convert dictionary's values to a list
values_list = list(values)

a_value = values_list[0]

print(a_value)

Ford


5. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries](https://stackoverflow.com/questions/25836376/how-to-get-the-inner-indexes-of-a-nested-dictionary-in-python).** <br><br>

In [265]:
b = max(hr_sleep['january']['friday'])
b

2

In [266]:
print(f""" The max value of 'friday' in 'january' of 'hr_sleep' dictionary is {str(b)} """)

 The max value of 'friday' in 'january' of 'hr_sleep' dictionary is 2 


6. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists. **Hint: Use `zip` function adn [this link](https://stackoverflow.com/questions/1024847/how-can-i-add-new-keys-to-a-dictionary).** <br><br>

In [267]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

In [268]:
march = dict(zip(week1, values2))
march

{'monday': [2, 3, 4], 'sunday': 8}

In [271]:
hr_sleep.update( {'march' : march } )
hr_sleep

{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]},
 'february': {'saturday': 5, 'sunday': 10, 'monday': 8},
 'march': {'monday': [2, 3, 4], 'sunday': 8}}

## 1.4 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>


In [366]:
np1 = np.arange( 200, 750)

In [277]:
np1[np1 % 2 == 0 ] = 100
np1

array([100, 201, 100, 203, 100, 205, 100, 207, 100, 209, 100, 211, 100,
       213, 100, 215, 100, 217, 100, 219, 100, 221, 100, 223, 100, 225,
       100, 227, 100, 229, 100, 231, 100, 233, 100, 235, 100, 237, 100,
       239, 100, 241, 100, 243, 100, 245, 100, 247, 100, 249, 100, 251,
       100, 253, 100, 255, 100, 257, 100, 259, 100, 261, 100, 263, 100,
       265, 100, 267, 100, 269, 100, 271, 100, 273, 100, 275, 100, 277,
       100, 279, 100, 281, 100, 283, 100, 285, 100, 287, 100, 289, 100,
       291, 100, 293, 100, 295, 100, 297, 100, 299, 100, 301, 100, 303,
       100, 305, 100, 307, 100, 309, 100, 311, 100, 313, 100, 315, 100,
       317, 100, 319, 100, 321, 100, 323, 100, 325, 100, 327, 100, 329,
       100, 331, 100, 333, 100, 335, 100, 337, 100, 339, 100, 341, 100,
       343, 100, 345, 100, 347, 100, 349, 100, 351, 100, 353, 100, 355,
       100, 357, 100, 359, 100, 361, 100, 363, 100, 365, 100, 367, 100,
       369, 100, 371, 100, 373, 100, 375, 100, 377, 100, 379, 10

2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>

In [273]:
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>

In [278]:
Z = [1,2,3,4,5,6,7,8,9,10]
Z

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [363]:
a = 0 
b = 4
c = np.zeros((7, 4))
for i in range(0,7):
    c[[i]] += np.array([Z[a+i:b+i]])
c

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  3.,  4.,  5.],
       [ 3.,  4.,  5.,  6.],
       [ 4.,  5.,  6.,  7.],
       [ 5.,  6.,  7.,  8.],
       [ 6.,  7.,  8.,  9.],
       [ 7.,  8.,  9., 10.]])

4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>

In [364]:
x1 = np.random.random(3)
y1 = np.random.random(3) 
z1 = np.random.random(3)

random4 = np.vstack((x1,y1,z1))
random4

array([[0.36864188, 0.67153433, 0.12977083],
       [0.07472645, 0.70269263, 0.13227948],
       [0.48369842, 0.47344329, 0.42507337]])

5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** 

In [365]:
np.nan == np.nan 

False

Four mutually exclusive relations are possible: less than, equal, greater than, and unordered. The last case arises when at least one operand is NaN. Every NaN shall compare unordered with everything, including itself. <br><br>
NAN is not a number but an undefined element. Therefore it cannot be equal to another posible element. It's an axiom. <br><br>
Source: 
https://stackoverflow.com/questions/1565164/what-is-the-rationale-for-all-comparisons-returning-false-for-ieee754-nan-values
https://stackoverflow.com/questions/1565164/what-is-the-rationale-for-all-comparisons-returning-false-for-ieee754-nan-values/1573715#1573715

6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [370]:
np2 = np.random.normal( 50 , 4, 300)

In [102]:
print(f"The mean of np2 is {np.mean(np2)} and the standard deviation is {np.var(np2)}.")

The mean of np2 is 50.12207880792807 and the standard deviation is 16.01642038586672.


## Restricted Least Squares

Given the following equation:


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq}lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$

1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>

In [529]:
import pandas as pd
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

In [530]:
greene.head(5)

id  YEAR    COST       Q       PL      SL      PK      SK      PF     SF 
0   1  1970  0.2130     8.0  6869.47  0.3291  64.945  0.4197  18.000  0.2512
1   4  1970  3.0427   869.0  8372.96  0.1030  68.227  0.2913  21.067  0.6057
2   5  1970  9.4059  1412.0  7960.90  0.0891  40.692  0.1567  41.530  0.7542
3  14  1970  0.7606    65.0  8971.89  0.2802  41.243  0.1282  28.539  0.5916
4  15  1970  2.2587   295.0  8218.40  0.1772  71.940  0.1623  39.200  0.6606

In [536]:
greene.dtypes

id        int64
YEAR      int64
COST    float64
Q       float64
PL      float64
SL      float64
PK      float64
SK      float64
PF      float64
SF      float64
dtype: object

In [544]:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

In [614]:
np.ones(3).reshape(-1, 1)

array([[1.],
       [1.],
       [1.]])

In [620]:
y = np.log(ct)
x0 = np.ones(len(greene)).reshape(-1, 1)
ln_q = np.log(q)
ln_q_2 = 0.5 *(ln_q * ln_q)
ln_q_p1 = ln_q * np.log(p1)
ln_q_p2 = ln_q * np.log(p2)
ln_q_p3 = ln_q * np.log(p3)
ln_p1 = np.log(p1)
ln_p2 = np.log(p2)
ln_p3 = np.log(p3)
ln_p1_2 = 0.5 * ln_p1 * ln_p1
ln_p2_2 = 0.5 * ln_p2 * ln_p2
ln_p3_2 = 0.5 * ln_p3 * ln_p3
ln_p1_p2 = 0.5 * ln_p1 * ln_p2
ln_p1_p3 = 0.5 * ln_p1 * ln_p3
ln_p2_p3 = 0.5 * ln_p2 * ln_p3

In [635]:
x = np.column_stack([x0, ln_q, q_ln_q_2, ln_q_p1, ln_q_p2, ln_q_p3, ln_p1, ln_p2, ln_p3, ln_p1_2, ln_p2_2, ln_p3_3, ln_p1_p2, ln_p1_p3, ln_p2_p3]) 
x.shape

(158, 15)

In [625]:
data = pd.DataFrame(np.column_stack([y, x]), 
                    columns = ['y', 'constant', 'ln_q' ,  'q_ln_q_2' ,  'ln_q_p1' ,  'ln_q_p2' ,  'ln_q_p3' ,  'ln_p1' ,  'ln_p2' ,  'ln_p3' ,  'ln_p1_2' , 'ln_p2_2' ,  'ln_p3_2' ,  'ln_p1_p2' ,  'ln_p1_p3' ,  'ln_p2_p3'])
data

y  constant      ln_q       q_ln_q_2    ln_q_p1    ln_q_p2  \
0   -1.546463       1.0  2.079442      17.296309  18.371538   6.010359   
1    1.112745       1.0  6.767343   19898.767378  61.127805  20.624885   
2    2.241337       1.0  7.252762   37137.409261  65.146469  27.026810   
3   -0.273648       1.0  4.174387     566.329045  37.994654  13.989505   
4    0.814789       1.0  5.686975    4770.399084  51.263140  20.863674   
..        ...       ...       ...            ...        ...        ...   
153  1.921222       1.0  6.852877   22227.075758  63.543838  27.006249   
154  1.324552       1.0  5.932245    6633.603964  52.877557  20.820004   
155  1.381834       1.0  5.968708    6964.779373  51.749248  22.671977   
156  3.407444       1.0  8.578665  195648.279435  78.650266  32.031471   
157  4.217391       1.0  9.630366  705781.400102  85.244879  31.250645   

       ln_q_p3     ln_p1     ln_p2     ln_p3    ln_p1_2   ln_p2_2   ln_p3_2  \
0     8.678634  8.834842  2.890372  4.173541  39.027219  4.177124  8.709221   
1    28.577410  9.032763  3.047708  4.222840  40.795401  4.644262  8.916190   
2    26.878966  8.982297  3.726416  3.706032  40.340833  6.943088  6.867335   
3    15.526556  9.101852  3.351272  3.719481  41.421852  5.615511  6.917271   
4    24.316554  9.014131  3.668677  4.275832  40.627277  6.729595  9.141372   
..         ...       ...       ...       ...        ...       ...       ...   
153  25.870001  9.272579  3.940863  3.775057  42.990358  7.765201  7.125528   
154  25.542382  8.913583  3.509633  4.305685  39.725977  6.158762  9.269463   
155  26.025919  8.670093  3.798473  4.360394  37.585255  7.214200  9.506519   
156  37.375623  9.168125  3.733853  4.356811  42.027255  6.970828  9.490903   
157  41.452974  8.851676  3.245011  4.304403  39.176087  5.265049  9.263942   

      ln_p1_p2   ln_p1_p3  ln_p2_p3  
0    12.767989  18.436287  6.031542  
1    13.764611  19.071958  6.434992  
2    16.735889  16.644338  6.905108  
3    15.251388  16.927084  6.232496  
4    16.534966  19.271456  7.843324  
..         ...        ...       ...  
153  18.270982  17.502257  7.438492  
154  15.641703  19.189541  7.555688  
155  16.466559  18.902512  8.281421  
156  17.116214  19.971895  8.133846  
157  14.361895  19.050590  6.983918  

[158 rows x 16 columns]

In [568]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [684]:
# OLS estimation 

y_mdl = sm.OLS.from_formula("y ~ ln_q + q_ln_q_2 + ln_q_p1 + ln_q_p2 + ln_q_p3 + ln_p1 + ln_p2 + ln_p3 + ln_p1_2 +ln_p2_2 + ln_p3_2 + ln_p1_p2 + ln_p1_p3 + ln_p2_p3", 
                            data = data)
y_mdl_fit = y_mdl.fit()
print(y_mdl_fit.summary().tables[1])

                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -29.9218     46.181     -0.648      0.518    -121.207      61.364
ln_q          -1.8861      0.441     -4.276      0.000      -2.758      -1.014
q_ln_q_2    1.087e-07   1.74e-08      6.257      0.000    7.43e-08    1.43e-07
ln_q_p1        0.2428      0.044      5.552      0.000       0.156       0.329
ln_q_p2        0.0552      0.031      1.763      0.080      -0.007       0.117
ln_q_p3        0.0790      0.036      2.205      0.029       0.008       0.150
ln_p1          8.7260      8.583      1.017      0.311      -8.239      25.691
ln_p2         -4.9567      3.417     -1.451      0.149     -11.711       1.797
ln_p3          2.2698      5.490      0.413      0.680      -8.582      13.121
ln_p1_2       -1.1470      0.841     -1.364      0.175      -2.809       0.515
ln_p2_2       -0.1937      0.221     -0.877      0.3

In [665]:
#Restrictions 

L = np.array(([0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
              [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1]))
rr = [0, 0, 0, 0, 0] 

In [686]:
X_d = sm.add_constant(x)
xtx_inv  = np.linalg.inv(np.dot(np.transpose(X_d), X_d))
beta_ols = np.dot(xtx_inv, np.dot(np.transpose(X_d), y))

print(pd.DataFrame(beta_ols, columns = ["est - OLS"],
                   index = ['constant', 'ln_q' ,  'q_ln_q_2' ,  'ln_q_p1' ,  'ln_q_p2' ,  'ln_q_p3' ,  'ln_p1' ,  'ln_p2' ,  'ln_p3' ,  'ln_p1_2' , 'ln_p2_2' ,  'ln_p3_2' ,  'ln_p1_p2' ,  'ln_p1_p3' ,  'ln_p2_p3']))

             est - OLS
constant -2.992182e+01
ln_q     -1.886142e+00
q_ln_q_2  1.086833e-07
ln_q_p1   2.428421e-01
ln_q_p2   5.516336e-02
ln_q_p3   7.904991e-02
ln_p1     8.725983e+00
ln_p2    -4.956660e+00
ln_p3     2.269796e+00
ln_p1_2  -1.146982e+00
ln_p2_2  -1.936770e-01
ln_p3_2   2.769396e-01
ln_p1_p2  1.061980e+00
ln_p1_p3 -1.037927e+00
ln_p2_p3  4.818801e-01


In [668]:
RA_1 = np.dot(xtx_inv, np.transpose(L))
RA_2 = np.linalg.inv(np.linalg.multi_dot([L, xtx_inv, np.transpose(L)]))
RA_3 = np.dot(L, beta_ols) - np.array(rr)
RA   = RA_1.dot(RA_2).dot(RA_3)
RA

array([-2.76044921e+01, -2.54166606e+00, -2.77303983e-08,  2.08494542e-01,
        3.33434419e-02,  1.35217382e-01,  9.74024673e+00, -5.22284745e+00,
        1.52172032e+00, -1.27333071e+00, -1.19391778e-02, -3.53637236e-02,
        8.78133658e-01, -7.27731972e-01,  4.83988527e-01])

In [687]:
# Having calculated the adjustment component, we can finally calculate the RLS estimator:

beta_rls = beta_ols - RA
print(pd.DataFrame(beta_rls, columns = ["est - RLS"],
                   index = ['constant', 'ln_q' ,  'q_ln_q_2' ,  'ln_q_p1' ,  'ln_q_p2' ,  'ln_q_p3' ,  'ln_p1' ,  'ln_p2' ,  'ln_p3' ,  'ln_p1_2' , 'ln_p2_2' ,  'ln_p3_2' ,  'ln_p1_p2' ,  'ln_p1_p3' ,  'ln_p2_p3']))

             est - RLS
constant -2.317329e+00
ln_q      6.555243e-01
q_ln_q_2  1.364137e-07
ln_q_p1   3.434756e-02
ln_q_p2   2.181992e-02
ln_q_p3  -5.616747e-02
ln_p1    -1.014263e+00
ln_p2     2.661875e-01
ln_p3     7.480758e-01
ln_p1_2   1.263486e-01
ln_p2_2  -1.817379e-01
ln_p3_2   3.123033e-01
ln_p1_p2  1.838463e-01
ln_p1_p3 -3.101949e-01
ln_p2_p3 -2.108428e-03


2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

In [670]:
y_fit = np.dot(X_d, beta_rls)
resid = np.array(y) - y_fit

sigma2_rls = np.sum(resid**2) / (len(data.index) - (len(beta_rls) - len(rr)))
print("Estimated RLS residual standard error: " + str(np.round(sigma2_rls, 5)))

Estimated RLS residual standard error: 0.03128


In [671]:
D_mat = np.identity(len(beta_rls)) - RA_1.dot(RA_2).dot(L)
rls_vcov = sigma2_rls * D_mat.dot(xtx_inv)
beta_rls_se = np.sqrt(np.diag(rls_vcov))
print(pd.DataFrame(np.column_stack([beta_rls, beta_rls_se]), columns = ["est", "se"],
                   index = ['constant', 'ln_q' ,  'q_ln_q_2' ,  'ln_q_p1' ,  'ln_q_p2' ,  'ln_q_p3' ,  'ln_p1' ,  'ln_p2' ,  'ln_p3' ,  'ln_p1_2' , 'ln_p2_2' ,  'ln_p3_2' ,  'ln_p1_p2' ,  'ln_p1_p3' ,  'ln_p2_p3']))

                   est            se
constant -2.317329e+00  3.712274e+00
ln_q      6.555243e-01  1.601232e-01
q_ln_q_2  1.364137e-07  1.852379e-08
ln_q_p1   3.434756e-02  3.048424e-02
ln_q_p2   2.181992e-02  3.273335e-02
ln_q_p3  -5.616747e-02  2.861894e-02
ln_p1    -1.014263e+00  1.367704e+00
ln_p2     2.661875e-01  7.454243e-01
ln_p3     7.480758e-01  7.154793e-01
ln_p1_2   1.263486e-01  1.897701e-01
ln_p2_2  -1.817379e-01  2.153583e-01
ln_p3_2   3.123033e-01  4.036761e-01
ln_p1_p2  1.838463e-01  3.057322e-01
ln_p1_p3 -3.101949e-01  1.976340e-01
ln_p2_p3 -2.108428e-03  3.116863e-01


In [674]:
# Variance matrix

np.diag(rls_vcov)

array([1.37809801e+01, 2.56394483e-02, 3.43130849e-16, 9.29288748e-04,
       1.07147240e-03, 8.19043715e-04, 1.87061454e+00, 5.55657367e-01,
       5.11910674e-01, 3.60126892e-02, 4.63792057e-02, 1.62954392e-01,
       9.34721609e-02, 3.90592137e-02, 9.71483735e-02])

In [678]:
# Variance and covariance matrix

rls_vcov

array([[ 1.37809801e+01, -1.54966159e-01, -3.22178204e-10,
         2.57510466e-02, -3.58126052e-02,  1.00615586e-02,
        -4.95469854e+00,  2.61828371e+00,  2.33641482e+00,
         6.43666280e-01, -1.50264115e-01, -1.33392434e+00,
        -9.13663253e-01,  2.69996973e-01,  1.06392737e+00],
       [-1.54966159e-01,  2.56394483e-02, -7.82063661e-11,
        -4.81876269e-03,  3.68583720e-03,  1.13292549e-03,
         1.95368832e-02, -2.31415381e-02,  3.60465490e-03,
         2.72740299e-03, -4.37188183e-03, -2.70097229e-03,
        -5.28246721e-04, -2.19915627e-03,  4.90012855e-03],
       [-3.22178204e-10, -7.82063661e-11,  3.43130849e-16,
        -1.59472975e-11, -5.53215295e-11,  7.12688269e-11,
         2.45353698e-10,  2.00480755e-10, -4.45834453e-10,
         5.81716916e-12, -9.96720777e-11,  8.03836882e-11,
         8.71192984e-11, -9.29364675e-11,  1.25527793e-11],
       [ 2.57510466e-02, -4.81876269e-03, -1.59472975e-11,
         9.29288748e-04, -5.90858717e-04, -3.38430030