In [1]:
#Create a tuple
tuple1 = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")

In [ ]:
##1.1 Tuple##

#1.Print the first item of the tuple1 object
print (tuple1 [0])
index1 = tuple1.index( "apple" )
print('The index of "apple" is:', index1)

In [13]:
#2. Print the last item of the tuple1 object
print (tuple1 [6])
index2 = tuple1.index( "mango" )
print('The index of "mango" is:', index2)

mango
The index of "mango" is: 6


In [ ]:
#3. Change the value "orange" for "pink grapefruit"
tuple1["orange"] = "pink grapefruit"
#It's not possible because, you can't modify a tuple

In [16]:
#4. Print the length of tuple1
print('The length of the tuple1 is:', len(tuple1))

The length of the tuple1 is: 7


In [19]:
#5. Sort tuple2 in descending order
tuple2 = (10, 20, 30, 40, 50)
tuple2_r = tuple(sorted(tuple2, reverse=True))
print(tuple2_r)

(50, 40, 30, 20, 10)


In [21]:
#6. Generate a new tuple object named as tuple3 with the half values of tuple2
tuple2 = (10, 20, 30, 40, 50)
tuple3 = tuple(tuple2i/2 for tuple2i in tuple2)
print( tuple3 )

(5.0, 10.0, 15.0, 20.0, 25.0)


In [5]:
## 1.2 Lists ##

import numpy as np
f_list = [np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]

In [49]:
#1. Show the indices of the np.nan values in the f_list list. We want to see this output: The indices 0, 1, 4, 7 have np.nan values. 

ind = [i for i, v in enumerate(f_list) if v is np.nan]

ind2 = str(ind)[1:-1] 

In [50]:
print('The indices', ind2 ,"have np.nan values")

The indices 0, 1, 4, 7 have np.nan values


In [67]:
#2. Replicate 4 times the values of the list p2_list. We expect an ouput like this: [ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]. Hint: Use multiplication function in listsand see the output.

p2_list = [2 ,3, 4, 5]

output = p2_list *4

In [68]:
print(output)

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]


In [69]:
#3. Print the length of f_list. Hint: Length function

len(f_list)

8

In [91]:
#4. Print My teacher assistant is so boring. using text1 list. Hint: Use the join function

text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring.']

In [94]:
print(*text1, sep=" ") 

My teacher assistant is so boring.


In [74]:
#or
print(' '.join(text1))

My teacher assistant is so boring.


In [114]:
#5. Print My TA is so boring, but is very funny. using text1 list.Hint: Use the join function, and extend method.

text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring']
text2 = [',','but', 'is', 'very', 'funny.']
text1.extend(text2)

print(' '.join(text1))

My teacher assistant is so boring , but is very funny.


In [85]:
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1 ] 

In [103]:
maxmin = "max"
valores =  max(values1)
ubicacion = values1.index(max(values1))

f"The {maxmin} value of values 1 is {valores} and is located in {ubicacion}."

# No sé si está bien!

'The max value of values 1 is 86 and is located in 0'

In [102]:
print("The max value of values 1 is", max(values1), "and is located in", values1.index(max(values1)))

The max value of values 1 is 86 and is located in 0


In [121]:
# Creo que esta es!
max1 = 'max'
valor1 =  max(values1)
ubicacion1 = values1.index(max(values1))

min1 = 'min'
valor2 =  min(values1)
ubicacion2 = values1.index(min(values1))

print(f'The {max1} value of values1 is {valor1} and is located in the {ubicacion1} index.\n',
    f'The {min1} value of values1 is {valor2} and is located in the {ubicacion2} index.')

The max value of values1 is 86 and is located in the 0 index.
 The min value of values1 is 0 and is located in the 7 index.


In [11]:
## 1.4 Numpy ##

#1. Replace all the even_numbers in np1 with 100.
import numpy as np
np1 = np.arange(200, 750)
np1[np1%2 == 1] = 100
print( np1 )

[200 100 202 100 204 100 206 100 208 100 210 100 212 100 214 100 216 100
 218 100 220 100 222 100 224 100 226 100 228 100 230 100 232 100 234 100
 236 100 238 100 240 100 242 100 244 100 246 100 248 100 250 100 252 100
 254 100 256 100 258 100 260 100 262 100 264 100 266 100 268 100 270 100
 272 100 274 100 276 100 278 100 280 100 282 100 284 100 286 100 288 100
 290 100 292 100 294 100 296 100 298 100 300 100 302 100 304 100 306 100
 308 100 310 100 312 100 314 100 316 100 318 100 320 100 322 100 324 100
 326 100 328 100 330 100 332 100 334 100 336 100 338 100 340 100 342 100
 344 100 346 100 348 100 350 100 352 100 354 100 356 100 358 100 360 100
 362 100 364 100 366 100 368 100 370 100 372 100 374 100 376 100 378 100
 380 100 382 100 384 100 386 100 388 100 390 100 392 100 394 100 396 100
 398 100 400 100 402 100 404 100 406 100 408 100 410 100 412 100 414 100
 416 100 418 100 420 100 422 100 424 100 426 100 428 100 430 100 432 100
 434 100 436 100 438 100 440 100 442 100 444 100 44

In [29]:
#2. Create a 3x3 matrix with values ranging from 0 to 8
matrix1 =  np.arange(0, 9).reshape(3,3)
print(matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [42]:
#3. Generate an array: R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]
z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 

In [50]:
#4. Create a 3x3x3 array with random values
np.random.random((3, 3))

array([[0.50413416, 0.49938274, 0.15962205],
       [0.89067293, 0.45387265, 0.46178381],
       [0.80157793, 0.95923691, 0.93297814]])

In [ ]:
#5. Comment why this expression np.nan == np.nan
#Because equivalence between missing or invalid values is not well defined

In [57]:
#6. Print the mean and standard deviation of np2
np2 = np.random.normal( 50, 4, 300)
np.mean( np2 )

50.06907437131031

In [58]:
np.var( np2 )

16.821373172492