# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Dictionaries
1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>
2. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>
3. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>
4. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries](https://stackoverflow.com/questions/25836376/how-to-get-the-inner-indexes-of-a-nested-dictionary-in-python).** <br><br>
5. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists. **Hint: Use `zip` function adn [this link](https://stackoverflow.com/questions/1024847/how-can-i-add-new-keys-to-a-dictionary).** <br><br>

In [6]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

In [7]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>

In [8]:
import numpy as np # Importing numpy as np 

#Creating the arrays requiered with the np.arange function. 
even_numbers=np.arange(0,2002,2)
#print(even_numbers)

odd_numbers=np.arange(9001,19000,2)
#print(odd_numbers)


#Converting the arrays in lists with the np.tolist() function.
list_even=even_numbers.tolist()
#print(list_even)

list_odd=odd_numbers.tolist()
#print(list_odd)

#Converting the list in a dictionary.
dict1= dict( zip( list_even, list_odd))
print(dict1)
#type(dict1)

{0: 9001, 2: 9003, 4: 9005, 6: 9007, 8: 9009, 10: 9011, 12: 9013, 14: 9015, 16: 9017, 18: 9019, 20: 9021, 22: 9023, 24: 9025, 26: 9027, 28: 9029, 30: 9031, 32: 9033, 34: 9035, 36: 9037, 38: 9039, 40: 9041, 42: 9043, 44: 9045, 46: 9047, 48: 9049, 50: 9051, 52: 9053, 54: 9055, 56: 9057, 58: 9059, 60: 9061, 62: 9063, 64: 9065, 66: 9067, 68: 9069, 70: 9071, 72: 9073, 74: 9075, 76: 9077, 78: 9079, 80: 9081, 82: 9083, 84: 9085, 86: 9087, 88: 9089, 90: 9091, 92: 9093, 94: 9095, 96: 9097, 98: 9099, 100: 9101, 102: 9103, 104: 9105, 106: 9107, 108: 9109, 110: 9111, 112: 9113, 114: 9115, 116: 9117, 118: 9119, 120: 9121, 122: 9123, 124: 9125, 126: 9127, 128: 9129, 130: 9131, 132: 9133, 134: 9135, 136: 9137, 138: 9139, 140: 9141, 142: 9143, 144: 9145, 146: 9147, 148: 9149, 150: 9151, 152: 9153, 154: 9155, 156: 9157, 158: 9159, 160: 9161, 162: 9163, 164: 9165, 166: 9167, 168: 9169, 170: 9171, 172: 9173, 174: 9175, 176: 9177, 178: 9179, 180: 9181, 182: 9183, 184: 9185, 186: 9187, 188: 9189, 190: 9191

2. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>

In [9]:
car.get('brand') #Using the get method in order to obtain the value of "brand" key of car dictionary. 

'Ford'

3. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>

In [13]:
car.values() #Using the values method in order to obtain all the values of the car dictionary. 

dict_values(['Ford', 'Mustang', 1964])

4. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries]

In [15]:
#Using the get function in order to obtain the values, first of the month:january amd then to get the day: friday
#The result is in the object: friday_items
friday_items=hr_sleep.get('january').get('friday')

#we have "friday_items" the represents "friday" in "january" of hr_sleep dictionary.
#Using the max function in order to obtain the max value.
max_value=max(friday_items)  
print(max_value)

2


5. Add march key to the hr_sleep dictionary using week1 and values2 Python lists. Hint: Use zip function adn this link.

In [44]:
import pandas as pd
import numpy as np

In [45]:
hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

In [46]:
print (hr_sleep)

{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]}, 'february': {'saturday': 5, 'sunday': 10, 'monday': 8}}


In [47]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]
print (week1)
print (values2)

['monday', 'sunday']
[[2, 3, 4], 8]


In [52]:
march = dict( zip( week1, values2))
print(march)  #Zip function is used to pair together one the first items in each iterator.

{'monday': [2, 3, 4], 'sunday': 8}


In [53]:
march2 = {} #Create a new empty dictionary
march2 ["march"] = march #This dictionary is named march 2 and contains item "march" and key created above. 
print (march2)

{'march': {'monday': [2, 3, 4], 'sunday': 8}}


In [54]:
hr_sleep.update (march)  #Use update to aggregate a new key on existing dictionary
print (hr_sleep)

{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]}, 'february': {'saturday': 5, 'sunday': 10, 'monday': 8}, 'monday': [2, 3, 4], 'sunday': 8}


## 1.2 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [13]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>

In [16]:
#Using the information of filtering numbers in python in the link in order to replace the even numbers with 100 in np1.
np1[np1%2==0]=100  

print(np1)

[100 201 100 203 100 205 100 207 100 209 100 211 100 213 100 215 100 217
 100 219 100 221 100 223 100 225 100 227 100 229 100 231 100 233 100 235
 100 237 100 239 100 241 100 243 100 245 100 247 100 249 100 251 100 253
 100 255 100 257 100 259 100 261 100 263 100 265 100 267 100 269 100 271
 100 273 100 275 100 277 100 279 100 281 100 283 100 285 100 287 100 289
 100 291 100 293 100 295 100 297 100 299 100 301 100 303 100 305 100 307
 100 309 100 311 100 313 100 315 100 317 100 319 100 321 100 323 100 325
 100 327 100 329 100 331 100 333 100 335 100 337 100 339 100 341 100 343
 100 345 100 347 100 349 100 351 100 353 100 355 100 357 100 359 100 361
 100 363 100 365 100 367 100 369 100 371 100 373 100 375 100 377 100 379
 100 381 100 383 100 385 100 387 100 389 100 391 100 393 100 395 100 397
 100 399 100 401 100 403 100 405 100 407 100 409 100 411 100 413 100 415
 100 417 100 419 100 421 100 423 100 425 100 427 100 429 100 431 100 433
 100 435 100 437 100 439 100 441 100 443 100 445 10

2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>

In [17]:
matrix= np.arange(0,9,1) #Using the np.arange method to create an array with values from 0 to 8.
matrix3x3 = matrix.reshape(3,3) #Using np.reshape method to convert "matrix" intro a 3 x 3 matrix. 

print(matrix3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>

In [17]:
#Using np.arange to create the array Z.
Z= np.arange(1,11,1) 

#Using np.concatenate to create the array R that it´s compouse of 7 arrays created with np.arange.
R= np.concatenate(([np.arange(1,5,1)], [np.arange(2,6,1)], [np.arange(3,7,1)], 
                   [np.arange(4,8,1)], [np.arange(5,9,1)], [np.arange(6,10,1)], 
                   [np.arange(7,11,1)]))
print(R)
print(Z)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`]

In [22]:
#Using np.random.random in order to create a 3x3x3 array with random values 
array3x3x3 = np.random.random_sample((3,3,3)) 
print(array3x3x3)

[[[0.14880371 0.93493605 0.12589912]
  [0.00783298 0.36989577 0.74871304]
  [0.4600936  0.71611385 0.45843488]]

 [[0.36561875 0.13795091 0.36002703]
  [0.19640615 0.27643201 0.60838082]
  [0.0360846  0.57748868 0.5067313 ]]

 [[0.32010243 0.99972    0.81733106]
  [0.31872246 0.45159172 0.11492587]
  [0.00721932 0.52319437 0.00552583]]]


5. Comment why this expression np.nan == np.nan is False. Hint: Use stackoverflow.

The expression np.nan == np.nan is False because np.nan ("Not a Number") represents an undefined or unrepresentable value. 
The value of np.nan is not equal to any value, including itself because its behavior is that when a mathematical operation results in a undefined value such as 0/0 or sqrt(-1) the result is NaN, but that NaN value has not the same origin, so it is not the same NaN value. 

Because of that, it's not possible to compare two np.nan values.

6. Print the mean and standard deviation of np2. Hint: Use f-string, np.mean, and np.var methods.

In [58]:
np2 = np.random.normal( 50 , 4, 300)

In [62]:
mean = np.mean (np2)
print (mean)

50.041701524011465


In [64]:
variance = np.var (np2)
print (variance)

14.45998854909313


In [66]:
standard_deviation = np.sqrt (variance)
print (standard_deviation)

3.8026291627100752


In [73]:
print (f"Mean of values on np2 is {mean}")

print (f"Standar deviation of values on np2 is {standard_deviation}")

Mean of values on np2 is 50.041701524011465
Standar deviation of values on np2 is 3.8026291627100752


## Restricted Least Squares

Given the following equation:


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$


1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>
2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

In [1]:
import pandas as pd
greene = pd.read_csv(r"/Users/Andre/Documents/GitHub/Diplomado_PUCP/_data/christensen_greene_f4.csv")

In [2]:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

In [3]:
import numpy as np

# First of all, we need to define the terms in the equation
Y = np.log(ct) # This is the term ln(CT)
c = np.ones(len(Y)) # This is the constant that has same number of observations, as the number of observations in the independent variable
x_q = np.log(q) # This is the dependent variable ln(q)
x_qq = np.log(q) * np.log(q) # This is the dependent variable ln(q)^2
x_q1 = np.log(q) * np.log(p1) # This is the dependent variable ln(q)*ln(p1)
x_q2 = np.log(q) * np.log(p2) # This is the dependent ln(q)*ln(p2)
x_q3 = np.log(q) * np.log(p3) # This is the dependent ln(q)*ln(p3)
x_p1 = np.log(p1) # This is the dependent variable ln(p1)
x_p2 = np.log(p2) # This is the dependent variable ln(p2)
x_p3 = np.log(p3) # This is the dependent variable ln(p3)
x_p1p1 = 0.5 * np.log(p1) * np.log(p1) # (1/2)*ln(p1)^2
x_p2p2 = 0.5 * np.log(p2) * np.log(p2) # (1/2)*ln(p2)^2
x_p3p3 = 0.5 * np.log(p3) * np.log(p3) # (1/2)*lnp(p3)^2
x_p1p2 = 0.5 * np.log(p1) * np.log(p2) # (1/2)*ln(p1)*ln(p2)
x_p1p3 = 0.5 * np.log(p1) * np.log(p3) # (1/2)*ln(p1)*ln(p3)
x_p2p3 = 0.5 * np.log(p2) * np.log(p3) # (1/2)*ln(p2)*ln(p3)

# Then we define the X matrix and L matrix 
X = np.asarray([c, x_q, x_qq, x_q1, x_q2,x_q3, x_p1, x_p2, x_p3, x_p1p1, x_p2p2, x_p3p3, x_p1p2, x_p1p3, x_p2p3]).T

L = np.array( ([0,0,0,0,0,0,1,1,1,0,0,0,0,0,0],
               [0,0,0,1,1,1,0,0,0,0,0,0,0,0,0],
               [0,0,0,0,0,0,0,0,0,1,0,0,1,1,0],
               [0,0,0,0,0,0,0,0,0,0,1,0,1,0,1],
               [0,0,0,0,0,0,0,0,0,0,0,1,0,1,1]) )

# Defining the r vector
r = np.array( [1, 0, 0, 0, 0] )

# According to the theory, the b_rls is equal to b_ols plus a term that considers how much b_ols
# doesn't satisfy the restrictions
# So first we need to estimate b_ols, then we can estimate b_rls

# beta OLS
b_ols = np.linalg.inv(X.T @ X) @ (X.T @ Y)

# beta RLS
b_rls = b_ols - np.linalg.inv(X.T @ X) @ L.T @ np.linalg.inv( L @ np.linalg.inv(X.T @ X) @ L.T) @ (L @ b_ols - r )


# Then we label the coefficients
betas = ["beta_0", "beta_q", "beta_qq", "beta_q1", "beta_q2",
          "beta_q3", "beta_p1", "beta_p2", "beta_p3", "beta_p1p1",
          "beta_p2p2", "beta_p3p3", "beta_p1p2", "beta_p1p3", "beta_p2p3"]

##### 1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>

In [4]:
# Showing the results

print('\t\t Results\t')
print('Parameter',' \t\t' ,'OLS' , ' \t\t\t', 'RLS')
print(betas[0]   , ' \t',b_ols[0], ' \t', b_rls[0])
print(betas[1]   , ' \t',b_ols[1], ' \t', b_rls[1])
print(betas[2]   , ' \t',b_ols[2], ' \t', b_rls[2])
print(betas[3]   , ' \t',b_ols[3], ' \t', b_rls[3])
print(betas[4]   , ' \t',b_ols[4], ' \t', b_rls[4])
print(betas[5]   , ' \t',b_ols[5], ' \t', b_rls[5])
print(betas[6]   , ' \t',b_ols[6], ' \t', b_rls[6])
print(betas[7]   , ' \t',b_ols[7], ' \t', b_rls[7])
print(betas[8]   , ' \t',b_ols[8], ' \t', b_rls[8])
print(betas[9]   , ' \t',b_ols[9], ' \t', b_rls[9])
print(betas[10]   , ' \t',b_ols[10], ' \t', b_rls[10])
print(betas[11]   , ' \t',b_ols[11], ' \t', b_rls[11])
print(betas[12]   , ' \t',b_ols[12], ' \t', b_rls[12])
print(betas[13]   , ' \t',b_ols[13], ' \t', b_rls[13])
print(betas[14]   , ' \t',b_ols[14], ' \t', b_rls[14])

		 Results	
Parameter  		 OLS  			 RLS
beta_0  	 -76.25926146656275  	 -7.111200145504128
beta_q  	 -1.0804253568639979  	 0.46136798349312924
beta_qq  	 0.026489246416623757  	 0.02997769675393789
beta_q1  	 0.13104058702720067  	 -0.004354401896267346
beta_q2  	 0.058652203004839976  	 0.03677797912031289
beta_q3  	 0.04014440021046539  	 -0.032423577224046
beta_p1  	 14.71829254925251  	 0.21556634414485742
beta_p2  	 -0.8947329132352024  	 0.4029230270343964
beta_p3  	 6.380797025747597  	 0.3815106288206156
beta_p1p1  	 -1.5385273529682308  	 -0.008712239864907545
beta_p2p2  	 -0.07350555841912865  	 0.005155675581659039
beta_p3p3  	 -0.3274142669979483  	 -0.015301676695891497
beta_p1p2  	 0.32456578317214735  	 -0.005872556206318769
beta_p1p3  	 -1.144100975128822  	 0.01458479607124219
beta_p2p3  	 -0.0480493950744858  	 0.0007168806246610065


##### 2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

In [5]:
# To estimate the covariance matrix we need to estimate the vector of residuals and the standart deviation
# Defining errors and variance
residuals = Y - X @ b_ols
sigma_sqr = ( residuals.T @ residuals) / (len(Y)-(len(X[0])+1))

# getting var_beta_rls
var_b_rls = sigma_sqr * np.linalg.inv(X.T @ X) - sigma_sqr * np.linalg.inv(X.T @ X) @ L.T @ np.linalg.inv( L @ np.linalg.inv(X.T @ X) @ L.T) @ L @ np.linalg.inv(X.T @ X)

# Finally we show the var-cov coef. matrix
vbr = pd.DataFrame(var_b_rls)
vbr.columns = betas
vbr.index = betas
vbr

beta_0    beta_q   beta_qq   beta_q1   beta_q2   beta_q3  \
beta_0     7.648283 -0.086668  0.000093  0.014129 -0.019922  0.005793   
beta_q    -0.086668  0.014434 -0.000031 -0.002625  0.002046  0.000579   
beta_qq    0.000093 -0.000031  0.000005 -0.000007 -0.000001  0.000008   
beta_q1    0.014129 -0.002625 -0.000007  0.000527 -0.000328 -0.000200   
beta_q2   -0.019922  0.002046 -0.000001 -0.000328  0.000590 -0.000262   
beta_q3    0.005793  0.000579  0.000008 -0.000200 -0.000262  0.000462   
beta_p1   -2.749398  0.010989 -0.000017 -0.001241  0.004595 -0.003354   
beta_p2    1.454277 -0.013284  0.000068  0.001534 -0.005516  0.003983   
beta_p3    1.295121  0.002295 -0.000051 -0.000292  0.000921 -0.000629   
beta_p1p1  0.357380  0.001436  0.000011 -0.000432 -0.000300  0.000732   
beta_p2p2 -0.082861 -0.002631  0.000028  0.000506  0.000052 -0.000558   
beta_p3p3 -0.740994 -0.001187 -0.000044  0.000517  0.000415 -0.000933   
beta_p1p2 -0.507756  0.000004 -0.000041  0.000222  0.000332 -0.000553   
beta_p1p3  0.150377 -0.001440  0.000030  0.000211 -0.000032 -0.000179   
beta_p2p3  0.590617  0.002627  0.000014 -0.000728 -0.000383  0.001111   

            beta_p1   beta_p2   beta_p3  beta_p1p1  beta_p2p2  beta_p3p3  \
beta_0    -2.749398  1.454277  1.295121   0.357380  -0.082861  -0.740994   
beta_q     0.010989 -0.013284  0.002295   0.001436  -0.002631  -0.001187   
beta_qq   -0.000017  0.000068 -0.000051   0.000011   0.000028  -0.000044   
beta_q1   -0.001241  0.001534 -0.000292  -0.000432   0.000506   0.000517   
beta_q2    0.004595 -0.005516  0.000921  -0.000300   0.000052   0.000415   
beta_q3   -0.003354  0.003983 -0.000629   0.000732  -0.000558  -0.000933   
beta_p1    1.037901 -0.531437 -0.506464  -0.141017   0.041095   0.279112   
beta_p2   -0.531437  0.309258  0.222179   0.070338  -0.002296  -0.154323   
beta_p3   -0.506464  0.222179  0.284285   0.070679  -0.038800  -0.124789   
beta_p1p1 -0.141017  0.070338  0.070679   0.020010  -0.007440  -0.037810   
beta_p2p2  0.041095 -0.002296 -0.038800  -0.007440   0.025888  -0.005723   
beta_p3p3  0.279112 -0.154323 -0.124789  -0.037810  -0.005723   0.090825   
beta_p1p2  0.189517 -0.111183 -0.078334  -0.025190  -0.012085   0.067179   
beta_p1p3 -0.048500  0.040845  0.007655   0.005180   0.019525  -0.029369   
beta_p2p3 -0.230612  0.113478  0.117134   0.032630  -0.013802  -0.061456   

           beta_p1p2  beta_p1p3  beta_p2p3  
beta_0     -0.507756   0.150377   0.590617  
beta_q      0.000004  -0.001440   0.002627  
beta_qq    -0.000041   0.000030   0.000014  
beta_q1     0.000222   0.000211  -0.000728  
beta_q2     0.000332  -0.000032  -0.000383  
beta_q3    -0.000553  -0.000179   0.001111  
beta_p1     0.189517  -0.048500  -0.230612  
beta_p2    -0.111183   0.040845   0.113478  
beta_p3    -0.078334   0.007655   0.117134  
beta_p1p1  -0.025190   0.005180   0.032630  
beta_p2p2  -0.012085   0.019525  -0.013802  
beta_p3p3   0.067179  -0.029369  -0.061456  
beta_p1p2   0.052227  -0.027037  -0.040142  
beta_p1p3  -0.027037   0.021857   0.007512  
beta_p2p3  -0.040142   0.007512   0.053944

# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [ ]:
# read REC0111 data
#!pip install savReaderWriter
import savReaderWriter as sav
rec1 = pd.read_spss( fr"../../_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"../../_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]
dict_varlabels

**Answers**

In [75]:
# Firstly we import pandas as "pd" and install the libraries "savReaderWriter" and "pyreadstat". Both are used for reading SPSS files with Python and allow us to read theses files with pandas data frame.
import pandas as pd
!pip install savReaderWriter
!pip install pyreadstat

#Now we import "savReaderWriter" as "sav" and open "REC0111.sav" as a pandas dataframe "rec1"
import savReaderWriter as sav
rec1 = pd.read_spss( fr"C:/Users/hecto/OneDrive/Documents/GitHub/Diplomado_PUCP/_data/endes/2019/REC0111.sav" )

#Now we get labels from sav file
with sav.SavHeaderReader( fr"C:/Users/hecto/OneDrive/Documents/GitHub/Diplomado_PUCP/_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

#Here we can see the labels of the variables (or column headers) of the dataframe
dict_varlabels = metadata[3]
dict_varlabels

{'ID1': 'Año',
 'HHID': 'Identificación Cuestionario del Hogar',
 'CASEID': 'Identificación Cuestionario Individual',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V013': 'Edad actual por grupos de 5 años',
 'V014': 'Integridad de la información para la fecha de nacimiento ',
 'V015': 'Resultado entrevista individual',
 'V017': 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'V018': 'Columna del mes de la entrevista',
 'V019': 'Duración del calendario',
 'V019A': 'Número de columnas de calendario',
 'V020': 'Muestra alguna vez casada',
 'V021': 'Unidad de muestreo primar

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**

In [9]:
#It is important to know if "CASEID" column has unique observations because we will make it our index column.
#If the index column is not unique, which means that it has duplicate rows with the same index value, can lead to confusion and errors when trying to manipulate the data. Also can bring issues when trying to merge data with other dataframes. 
#It is important to ensure that the index is unique to maintain the integrity and accuracy of the data in the dataframe.

#We use the is_unique method to check if the "CASEID" column each observation uniquely.
if rec1["CASEID"].is_unique:
    print("CASEID column identifies each observation uniquely")
else:
    print("CASEID column does not identify each observation uniquely")

CASEID column identifies each observation uniquely


2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 

In [77]:
#We use the set_index method to set as index the "CASEID" column.
rec1=rec1.set_index("CASEID") 

In [78]:
#We verify that the "CASEID" is now the index column with the .index.name method.
if rec1.index.name == 'CASEID':
    print("CASEID is the index of the DataFrame.")
else:
    print("CASEID is not the index of the DataFrame.")


CASEID is the index of the DataFrame.


3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.

In [79]:
#First, we analyze the "V102" and "V013" variables, which describe whether the place of residence is rural or urban and the age group of the interviewees respectively. We use for this the .value_counts() method.
urban_counts = rec1["V102"].value_counts()
print(urban_counts)
age_counts = rec1["V013"].value_counts()
print(age_counts)

Urbano    26133
Rural     10789
Name: V102, dtype: int64
De 25 a 29 años de edad    5836
De 30 a 34 años de edad    5808
De 20 a 24 años de edad    5350
De 35 a 39 años de edad    4951
De 15 a 19 años de edad    4668
De 40 a 44 años de edad    3892
De 12 a 14 años de edad    3633
De 45 a 49 años de edad    2784
Name: V013, dtype: int64


In [80]:
#We use the query() method to filter the data based on specific conditions. 
#In this case we keep all the observations where the interviewees live in a urban area and are between 15 and 30 years old. 
rec1 = rec1.query("V013 in ['De 15 a 19 años de edad', 'De 20 a 24 años de edad', 'De 25 a 29 años de edad'] and V102 == 'Urbano' ")

#We confirm the changes done on the observations in the dataframe
urban_counts = rec1["V102"].value_counts()
print(urban_counts)
age_counts = rec1["V013"].value_counts()
print(age_counts)

Urbano    11327
Rural         0
Name: V102, dtype: int64
De 25 a 29 años de edad    4306
De 20 a 24 años de edad    3864
De 15 a 19 años de edad    3157
De 12 a 14 años de edad       0
De 30 a 34 años de edad       0
De 35 a 39 años de edad       0
De 40 a 44 años de edad       0
De 45 a 49 años de edad       0
Name: V013, dtype: int64


4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [81]:
#First, we analyze the variable "V009" which has the label of "Interviewee's month of birth"
print(rec1.V009)

CASEID
      000104801  2     5.0
      000116701  1     6.0
      000119101  1     9.0
      000203001  2     5.0
      000204001  3     9.0
                      ... 
      324202401  2     2.0
      324202501  3     5.0
      324203901  1     8.0
      324204501  2     5.0
      324206901  3    10.0
Name: V009, Length: 11327, dtype: float64


In [83]:
month_counts = rec1["V009"].value_counts()
print(month_counts)

9.0     1025
8.0     1002
3.0     1000
5.0      991
6.0      986
7.0      968
4.0      946
12.0     917
10.0     889
11.0     874
1.0      870
2.0      859
Name: V009, dtype: int64


In [84]:
#We can see that the "V009" column has numbers representing the order number of the months.
#In that way, we use the replace() method and create the column "month_name", which uses the number of the month from "V009" and replaces it with the first three letters of the month name in English. 
rec1["month_name"] = rec1["V009"].replace({
    1: 'Jan',
    2: 'Feb',
    3: 'Mar',
    4: 'Apr',
    5: 'May',
    6: 'Jun',
    7: 'Jul',
    8: 'Aug',
    9: 'Sep',
    10: 'Oct',
    11: 'Nov',
    12: 'Dec'
})

#We verify the column created:
month_name_counts = rec1["month_name"].value_counts()
print(month_name_counts)

Sep    1025
Aug    1002
Mar    1000
May     991
Jun     986
Jul     968
Apr     946
Dec     917
Oct     889
Nov     874
Jan     870
Feb     859
Name: month_name, dtype: int64
