# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Dictionaries


1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>
2. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>
3. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>
4. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries](https://stackoverflow.com/questions/25836376/how-to-get-the-inner-indexes-of-a-nested-dictionary-in-python).** <br><br>

In [92]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

5. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists. **Hint: Use `zip` function adn [this link](https://stackoverflow.com/questions/1024847/how-can-i-add-new-keys-to-a-dictionary).** <br><br>

In [93]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

In [94]:
hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

In [95]:
#From lists to dictionary. Assign keys and values
keys = week1 
values = values2 

In [96]:
#check that they are the same length
len(keys)

2

In [97]:
len(values)

2

In [98]:
# Return a dictionary
march = dict( zip( keys , values ) )
march

{'monday': [2, 3, 4], 'sunday': 8}

In [99]:
#Add march key to the hr_sleep dictionary
hr_sleep["March"] = march
hr_sleep

{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]},
 'february': {'saturday': 5, 'sunday': 10, 'monday': 8},
 'March': {'monday': [2, 3, 4], 'sunday': 8}}

## 1.2 Numpy

In [100]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>

In [101]:
#We see that the array np1 is composed of values from 200 to 749 incremented by 1
print(np1)

[200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235
 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253
 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271
 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289
 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307
 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325
 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343
 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361
 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379
 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397
 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415
 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433
 434 435 436 437 438 439 440 441 442 443 444 445 44

In [102]:
#We filter even numbers: numbers that have a remainder of 0 when divided by 2. 
np1 [np1%2 == 0] = 100

In [103]:
#We print the array again and see that all even number have been replaced with 100.
print(np1)

[100 201 100 203 100 205 100 207 100 209 100 211 100 213 100 215 100 217
 100 219 100 221 100 223 100 225 100 227 100 229 100 231 100 233 100 235
 100 237 100 239 100 241 100 243 100 245 100 247 100 249 100 251 100 253
 100 255 100 257 100 259 100 261 100 263 100 265 100 267 100 269 100 271
 100 273 100 275 100 277 100 279 100 281 100 283 100 285 100 287 100 289
 100 291 100 293 100 295 100 297 100 299 100 301 100 303 100 305 100 307
 100 309 100 311 100 313 100 315 100 317 100 319 100 321 100 323 100 325
 100 327 100 329 100 331 100 333 100 335 100 337 100 339 100 341 100 343
 100 345 100 347 100 349 100 351 100 353 100 355 100 357 100 359 100 361
 100 363 100 365 100 367 100 369 100 371 100 373 100 375 100 377 100 379
 100 381 100 383 100 385 100 387 100 389 100 391 100 393 100 395 100 397
 100 399 100 401 100 403 100 405 100 407 100 409 100 411 100 413 100 415
 100 417 100 419 100 421 100 423 100 425 100 427 100 429 100 431 100 433
 100 435 100 437 100 439 100 441 100 443 100 445 10

2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>

In [104]:
# Create a 1D NumPy array with values from 0 to 8 incremented by 1:
array = np.arange( 0, 9, 1 ) 
print(array)

[0 1 2 3 4 5 6 7 8]


In [105]:
#Convert the 1-D array with 9 elements into a 3x3 matrix using the n.p reshape method
matrix = array.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>

FORM 1

In [106]:
# 1D array Z
Z = np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] )
print(Z)

[ 1  2  3  4  5  6  7  8  9 10]


In [52]:
# Create each individual vector using np.arrange
a = np.arange ( 1, 5)
print(a)
b = np.arange( 2, 6)
print(b) 
c = np.arange( 3, 7)
print(c)
d = np.arange( 4, 8)
print(d)
e = np.arange( 5, 9)
print(e)
f = np.arange( 6, 10)
print(f)
g = np.arange( 7, 11)
print(g)

[1 2 3 4]
[2 3 4 5]
[3 4 5 6]
[4 5 6 7]
[5 6 7 8]
[6 7 8 9]
[ 7  8  9 10]


In [71]:
#Generating an array R using np.concatenate to join the individual vectors into one.
R = np.concatenate((a, b, c, d, e, f, g), axis=0) 
print(R)

[ 1  2  3  4  2  3  4  5  3  4  5  6  4  5  6  7  5  6  7  8  6  7  8  9
  7  8  9 10]


FORM 2

In [73]:
z= np.arange(1,11) #We create the array Z
R = np.concatenate(([z[0:4]], [z[1:5]], [z[2:6]], [z[3:7]],[z[4:8]],[z[5:9]],[z[6:10]])) #We concatenate the array by selecting the indicated values 
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>

In [109]:
np.random.random( (3,3,3) )  #It's a funtion that returns an array with 3 sub arrays of random floats of shape size (3x3). 
#The first sub argument is to create the number of subarrays, the second one to rows and finally, the third one is to the columns. 

array([[[0.24814784, 0.4394413 , 0.46425967],
        [0.66422865, 0.20511917, 0.66136323],
        [0.75677067, 0.3314973 , 0.65508102]],

       [[0.78037258, 0.12913994, 0.25095822],
        [0.5479428 , 0.56791197, 0.96897832],
        [0.58595676, 0.35508587, 0.96160249]],

       [[0.94507955, 0.98522773, 0.3324286 ],
        [0.69883843, 0.9943248 , 0.91307325],
        [0.92912548, 0.24798511, 0.93928786]]])

5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>


In principle, np.nan are not numbers, but are undefined values that are substitutes for the empty spaces of an array, in this case, since we are working with numpys. So, it does not make much mathematical sense to compare two undefined values. 

6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [110]:
mean =  round( np.mean(np2) ) #we use the function np.mean to calculate the mean of the array. Then we round the number. 
sd = round( np.sqrt ( np.var (np2) ) ) #we use the function np.var to calculate the var of the array. Then then we calculate the square root of that number and thus obtain the sd.


In [111]:
 print( f'The mean is {mean} and its standard deviation is {sd}') #we print 

The mean is 50 and its standard deviation is 4


## Restricted Least Squares

Given the following equation:


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$

In [124]:
import pandas as pd
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

In [125]:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>

In [123]:
import numpy as np
greene

id  YEAR     COST        Q        PL      SL      PK      SK      PF  \
0      1  1970   0.2130      8.0   6869.47  0.3291  64.945  0.4197  18.000   
1      4  1970   3.0427    869.0   8372.96  0.1030  68.227  0.2913  21.067   
2      5  1970   9.4059   1412.0   7960.90  0.0891  40.692  0.1567  41.530   
3     14  1970   0.7606     65.0   8971.89  0.2802  41.243  0.1282  28.539   
4     15  1970   2.2587    295.0   8218.40  0.1772  71.940  0.1623  39.200   
..   ...   ...      ...      ...       ...     ...     ...     ...     ...   
153  214  1970   6.8293    946.6  10642.16  0.0883  43.600  0.1914  51.463   
154  215  1970   3.7605    377.0   7432.24  0.2117  74.120  0.2274  33.436   
155  216  1970   3.9822    391.0   5826.04  0.1926  78.288  0.0924  44.633   
156  217  1970  30.1880   5317.0   9586.63  0.0845  78.008  0.2009  41.840   
157  218  1970  67.8562  15220.0   6986.09  0.1451  74.025  0.2596  25.662   

        SF   
0    0.2512  
1    0.6057  
2    0.7542  
3    0.5916  
4    0.6606  
..      ...  
153  0.7203  
154  0.5609  
155  0.7151  
156  0.7147  
157  0.5945  

[158 rows x 10 columns]

$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$



In [139]:
#First, we construct the variables 
lnCT =np.log(ct).reshape(-1,1)

x0 = np.ones( len(greene) )  #we create a vector of 1's. 
x1=np.log(q)
x2= (1/2)*np.log(np.sqrt(q))
x3=np.log(q)*np.log(p1)
x4=np.log(q)*np.log(p2)
x5=np.log(q)*np.log(p3)
x6=np.log(p1)
x7=np.log(p2)
x8=np.log(p3)
x9=0.5*np.log(p1)**(2)
x10=0.5*np.log(p2)**(2)
x11=0.5*np.log(p3)**(2)
x12=0.5*np.log(p1)*np.log(p2)
x13=0.5*np.log(p1)*np.log(p3)
x14=0.5*np.log(p2)*np.log(p3)



In [127]:
#Create the matrix X
X = np.hstack(( x0.reshape(-1, 1 ) , x1.reshape(-1, 1 ), x2.reshape(-1, 1 ), x3.reshape(-1, 1 ), x4.reshape(-1, 1 )
              , x5.reshape(-1, 1 ), x6.reshape(-1, 1 ), x7.reshape(-1, 1 ), x8.reshape(-1, 1 ), x9.reshape(-1, 1 )
              , x10.reshape(-1, 1 ), x11.reshape(-1, 1 ), x12.reshape(-1, 1 ), x13.reshape(-1, 1 ), x14.reshape(-1, 1 )))
X.shape

(158, 15)

In [132]:
#We create the matrix of restrictions L*beta = r
L_1 = np.array([0,0,0,0,0,0,1,1,1,0,0,0,0,0,0])
L_2 = np.array([0,0,0,1,1,1,0,0,0,0,0,0,0,0,0])
L_3 = np.array([0,0,0,0,0,0,0,0,0,1,0,0,1,1,0])
L_4 = np.array([0,0,0,0,0,0,0,0,0,0,1,0,1,0,1])
L_5 = np.array([0,0,0,0,0,0,0,0,0,0,0,1,0,1,1])

L = np.vstack(( L_1, L_2, L_3, L_4, L_5 ))
L.shape
L


array([[0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1]])

In [140]:
r = np.array([1,0,0,0,0]).reshape(-1, 1 )
r.shape
lnCT.shape

(158, 1)

We calculate the following according to this [`page`](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).

$$
\widehat{\beta }^{\left( RLS\right) } = \widehat{\beta }^{\left( OLS\right) } - \left[
 X^{T}X\right] ^{-1}L^{T}\left( L\left(
X^{T}X\right) ^{-1}L^{T}\right) ^{-1}\left( L\widehat{\beta }^{\left( OLS\right) }-r\right) 
$$


In [141]:
#First, we calculate the beta OLS
beta_ols = np.linalg.inv(X.T @ X) @ X.T @ lnCT
beta_ols

array([[-1.81364785e+01],
       [-7.75794873e+02],
       [ 3.09174577e+03],
       [ 3.03500392e-01],
       [ 8.39207720e-02],
       [ 9.24993121e-02],
       [ 7.60494052e+00],
       [-5.91269457e+00],
       [ 2.27111177e+00],
       [-1.12847196e+00],
       [-1.98222478e-01],
       [ 2.43326855e-01],
       [ 1.26826593e+00],
       [-1.00949995e+00],
       [ 4.12353351e-01]])

In [163]:
#Calculate the beta RLS
beta_rls = beta_ols - np.linalg.inv(X.T @ X)  @ L.T @ np.linalg.inv(L @ np.linalg.inv(X.T @ X) @ L.T) @ (L@ beta_ols - r)
beta_rls


array([[-5.39482863e+00],
       [-7.58734616e+02],
       [ 3.03637703e+03],
       [ 4.44106970e-02],
       [ 4.39271042e-02],
       [-8.83378011e-02],
       [ 3.27955314e-01],
       [-4.46628425e-02],
       [ 7.16707528e-01],
       [-8.31067347e-02],
       [-1.78254950e-01],
       [ 2.72618619e-01],
       [ 2.66990152e-01],
       [-1.83883417e-01],
       [-8.87352022e-02]])

2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

$$
Var\left( \widehat{\beta }^{\left( RLS\right) }\right) =\sigma ^{2}\left[
X^{T}X\right] ^{-1}-\sigma ^{2}\left[ X^{T}X\right] ^{-1}L^{T}\left( L\left(
X^{T}X\right) ^{-1}L^{T}\right) ^{-1}L\left( X^{T}X\right) ^{-1}
$$

In [161]:
#We calculate the Y_pred
y_pred = X @ beta_ols

# We calculate the standard error of the regression
sigma2 = ( (1 / (len(greene) - X.shape[1]+1-L.shape[0])) * (y_pred - lnCT).T  @ (y_pred - lnCT))
sigma = np.sqrt(var)
sigma 

array([[0.63198512]])

In [162]:
#
Cov_Var_RLS=sigma*(np.linalg.inv(X.T@X))-sigma*(np.linalg.inv(X.T@X)@L.T@np.linalg.inv(L@np.linalg.inv(X.T@X)@L.T)@L@np.linalg.inv(X.T@X))
Cov_Var_RLS

array([[ 2.78451305e+02,  2.05956190e+02, -8.36354305e+02,
         5.20021101e-01, -7.24676295e-01,  2.04655194e-01,
        -1.00109601e+02,  5.29086417e+01,  4.72009588e+01,
         1.30059814e+01, -3.03811608e+00, -2.69516470e+01,
        -1.84597562e+01,  5.45377476e+00,  2.14978723e+01],
       [ 2.06870738e+02,  3.47437496e+11, -1.38974998e+12,
        -1.84198172e-01, -6.46037109e-02,  2.48801883e-01,
        -7.87141062e+01,  4.47830640e+01,  3.39310421e+01,
         1.06391211e+01,  3.67076638e+00, -2.71215020e+01,
        -2.07156947e+01,  1.00765736e+01,  1.70449284e+01],
       [-8.40013823e+02, -1.38974998e+12,  5.55899994e+12,
         3.47028731e-01,  5.55298713e-01, -9.02327444e-01,
         3.16439987e+02, -1.80998947e+02, -1.35441040e+02,
        -4.23359386e+01, -1.50382532e+01,  1.08269186e+02,
         8.28216890e+01, -4.04857504e+01, -6.77834358e+01],
       [ 5.20021101e-01, -1.83514457e-01,  3.44293874e-01,
         1.87621606e-02, -1.19907973e-02, -6.77136335

# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.


In [4]:
# read REC0111 data
#!pip install savReaderWriter
# install pyreadstat
#!pip install pyreadstat 

In [5]:
import pandas as pd ## Import pandas library 
import numpy as np ## Import numpy library 

In [6]:
import savReaderWriter as sav
rec1 = pd.read_spss( fr"../../_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"../../_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]


In [7]:
dict_varlabels

{'ID1': 'Año',
 'HHID': 'Identificación Cuestionario del Hogar',
 'CASEID': 'Identificación Cuestionario Individual',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V013': 'Edad actual por grupos de 5 años',
 'V014': 'Integridad de la información para la fecha de nacimiento ',
 'V015': 'Resultado entrevista individual',
 'V017': 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'V018': 'Columna del mes de la entrevista',
 'V019': 'Duración del calendario',
 'V019A': 'Número de columnas de calendario',
 'V020': 'Muestra alguna vez casada',
 'V021': 'Unidad de muestreo primar

1. Check if CASEID identifies each observation uniquely. Hint: Use is_unique method.

In [8]:
rec1['CASEID'].is_unique ## TRUE, each ID is unique

True

2. Make the CASEID column the index of your data set. Hint: Use set_index.

In [9]:
rec1.columns ## Show columns names from base rec1

Index(['ID1', 'HHID', 'CASEID', 'V001', 'V002', 'V003', 'V004', 'V007', 'V008',
       'V009',
       ...
       'QD333_4', 'QD333_5', 'QD333_6', 'UBIGEO', 'V022', 'V005', 'V190',
       'V191', 'mujeres12a49', 'NCONGLOME'],
      dtype='object', length=105)

In [10]:
rec1.set_index('CASEID', drop=True, inplace=True) ## use set_index on data rec1 to convert CASEID to the index of the data
rec1

ID1             HHID    V001  V002  V003    V004  \
CASEID                                                                    
      000100201  2  2019.0        000100201     1.0   2.0   2.0     1.0   
      000100201  3  2019.0        000100201     1.0   2.0   3.0     1.0   
      000102801  2  2019.0        000102801     1.0  28.0   2.0     1.0   
      000102801  6  2019.0        000102801     1.0  28.0   6.0     1.0   
      000104801  2  2019.0        000104801     1.0  48.0   2.0     1.0   
...                    ...              ...     ...   ...   ...     ...   
      325406201  2  2019.0        325406201  3254.0  62.0   2.0  3254.0   
      325406301  2  2019.0        325406301  3254.0  63.0   2.0  3254.0   
      325407001  2  2019.0        325407001  3254.0  70.0   2.0  3254.0   
      325407201  2  2019.0        325407201  3254.0  72.0   2.0  3254.0   
      325407401  2  2019.0        325407401  3254.0  74.0   2.0  3254.0   

                      V007    V008  V009    V010  ...  QD333_4  QD333_5  \
CASEID                                            ...                     
      000100201  2  2019.0  1434.0   4.0  1986.0  ...       No       No   
      000100201  3  2019.0  1434.0   1.0  2007.0  ...       No       No   
      000102801  2  2019.0  1434.0   6.0  1983.0  ...       No       No   
      000102801  6  2019.0  1434.0   3.0  1970.0  ...       No       No   
      000104801  2  2019.0  1434.0   5.0  1991.0  ...       No       No   
...                    ...     ...   ...     ...  ...      ...      ...   
      325406201  2  2019.0  1440.0  12.0  1971.0  ...       No       No   
      325406301  2  2019.0  1440.0   6.0  1988.0  ...       No       No   
      325407001  2  2019.0  1440.0   7.0  1973.0  ...       No       No   
      325407201  2  2019.0  1440.0  12.0  1994.0  ...       No       No   
      325407401  2  2019.0  1440.0  10.0  1996.0  ...       No       No   

                   QD333_6  UBIGEO   V022      V005          V190      V191  \
CASEID                                                                        
      000100201  2      No  010101    3.0  154803.0          Rico  1.234450   
      000100201  3      No  010101    3.0  154803.0          Rico  1.234450   
      000102801  2      No  010101    3.0  154803.0          Rico  1.295611   
      000102801  6      No  010101    3.0  154803.0          Rico  1.295611   
      000104801  2      No  010101    3.0  154803.0        Pobrer -0.256431   
...                    ...     ...    ...       ...           ...       ...   
      325406201  2      No  250401  249.0  244995.0  El más pobre -1.750187   
      325406301  2      No  250401  249.0  244995.0  El más pobre -1.676861   
      325407001  2      No  250401  249.0  459792.0  El más pobre -1.585333   
      325407201  2      No  250401  249.0  459792.0  El más pobre -1.650159   
      325407401  2      No  250401  249.0  244995.0  El más pobre -1.644720   

                                                     mujeres12a49 NCONGLOME  
CASEID                                                                       
      000100201  2                Mujeres de 15 a 49 años de edad    7065.0  
      000100201  3  Mujeres de 12 a 14 de edad, nunca embarazadas    7065.0  
      000102801  2                Mujeres de 15 a 49 años de edad    7065.0  
      000102801  6                Mujeres de 15 a 49 años de edad    7065.0  
      000104801  2                Mujeres de 15 a 49 años de edad    7065.0  
...                                                           ...       ...  
      325406201  2                Mujeres de 15 a 49 años de edad   15783.0  
      325406301  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407001  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407201  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407401  2                Mujeres de 15 a 49 años de edad   15783.0  

[38335 rows x 104 columns]

3. Keep women who are 15-30 years old and live in Urban areas. Hint: Use query.

In [11]:
rec1.V010 ## indicates values of  V010 'Año de nacimiento de la entrevistada'

CASEID
      000100201  2    1986.0
      000100201  3    2007.0
      000102801  2    1983.0
      000102801  6    1970.0
      000104801  2    1991.0
                       ...  
      325406201  2    1971.0
      325406301  2    1988.0
      325407001  2    1973.0
      325407201  2    1994.0
      325407401  2    1996.0
Name: V010, Length: 38335, dtype: float64

In [12]:
#first step --> Urban areas
rec1 = rec1[rec1['V102'] == 'Urbano'] ## filter observations of Urban areas 

In [13]:
#second step -->  women who are 15-30 years old
rec1['V010'].min() ## shows the minimun value of V010

1969.0

In [14]:
rec1['V010'].max() ## shows the maximum value of V010

2007.0

In [15]:
rec1.shape ## verifica tamaño base de datos filte

(26133, 104)

In [16]:
2019-15 ## from the year of the survey, subtract  15 years 

2004

In [17]:
2019-30 ## from the year of the survey, subtract  30 years

1989

In [18]:
rec1 = rec1.query('  V010  >= 1989  &  V010  <= 2004') ## filter observations of women who are 15-30 years old based on years of her birth

In [19]:
rec1.shape ## check new database size 

(12127, 104)

In [20]:
rec1['V010'].min() ## check new minimun value of V010

1989.0

In [21]:
rec1['V010'].max()  ## check new maximum value of V010

2004.0

4. Generate a new column with the month of born. Just use the first three letters. Use the English names of the months.

In [22]:
rec1.V009 ## ## indicates values of  V009 'Mes de nacimiento de la entrevistada'


CASEID
      000104801  2     5.0
      000116701  1     6.0
      000119101  1     9.0
      000203001  2     5.0
      000204001  3     9.0
                      ... 
      324202401  2     2.0
      324202501  3     5.0
      324203901  1     8.0
      324204501  2     5.0
      324206901  3    10.0
Name: V009, Length: 12127, dtype: float64

In [23]:
def conditions(x):  ## Function that names months based on month number
    if   x == 1 :   return "jan" 
    elif x == 2 :   return "feb"
    elif x == 3 :   return "mar"
    elif x == 4 :   return "apr"
    elif x == 5 :   return "may"
    elif x == 6 :   return "jun"
    elif x == 7 :   return "jul"
    elif x == 8 :   return "aug"
    elif x == 9 :   return "sep"
    elif x == 10 :   return "oct"
    elif x == 11 :   return "nov"
    else:   return "dec"

In [24]:
func         = np.vectorize(conditions) ## vectorizes the results of the conditions function
rec1['month'] = func(rec1['V009']) ## applies the function to the variable V009 and creates the new column 'month' 

In [25]:
rec1.month ## display the new column in the same base rec1

CASEID
      000104801  2    may
      000116701  1    jun
      000119101  1    sep
      000203001  2    may
      000204001  3    sep
                     ... 
      324202401  2    feb
      324202501  3    may
      324203901  1    aug
      324204501  2    may
      324206901  3    oct
Name: month, Length: 12127, dtype: object