# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Dictionaries
1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>
2. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>
3. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>
4. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries](https://stackoverflow.com/questions/25836376/how-to-get-the-inner-indexes-of-a-nested-dictionary-in-python).** <br><br>
5. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists. **Hint: Use `zip` function adn [this link](https://stackoverflow.com/questions/1024847/how-can-i-add-new-keys-to-a-dictionary).** <br><br>

In [3]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

In [4]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

In [5]:
## Pregunta 2
car.get("brand")

'Ford'

In [7]:
## Pregunta 3
car.values()

dict_values(['Ford', 'Mustang', 1964])

## 1.2 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [2]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

## 1.3 Restricted Least Squares

Given the following equation:


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$


1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>
2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

In [47]:
# 1. Get 𝜷ˆ(𝑅𝐿𝑆) vector from the equation bellow. Use the q, p1, p2, p3, CT numpies.

# First we import the relevant libraries:

import numpy as np
from math import log
import pandas as pd

In [48]:
# Now we import the dataset considering the proposed name "greene"
greene = pd.read_csv(r"/Users/joselinchavez/Documents/GitHub/Diplomado_PUCP/Lecture_3/christensen_greene_f4.csv")

#In this case we use the path to the folder where the database 
#is stored because it couldn't be taken directly.

In [49]:
#We can check the database
greene.describe()

id    YEAR        COST              Q            PL  \
count  158.000000   158.0  158.000000     158.000000    158.000000   
mean   127.208861  1970.0   53.269962   10469.410759   8001.863228   
std     60.792333     0.0   87.059326   15187.520802   1398.837478   
min      1.000000  1970.0    0.130400       4.000000   5063.490000   
25%     78.500000  1970.0   10.221050    1971.000000   6975.177500   
50%    138.500000  1970.0   25.545400    5645.500000   7890.185000   
75%    178.750000  1970.0   55.315900   12365.750000   8855.230000   
max    218.000000  1970.0  737.408800  115500.000000  13044.000000   

               SL          PK          SK          PF         SF   
count  158.000000  158.000000  158.000000  158.000000  158.000000  
mean     0.138972   71.421063    0.226387   30.745785    0.632355  
std      0.054735   11.977489    0.060836    7.943089    0.083324  
min      0.045900   31.725000    0.092400    9.000000    0.243500  
25%      0.099725   67.605000    0.192550   24.477350    0.590100  
50%      0.123100   74.120000    0.218600   30.657900    0.645000  
75%      0.169800   78.794250    0.252775   36.000000    0.686900  
max      0.329100   92.650000    0.457100   51.463000    0.813600

In [50]:
# We use the provided renaming:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

In [51]:
# We also took logs of the relevant variables (14 variables 
# without the intercept, independents) and we can give it the same form as 
#requested by proposed equation 

ln_q = np.log(q)
ln2_q = 0.5*np.square(ln_q) # in this case we need the additional 
# square to logarithm

ln_p1 = np.log(p1)
ln_p2 = np.log(p2)
ln_p3 = np.log(p3)

ln_qp1 = np.multiply(ln_q, ln_p1) # in this case we need to multiply
# adittional to logarithm
ln_qp2 = np.multiply(ln_q, ln_p2)
ln_qp3 = np.multiply(ln_q, ln_p3)

ln2_p1 = 0.5*np.square(ln_p1)
ln2_p2 = 0.5*np.square(ln_p2)
ln2_p3 = 0.5*np.square(ln_p3)

ln_p1p2 = np.multiply(ln_p1, ln_p2)
ln_p1p3 = np.multiply(ln_p1, ln_p3)
ln_p2p3 = np.multiply(ln_p2, ln_p3)

In [56]:
# Now we create the intercept with the function ones:
intercept = np.ones((len(q), 1))
#intercept

# Likewise, we take logarithm of the dependent variable:
ln_ct = np.log(ct)
#ln_ct

In [65]:
# We must also create the big X matrix, it must contain the 14 
# variables and the intercept, so we use the function stack for columns

X_big = np.column_stack([intercept, ln_q, ln2_q, ln_qp1, ln_qp2, 
                         ln_qp3, ln_p1, ln_p2, ln_p3, ln2_p1, ln2_p2,
                         ln2_p3, ln_p1p2, ln_p1p3, ln_p2p3])

X_big

array([[ 1.        ,  2.07944154,  2.16203856, ..., 25.53597848,
        36.87257416, 12.06308434],
       [ 1.        ,  6.76734313, 22.89846649, ..., 27.52922179,
        38.14391527, 12.86998372],
       [ 1.        ,  7.25276242, 26.30128135, ..., 33.47177703,
        33.28867699, 13.81021534],
       ...,
       [ 1.        ,  5.96870756, 17.81273497, ..., 32.93311772,
        37.80502354, 16.56284231],
       [ 1.        ,  8.57866451, 36.79674242, ..., 34.23242826,
        39.94379007, 16.26769248],
       [ 1.        ,  9.63036563, 46.3719711 , ..., 28.72378963,
        38.10118094, 13.96783596]])

In [81]:
# To estimate the 𝜷ˆ(𝑅𝐿𝑆) we should introduce the restrictions in a matrix called L 
# (similar to the hint). Actually, we can verify that some betas doesn't exist for the
# third, fourth, and fifth restrictions, so the last constraint is implicitly introduced on these 

L = np.array( ( [ 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0 ],
                [ 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ], 
                [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0 ], 
                [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1 ], 
                [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1 ] ) )

rr = [ 1, 0, 0, 0, 0 ]

print(L)
print(rr)

[[0 0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 1 1]]
[1, 0, 0, 0, 0]


In [73]:
# We implementing the total database:
data_smpl = pd.DataFrame(np.column_stack([ln_ct, X_big]), columns = ["ln_ct","intercept", "ln_q", "ln2_q", 
                                                                     "ln_qp1", "ln_qp2", "ln_qp3", "ln_p1", 
                                                                     "ln_p2", "ln_p3", "ln2_p1", "ln2_p2",
                                                                     "ln2_p3", "ln_p1p2", "ln_p1p3", "ln_p2p3"])
#data_smpl

In [78]:
# Now we calculate the usual BETA_ols
XTX_inv  = np.linalg.inv(np.dot(np.transpose(X_big), X_big))
BETAS_ols = np.dot(XTX_inv, np.dot(np.transpose(X_big), ln_ct))

#Nevertheless, we need to calculate the RLS estimator expressed as β_RLS = β_OLS + "Restriction Adjustment"
RA_1 = np.dot(XTX_inv, np.transpose(L))
RA_2 = np.linalg.inv(np.linalg.multi_dot([L, XTX_inv, np.transpose(L)]))
RA_3 = np.dot(L, BETAS_ols) - np.array(rr)
RA   = RA_1.dot(RA_2).dot(RA_3)

# With this adjustment component, we can finally calculate the RLS estimator:
BETAS_rls = BETAS_ols - RA
print(pd.DataFrame(BETAS_rls, index = ["intercept", "ln_q", "ln2_q", "ln_qp1", "ln_qp2", "ln_qp3", "ln_p1", 
                                "ln_p2", "ln_p3", "ln2_p1", "ln2_p2", "ln2_p3", "ln_p1p2", "ln_p1p3", "ln_p2p3"]))


                  0
intercept -7.111200
ln_q       0.461368
ln2_q      0.059955
ln_qp1    -0.004354
ln_qp2     0.036778
ln_qp3    -0.032424
ln_p1      0.215566
ln_p2      0.402923
ln_p3      0.381511
ln2_p1    -0.004356
ln2_p2     0.002578
ln2_p3    -0.007651
ln_p1p2   -0.002936
ln_p1p3    0.007292
ln_p2p3    0.000358


In [80]:
# 2. Get the covariance matrix 𝕍ar(𝜷ˆ(𝑅𝐿𝑆))

# To calculate the covariance matrix we create the estimation residuals, 
# then we find the covvar matrix called "VarCov_rls":
ln_ct_fit = np.dot(X_big, BETAS_rls)
e_resid = np.array(ln_ct) - ln_ct_fit

sigma2_rls = np.sum(e_resid**2) / (len(data_smpl.index) - (len(BETAS_rls) - len(rr)))

D_mat = np.identity(len(BETAS_rls)) - RA_1.dot(RA_2).dot(L)
VarCov_rls = sigma2_rls * D_mat.dot(XTX_inv)

print(pd.DataFrame(VarCov_rls, 
                   index = ["intercept", "ln_q", "ln2_q", "ln_qp1", "ln_qp2", "ln_qp3", "ln_p1", 
                                "ln_p2", "ln_p3", "ln2_p1", "ln2_p2", "ln2_p3", "ln_p1p2", "ln_p1p3", "ln_p2p3"], 
                   columns = ["intercept", "ln_q", "ln2_q", "ln_qp1", "ln_qp2", "ln_qp3", "ln_p1", 
                                "ln_p2", "ln_p3", "ln2_p1", "ln2_p2", "ln2_p3", "ln_p1p2", "ln_p1p3", "ln_p2p3"]))

           intercept      ln_q     ln2_q    ln_qp1    ln_qp2    ln_qp3  \
intercept   8.485895 -0.096160  0.000206  0.015677 -0.022104  0.006427   
ln_q       -0.096160  0.016015 -0.000070 -0.002912  0.002270  0.000642   
ln2_q       0.000206 -0.000070  0.000020 -0.000016 -0.000002  0.000019   
ln_qp1      0.015677 -0.002912 -0.000016  0.000585 -0.000363 -0.000222   
ln_qp2     -0.022104  0.002270 -0.000002 -0.000363  0.000654 -0.000291   
ln_qp3      0.006427  0.000642  0.000019 -0.000222 -0.000291  0.000513   
ln_p1      -3.050502  0.012193 -0.000038 -0.001377  0.005099 -0.003722   
ln_p2       1.613544 -0.014739  0.000150  0.001701 -0.006121  0.004419   
ln_p3       1.436958  0.002546 -0.000112 -0.000324  0.001022 -0.000697   
ln2_p1      0.198259  0.000797  0.000012 -0.000240 -0.000166  0.000406   
ln2_p2     -0.045968 -0.001459  0.000031  0.000281  0.000029 -0.000310   
ln2_p3     -0.411072 -0.000658 -0.000048  0.000287  0.000230 -0.000517   
ln_p1p2    -0.281682  0.000002 -0.0000

## 1.4 Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

### Pandas

1. Ejecute el código a continuación, descomente la segunda línea para instalar la biblioteca savReaderWriter. El dict_varlabels tiene las etiquetas de las columnas de rec1.

2. Compruebe si CASEID identifica cada observación de forma única. Sugerencia: utilice el método is_unique.

3. Haga que la columna CASEID sea el índice de su conjunto de datos. Sugerencia: use set_index.

4. Mantenga a las mujeres que tengan entre 15 y 30 años y vivan en áreas urbanas. Sugerencia: use la consulta.

5. Genera una nueva columna con el mes de nacimiento. Solo usa las tres primeras letras. Usa los nombres en inglés de los meses.

In [46]:
# 1. Instalación preliminar

import pandas as pd
import numpy  as np
!pip install pyreadstat
import savReaderWriter as sav
rec1 = pd.read_spss( fr"C:/Users/USER/Documents/GitHub/Diplomado_PUCP/_data/endes/2019/REC0111.sav" )

with sav.SavHeaderReader( fr"C:/Users/USER/Documents/GitHub/Diplomado_PUCP/_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]


In [41]:
dict_varlabels

{'ID1': 'Año',
 'HHID': 'Identificación Cuestionario del Hogar',
 'CASEID': 'Identificación Cuestionario Individual',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V013': 'Edad actual por grupos de 5 años',
 'V014': 'Integridad de la información para la fecha de nacimiento ',
 'V015': 'Resultado entrevista individual',
 'V017': 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'V018': 'Columna del mes de la entrevista',
 'V019': 'Duración del calendario',
 'V019A': 'Número de columnas de calendario',
 'V020': 'Muestra alguna vez casada',
 'V021': 'Unidad de muestreo primar

In [53]:
pd.DataFrame(rec1)

ID1             HHID              CASEID    V001  V002  V003  \
0      2019.0        000100201        000100201  2     1.0   2.0   2.0   
1      2019.0        000100201        000100201  3     1.0   2.0   3.0   
2      2019.0        000102801        000102801  2     1.0  28.0   2.0   
3      2019.0        000102801        000102801  6     1.0  28.0   6.0   
4      2019.0        000104801        000104801  2     1.0  48.0   2.0   
...       ...              ...                 ...     ...   ...   ...   
38330  2019.0        325406201        325406201  2  3254.0  62.0   2.0   
38331  2019.0        325406301        325406301  2  3254.0  63.0   2.0   
38332  2019.0        325407001        325407001  2  3254.0  70.0   2.0   
38333  2019.0        325407201        325407201  2  3254.0  72.0   2.0   
38334  2019.0        325407401        325407401  2  3254.0  74.0   2.0   

         V004    V007    V008  V009  ...  QD333_4  QD333_5  QD333_6  UBIGEO  \
0         1.0  2019.0  1434.0   4.0  ...       No       No       No  010101   
1         1.0  2019.0  1434.0   1.0  ...       No       No       No  010101   
2         1.0  2019.0  1434.0   6.0  ...       No       No       No  010101   
3         1.0  2019.0  1434.0   3.0  ...       No       No       No  010101   
4         1.0  2019.0  1434.0   5.0  ...       No       No       No  010101   
...       ...     ...     ...   ...  ...      ...      ...      ...     ...   
38330  3254.0  2019.0  1440.0  12.0  ...       No       No       No  250401   
38331  3254.0  2019.0  1440.0   6.0  ...       No       No       No  250401   
38332  3254.0  2019.0  1440.0   7.0  ...       No       No       No  250401   
38333  3254.0  2019.0  1440.0  12.0  ...       No       No       No  250401   
38334  3254.0  2019.0  1440.0  10.0  ...       No       No       No  250401   

        V022      V005          V190      V191  \
0        3.0  154803.0          Rico  1.234450   
1        3.0  154803.0          Rico  1.234450   
2        3.0  154803.0          Rico  1.295611   
3        3.0  154803.0          Rico  1.295611   
4        3.0  154803.0        Pobrer -0.256431   
...      ...       ...           ...       ...   
38330  249.0  244995.0  El más pobre -1.750187   
38331  249.0  244995.0  El más pobre -1.676861   
38332  249.0  459792.0  El más pobre -1.585333   
38333  249.0  459792.0  El más pobre -1.650159   
38334  249.0  244995.0  El más pobre -1.644720   

                                        mujeres12a49  NCONGLOME  
0                    Mujeres de 15 a 49 años de edad     7065.0  
1      Mujeres de 12 a 14 de edad, nunca embarazadas     7065.0  
2                    Mujeres de 15 a 49 años de edad     7065.0  
3                    Mujeres de 15 a 49 años de edad     7065.0  
4                    Mujeres de 15 a 49 años de edad     7065.0  
...                                              ...        ...  
38330                Mujeres de 15 a 49 años de edad    15783.0  
38331                Mujeres de 15 a 49 años de edad    15783.0  
38332                Mujeres de 15 a 49 años de edad    15783.0  
38333                Mujeres de 15 a 49 años de edad    15783.0  
38334                Mujeres de 15 a 49 años de edad    15783.0  

[38335 rows x 105 columns]

In [56]:
is_unique(CASEID)

NameError: name 'is_unique' is not defined

In [ ]:
#1. Check if CASEID identifies each observation uniquely. Hint: Use is_unique method.

In [ ]:
#2. Make the CASEID column the index of your data set. Hint: Use set_index.

In [ ]:
#3. Keep women who are 15-30 years old and live in Urban areas. Hint: Use query.

In [ ]:
#4. Generate a new column with the month of born. Just use the first three letters. 
# Use the English names of the months.