# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Dictionaries


1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>
2. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>
3. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>
4. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries](https://stackoverflow.com/questions/25836376/how-to-get-the-inner-indexes-of-a-nested-dictionary-in-python).** <br><br>

In [92]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

5. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists. **Hint: Use `zip` function adn [this link](https://stackoverflow.com/questions/1024847/how-can-i-add-new-keys-to-a-dictionary).** <br><br>

In [93]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

In [94]:
hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

In [95]:
#From lists to dictionary. Assign keys and values
keys = week1 
values = values2 

In [96]:
#check that they are the same length
len(keys)

2

In [97]:
len(values)

2

In [98]:
# Return a dictionary
march = dict( zip( keys , values ) )
march

{'monday': [2, 3, 4], 'sunday': 8}

In [99]:
#Add march key to the hr_sleep dictionary
hr_sleep["March"] = march
hr_sleep

{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]},
 'february': {'saturday': 5, 'sunday': 10, 'monday': 8},
 'March': {'monday': [2, 3, 4], 'sunday': 8}}

## 1.2 Numpy

In [100]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>

In [101]:
#We see that the array np1 is composed of values from 200 to 749 incremented by 1
print(np1)

[200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217
 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235
 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253
 254 255 256 257 258 259 260 261 262 263 264 265 266 267 268 269 270 271
 272 273 274 275 276 277 278 279 280 281 282 283 284 285 286 287 288 289
 290 291 292 293 294 295 296 297 298 299 300 301 302 303 304 305 306 307
 308 309 310 311 312 313 314 315 316 317 318 319 320 321 322 323 324 325
 326 327 328 329 330 331 332 333 334 335 336 337 338 339 340 341 342 343
 344 345 346 347 348 349 350 351 352 353 354 355 356 357 358 359 360 361
 362 363 364 365 366 367 368 369 370 371 372 373 374 375 376 377 378 379
 380 381 382 383 384 385 386 387 388 389 390 391 392 393 394 395 396 397
 398 399 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415
 416 417 418 419 420 421 422 423 424 425 426 427 428 429 430 431 432 433
 434 435 436 437 438 439 440 441 442 443 444 445 44

In [102]:
#We filter even numbers: numbers that have a remainder of 0 when divided by 2. 
np1 [np1%2 == 0] = 100

In [103]:
#We print the array again and see that all even number have been replaced with 100.
print(np1)

[100 201 100 203 100 205 100 207 100 209 100 211 100 213 100 215 100 217
 100 219 100 221 100 223 100 225 100 227 100 229 100 231 100 233 100 235
 100 237 100 239 100 241 100 243 100 245 100 247 100 249 100 251 100 253
 100 255 100 257 100 259 100 261 100 263 100 265 100 267 100 269 100 271
 100 273 100 275 100 277 100 279 100 281 100 283 100 285 100 287 100 289
 100 291 100 293 100 295 100 297 100 299 100 301 100 303 100 305 100 307
 100 309 100 311 100 313 100 315 100 317 100 319 100 321 100 323 100 325
 100 327 100 329 100 331 100 333 100 335 100 337 100 339 100 341 100 343
 100 345 100 347 100 349 100 351 100 353 100 355 100 357 100 359 100 361
 100 363 100 365 100 367 100 369 100 371 100 373 100 375 100 377 100 379
 100 381 100 383 100 385 100 387 100 389 100 391 100 393 100 395 100 397
 100 399 100 401 100 403 100 405 100 407 100 409 100 411 100 413 100 415
 100 417 100 419 100 421 100 423 100 425 100 427 100 429 100 431 100 433
 100 435 100 437 100 439 100 441 100 443 100 445 10

2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>

In [104]:
# Create a 1D NumPy array with values from 0 to 8 incremented by 1:
array = np.arange( 0, 9, 1 ) 
print(array)

[0 1 2 3 4 5 6 7 8]


In [105]:
#Convert the 1-D array with 9 elements into a 3x3 matrix using the n.p reshape method
matrix = array.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>

In [106]:
# 1D array Z
Z = np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] )
print(Z)

[ 1  2  3  4  5  6  7  8  9 10]


In [107]:
# Create each individual vector using np.arrange
a = np.arange ( 1, 5, 1 )
print(a)
b = np.arange( 2, 6, 1 )
print(b) 
c = np.arange( 3, 7, 1 )
print(c)
d = np.arange( 4, 8, 1 )
print(d)
e = np.arange( 5, 9, 1 )
print(e)
f = np.arange( 6, 10, 1 )
print(f)
g = np.arange( 7, 11, 1 )
print(g)

[1 2 3 4]
[2 3 4 5]
[3 4 5 6]
[4 5 6 7]
[5 6 7 8]
[6 7 8 9]
[ 7  8  9 10]


In [108]:
#Generating an array R using np.concatenate to join the individual vectors into one.
R = np.concatenate((a, b, c, d, e, f, g), axis=None) 
print(R)

[ 1  2  3  4  2  3  4  5  3  4  5  6  4  5  6  7  5  6  7  8  6  7  8  9
  7  8  9 10]


4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>

In [109]:
np.random.random( (3,3,3) )  #It's a funtion that returns an array with 3 sub arrays of random floats of shape size (3x3). 
#The first sub argument is to create the number of subarrays, the second one to rows and finally, the third one is to the columns. 

array([[[0.24814784, 0.4394413 , 0.46425967],
        [0.66422865, 0.20511917, 0.66136323],
        [0.75677067, 0.3314973 , 0.65508102]],

       [[0.78037258, 0.12913994, 0.25095822],
        [0.5479428 , 0.56791197, 0.96897832],
        [0.58595676, 0.35508587, 0.96160249]],

       [[0.94507955, 0.98522773, 0.3324286 ],
        [0.69883843, 0.9943248 , 0.91307325],
        [0.92912548, 0.24798511, 0.93928786]]])

5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>


In principle, np.nan are not numbers, but are undefined values that are substitutes for the empty spaces of an array, in this case, since we are working with numpys. So, it does not make much mathematical sense to compare two undefined values. 

6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [110]:
mean =  round( np.mean(np2) ) #we use the function np.mean to calculate the mean of the array. Then we round the number. 
sd = round( np.sqrt ( np.var (np2) ) ) #we use the function np.var to calculate the var of the array. Then then we calculate the square root of that number and thus obtain the sd.


In [111]:
 print( f'The mean is {mean} and its standard deviation is {sd}') #we print 

The mean is 50 and its standard deviation is 4


## Restricted Least Squares

Given the following equation:


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$


1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>
2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

In [112]:
import pandas as pd
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

In [113]:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [ ]:
# read REC0111 data
#!pip install savReaderWriter
import savReaderWriter as sav
rec1 = pd.read_spss( fr"../../_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"../../_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [ ]:
dict_varlabels