# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Dictionaries
1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>
2. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>
3. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>
4. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries](https://stackoverflow.com/questions/25836376/how-to-get-the-inner-indexes-of-a-nested-dictionary-in-python).** <br><br>
5. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists. **Hint: Use `zip` function adn [this link](https://stackoverflow.com/questions/1024847/how-can-i-add-new-keys-to-a-dictionary).** <br><br>

In [42]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

In [2]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

## Solution 1.1

In [2]:
import numpy as np

In [36]:
#1
#1 Solution 
union = {"even_numbers" : np.arange(0,2000,2).tolist(),
           "odd_numbers" : np.arange(9001,19000,2).tolist()}
# Result
union

#2 Solution
# create the array of the first and second key 
v1 = np.arange(0,20001)
v2 = np.arange(9000, 19001)

# get the even  and odd numbers 
list_even =list(map(lambda x: x % 2==0, v1))
list_even_1 = np.where(list(list_even))[0]
list_even_1

list_odd =list(map(lambda x: x % 2!=0, v2))
list_odd_1 = np.where(list(list_odd))[0]
list_odd_1

# create key even_numbers and odd_numbers
keys = ['even_numbers','odd_numbers']
values = [list_even_1, list_odd_1]

# Use of dict to join list of keys and values
result_dict = dict( zip( keys , values ) )
result_dict

{'even_numbers': array([    0,     2,     4, ..., 19996, 19998, 20000], dtype=int64),
 'odd_numbers': array([   1,    3,    5, ..., 9995, 9997, 9999], dtype=int64)}

In [35]:
result_dict.keys()

dict_keys(['even_numbers', 'odd_numbers'])

In [ ]:
#Referencia
#- https://stackoverflow.com/questions/49852022/sorting-grouping-odd-and-even-numbers-in-odd-and-even-segregated-list

In [44]:
# 2
# using the get method for dictionaries 
print(car.get("brand"))

Ford


In [48]:
# 3
print(car.values())

dict_values(['Ford', 'Mustang', 1964])


In [49]:
# 4
# getting the max value since the dictionary is indexing
print(max(hr_sleep["january"]["friday"]))

2


In [52]:
# 5
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]
# Zip to join week1 and values2 
# * to update the dictonary with the new key "march"
hr_sleep["march"] = dict([*zip(week1,values2)])
hr_sleep


{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]},
 'february': {'saturday': 5, 'sunday': 10, 'monday': 8},
 'march': {'monday': [2, 3, 4], 'sunday': 8}}

## 1.2 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>
4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>
5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>
6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [2]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

## Solution 1.2

In [81]:
# 1
# Using lambda and map to recreate the list , and find all the even numbers , the conditional sentence is to filter 
# Finally we get 100 in even numbers and x to the rest
v1 = list(map(lambda x: 100 if x%2==0  else x, np.arange( 200, 750)))
v1

[100,
 201,
 100,
 203,
 100,
 205,
 100,
 207,
 100,
 209,
 100,
 211,
 100,
 213,
 100,
 215,
 100,
 217,
 100,
 219,
 100,
 221,
 100,
 223,
 100,
 225,
 100,
 227,
 100,
 229,
 100,
 231,
 100,
 233,
 100,
 235,
 100,
 237,
 100,
 239,
 100,
 241,
 100,
 243,
 100,
 245,
 100,
 247,
 100,
 249,
 100,
 251,
 100,
 253,
 100,
 255,
 100,
 257,
 100,
 259,
 100,
 261,
 100,
 263,
 100,
 265,
 100,
 267,
 100,
 269,
 100,
 271,
 100,
 273,
 100,
 275,
 100,
 277,
 100,
 279,
 100,
 281,
 100,
 283,
 100,
 285,
 100,
 287,
 100,
 289,
 100,
 291,
 100,
 293,
 100,
 295,
 100,
 297,
 100,
 299,
 100,
 301,
 100,
 303,
 100,
 305,
 100,
 307,
 100,
 309,
 100,
 311,
 100,
 313,
 100,
 315,
 100,
 317,
 100,
 319,
 100,
 321,
 100,
 323,
 100,
 325,
 100,
 327,
 100,
 329,
 100,
 331,
 100,
 333,
 100,
 335,
 100,
 337,
 100,
 339,
 100,
 341,
 100,
 343,
 100,
 345,
 100,
 347,
 100,
 349,
 100,
 351,
 100,
 353,
 100,
 355,
 100,
 357,
 100,
 359,
 100,
 361,
 100,
 363,
 100,
 365,
 100

In [49]:
# 2
#Create a 1D numpy array with values from 0 to 8 increasing from 1 to 1.
matrix_1 = np.arange( 0, 9, 1)
#Use the method reshape to changing the shape of "matrix_1" array.
matrix_2 = matrix_1.reshape(3,3)
print(matrix_2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
# 3
# Create a numpy array
Z = np.arange( 1, 11)

#Create a sub arrays from Z array. With select the positions to elements to found sub arrays.

z1 = np.array([Z[0:4]])
z2 = np.array([Z[1:5]])
z2 = np.array([Z[1:5]])
z3 = np.array([Z[2:6]])
z4 = np.array([Z[3:7]])
z5 = np.array([Z[4:8]])
z6 = np.array([Z[5:9]])
z7 = np.array([Z[6:]])

print(z1) # Verify elements of array
print(z7)

#Create a new array with sub arrays, use the methos np.concatenate to join arrays of the same shape along a specified axis.

R = np.concatenate ( (z1, z2, z3, z4, z5, z6, z7), axis = 0 ) 

print(R)


[[1 2 3 4]]
[[ 7  8  9 10]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]]


In [7]:
# 4
# Create an array that have 3 dimensions. "np.random.random" filled with random floats and we specified the size.
np3 = np.random.random((3,3,3))
print(np3)

[[[0.21819885 0.42640533 0.09066636]
  [0.47542962 0.21592765 0.77122916]
  [0.26600202 0.09165906 0.64936824]]

 [[0.01038459 0.6575549  0.00879798]
  [0.78369155 0.90717787 0.75879041]
  [0.68770543 0.439809   0.68812668]]

 [[0.10785847 0.62991546 0.25429471]
  [0.02908844 0.23545463 0.32657374]
  [0.75555264 0.23381403 0.93578635]]]


In [9]:
#5 
print(np.nan == np.nan)
# This expression is false beacuse  the content of the variable is diferent as the content of another variable. The np.nan
# is the representation of Not a Number. This type as a float.
#print(np.nan)

# Any ordered comparison of a number to a not-a-number value is false. 
# A counter-intuitive implication is that not-a-number values are not equal to themselves. 
# For example, if x = float('NaN'), 3 < x, x < 3 and x == x are all false, while x != x is true. 

False


In [14]:
# 6
#Create an array of specified shape and fills it with random values from a normal (Gaussian) distribution
np2 = np.random.normal( 50 , 4, 300)
# Mean. Get mean of all array values
mean_np2 = np.mean(np2)
print(mean_np2)

#f-string provides a better syntax for adding variables to strings
print(f'The mean of np2 array is {mean_np2}')
# Standar Deviation. 
#Get variance of all array values.
var_np2 = np.var(np2)
print(var_np2)

#Get square root of variance, by the theory we know
sd_np2 = np.sqrt(var_np2)
print(sd_np2)

#f-string provides a better syntax for adding variables to strings
print(f'The standard deviation of np2 array is {sd_np2}')

50.038188766935974
The mean of np2 array is 50.038188766935974
17.02060257696472
4.125603298544919
The standard deviation of np2 array is 4.125603298544919


## Restricted Least Squares

Given the following equation:


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$


1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>
2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

In [82]:
import pandas as pd
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

In [83]:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

## Solution 1.3

In [121]:
# 1
## First , getting the value of Y 
# From the ecuation
Y = np.log(ct)
Y

array([-1.54646311,  1.11274528,  2.24133715, -0.27364768,  0.81478943,
        0.29431006, -0.48467067, -0.71600647,  0.13749851,  2.0214416 ,
        0.71939955, -0.45208513,  1.14752943,  2.33346341,  1.76623651,
        1.50518789,  1.72224861,  1.31520107,  1.79284222,  2.54811616,
        1.89030683,  2.26622189,  2.16162043,  2.15607846,  2.41964787,
        1.89041254,  2.39484517,  2.61205312,  2.00680364,  2.28077906,
        3.03817376,  2.98108553,  2.64213117,  2.32142647,  2.78355339,
        3.74363749,  3.11623162,  3.49703772,  2.93896614,  2.58534758,
        3.07016234,  3.57038585,  3.39454531,  3.43002129,  3.19279875,
        2.86106881,  2.99075993,  3.35989263,  3.29891361,  3.11093866,
        3.40806375,  3.40677513,  3.48382137,  3.85833527,  3.19007709,
        3.44336887,  3.46537334,  3.73532401,  4.06243069,  3.70199556,
        3.61271629,  3.22559719,  3.81071427,  4.01053533,  3.71794784,
        4.38650783,  4.22654173,  4.57868144,  3.96581777,  3.65

In [109]:
# Second , from the system ecuation , we get  L 
# agregar b12-b21=0
# agregar b23-b32=0
# agregar b13-b31=0
L = np.array(( np.concatenate((np.zeros(5),[1,1,1,0,0,0,0,0,0])),
               np.concatenate((np.zeros(2),[1,1,1,0,0,0,0,0,0,0,0,0])),
               np.concatenate((np.zeros(8),[1,0,0,1,1,0])),
               np.concatenate((np.zeros(9),[1,0,0,0,1])),
               np.concatenate((np.zeros(10),[1,0,0,0])),
               np.concatenate((np.zeros(11),[1,0,0])),
               np.concatenate((np.zeros(13),[1])),
               np.concatenate((np.zeros(12),[1,0])),
             ))
L

array([[0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

In [112]:
# For the ecuation
X = np.column_stack([np.log(q),np.log(np.power(q,2)/2),np.log(q)*np.log(p1),np.log(q)*np.log(p2),np.log(q)*np.log(p3),
                     np.log(p1),np.log(p2),np.log(p3),np.power(np.log(p1),2)/2,np.power(np.log(p2),2)/2,np.power(np.log(p3),2)/2,
                     np.log(p1)*np.log(p2)/2,np.log(p1)*np.log(p3)/2,np.log(p2)*np.log(p3)/2])
X

array([[ 2.07944154,  3.4657359 , 18.37153796, ..., 12.76798924,
        18.43628708,  6.03154217],
       [ 6.76734313, 12.84153907, 61.12780486, ..., 13.7646109 ,
        19.07195764,  6.43499186],
       [ 7.25276242, 13.81237766, 65.14646856, ..., 16.73588852,
        16.6443385 ,  6.90510767],
       ...,
       [ 5.96870756, 11.24426794, 51.74924846, ..., 16.46655886,
        18.90251177,  8.28142116],
       [ 8.57866451, 16.46418185, 78.65026601, ..., 17.11621413,
        19.97189503,  8.13384624],
       [ 9.63036563, 18.56758408, 85.2448793 , ..., 14.36189482,
        19.05059047,  6.98391798]])

In [117]:
#Results
rr = np.hstack(([1],np.zeros(7)))
rr

array([1., 0., 0., 0., 0., 0., 0., 0.])

In [120]:
# geting the invert matriz of x
XX_inv = np.linalg.inv(np.matmul(np.transpose(X),X))
# matmul to multiplicate matrix
XY = np.matmul(np.transpose(X),Y)
b_ols = np.matmul(XX_inv,XY)
XX_invL = np.matmul(XX_inv,np.transpose(L))
## getting the invert of the multiplication above
LXXL_inv = np.linalg.inv(np.matmul(np.matmul(L,XX_inv),np.transpose(L)))
Lb_rr = np.matmul(L,b_ols)-rr
# Finally calculating beta_rls
beta_rls = b_ols - np.matmul(np.matmul(XX_invL,LXXL_inv),Lb_rr)
print(beta_rls)

[-1.77150446e+01  9.18366352e+00  4.64319410e-02  3.69444522e-02
 -8.33763932e-02 -2.91634897e-01  4.37698803e-01  8.53936094e-01
 -3.81250587e-13  1.31283873e-14  6.86395385e-14  5.83977311e-14
 -4.82058837e-13  1.66533454e-16]


In [124]:
# 2
# Getting the residuals of the ecuation 
residuals = Y - X@beta_rls
# Signma 2 for the varianza of beta_rls ( covarianza matrix)
sigma2 = np.transpose(residuals)@residuals / (len(Y) - (np.shape(X)[1] + 1 - len(r)))
var_b = sigma2*XX_inv - sigma2*XX_invL@LXXL_inv@L@XX_inv
var_b

array([[ 1.78227184e+01, -9.29109704e+00,  1.42490908e-01,
        -1.11715016e-01, -3.07758921e-02, -1.21078807e+00,
         9.38514905e-01,  2.72273159e-01,  9.97886218e-11,
        -1.58406621e-12,  6.27053964e-11,  1.35891298e-11,
         1.05330855e-10,  5.33817435e-12],
       [-9.29109705e+00,  4.84403988e+00, -7.44793245e-02,
         5.83798333e-02,  1.60994912e-02,  6.31230514e-01,
        -4.89435427e-01, -1.41795085e-01, -8.93578544e-11,
         4.89186469e-12, -4.04227762e-11, -1.55360169e-11,
        -1.04122932e-10,  1.37622136e-11],
       [ 1.42490908e-01, -7.44793245e-02,  1.23772979e-03,
        -8.27456828e-04, -4.10272967e-04, -9.88572918e-03,
         6.66288090e-03,  3.22284828e-03,  3.02882719e-15,
        -2.65846373e-16, -5.82606879e-15,  5.72458747e-15,
        -7.26762400e-15,  8.95550994e-16],
       [-1.11715016e-01,  5.83798333e-02, -8.27456828e-04,
         1.40754312e-03, -5.80086288e-04,  6.69230375e-03,
        -1.11025850e-02,  4.41028127e-03,  9.

# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [ ]:
###IMPORTANDO PAQUETE Y DATA
# read REC0111 data
#!pip install savReaderWriter
import savReaderWriter as sav
rec1 = pd.read_spss( fr"../../_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"../../_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [ ]:
dict_varlabels

## Solution 1.4

In [31]:
import pandas as pd
import savReaderWriter as sav
rec1 = pd.read_spss( "C:/Users\Rodrigo!/Documents/Tarea_Python/REC0111.sav" )
# Get labels from sav file
with sav.SavHeaderReader( "C:/Users\Rodrigo!/Documents/Tarea_Python/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [32]:
dict_varlabels

{'ID1': 'Año',
 'HHID': 'Identificación Cuestionario del Hogar',
 'CASEID': 'Identificación Cuestionario Individual',
 'V001': 'Conglomerado',
 'V002': 'Número de vivienda',
 'V003': 'Número de línea de entrevistada',
 'V004': 'Unidad de área final',
 'V007': 'Año de la entrevista',
 'V008': 'Fecha de la entrevista, Codificación centenaria de meses (CMC)',
 'V009': 'Mes de nacimiento de la entrevistada',
 'V010': 'Año de nacimiento de la entrevistada',
 'V011': 'Fecha de nacimiento, Codificación centenaria de meses (CMC)',
 'V012': 'Edad actual - entrevistada',
 'V013': 'Edad actual por grupos de 5 años',
 'V014': 'Integridad de la información para la fecha de nacimiento ',
 'V015': 'Resultado entrevista individual',
 'V017': 'Inicio del calendario, Codificación centenaria de mesesl CMC',
 'V018': 'Columna del mes de la entrevista',
 'V019': 'Duración del calendario',
 'V019A': 'Número de columnas de calendario',
 'V020': 'Muestra alguna vez casada',
 'V021': 'Unidad de muestreo primar

In [33]:
###1.Check if CASEID identifies each observation uniquely. Hint: Use is_unique method.
rec1['CASEID'].is_unique

True

In [35]:
###2.Make the CASEID column the index of your data set. Hint: Use set_index.
rec2=rec1.set_index('CASEID')
rec2

ID1             HHID    V001  V002  V003    V004  \
CASEID                                                                    
      000100201  2  2019.0        000100201     1.0   2.0   2.0     1.0   
      000100201  3  2019.0        000100201     1.0   2.0   3.0     1.0   
      000102801  2  2019.0        000102801     1.0  28.0   2.0     1.0   
      000102801  6  2019.0        000102801     1.0  28.0   6.0     1.0   
      000104801  2  2019.0        000104801     1.0  48.0   2.0     1.0   
...                    ...              ...     ...   ...   ...     ...   
      325406201  2  2019.0        325406201  3254.0  62.0   2.0  3254.0   
      325406301  2  2019.0        325406301  3254.0  63.0   2.0  3254.0   
      325407001  2  2019.0        325407001  3254.0  70.0   2.0  3254.0   
      325407201  2  2019.0        325407201  3254.0  72.0   2.0  3254.0   
      325407401  2  2019.0        325407401  3254.0  74.0   2.0  3254.0   

                      V007    V008  V009    V010  ...  QD333_4  QD333_5  \
CASEID                                            ...                     
      000100201  2  2019.0  1434.0   4.0  1986.0  ...       No       No   
      000100201  3  2019.0  1434.0   1.0  2007.0  ...       No       No   
      000102801  2  2019.0  1434.0   6.0  1983.0  ...       No       No   
      000102801  6  2019.0  1434.0   3.0  1970.0  ...       No       No   
      000104801  2  2019.0  1434.0   5.0  1991.0  ...       No       No   
...                    ...     ...   ...     ...  ...      ...      ...   
      325406201  2  2019.0  1440.0  12.0  1971.0  ...       No       No   
      325406301  2  2019.0  1440.0   6.0  1988.0  ...       No       No   
      325407001  2  2019.0  1440.0   7.0  1973.0  ...       No       No   
      325407201  2  2019.0  1440.0  12.0  1994.0  ...       No       No   
      325407401  2  2019.0  1440.0  10.0  1996.0  ...       No       No   

                   QD333_6  UBIGEO   V022      V005          V190      V191  \
CASEID                                                                        
      000100201  2      No  010101    3.0  154803.0          Rico  1.234450   
      000100201  3      No  010101    3.0  154803.0          Rico  1.234450   
      000102801  2      No  010101    3.0  154803.0          Rico  1.295611   
      000102801  6      No  010101    3.0  154803.0          Rico  1.295611   
      000104801  2      No  010101    3.0  154803.0        Pobrer -0.256431   
...                    ...     ...    ...       ...           ...       ...   
      325406201  2      No  250401  249.0  244995.0  El más pobre -1.750187   
      325406301  2      No  250401  249.0  244995.0  El más pobre -1.676861   
      325407001  2      No  250401  249.0  459792.0  El más pobre -1.585333   
      325407201  2      No  250401  249.0  459792.0  El más pobre -1.650159   
      325407401  2      No  250401  249.0  244995.0  El más pobre -1.644720   

                                                     mujeres12a49 NCONGLOME  
CASEID                                                                       
      000100201  2                Mujeres de 15 a 49 años de edad    7065.0  
      000100201  3  Mujeres de 12 a 14 de edad, nunca embarazadas    7065.0  
      000102801  2                Mujeres de 15 a 49 años de edad    7065.0  
      000102801  6                Mujeres de 15 a 49 años de edad    7065.0  
      000104801  2                Mujeres de 15 a 49 años de edad    7065.0  
...                                                           ...       ...  
      325406201  2                Mujeres de 15 a 49 años de edad   15783.0  
      325406301  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407001  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407201  2                Mujeres de 15 a 49 años de edad   15783.0  
      325407401  2                Mujeres de 15 a 49 años de edad   15783.0  

[38335 rows x 104 columns]

In [36]:
###3.Keep women who are 15-30 years old and live in Urban areas. Hint: Use query.
rec2.query('V012>15 & V012<30 & V025=="Urbano"')

ID1             HHID    V001   V002  V003    V004  \
CASEID                                                                     
      000104801  2  2019.0        000104801     1.0   48.0   2.0     1.0   
      000116701  1  2019.0        000116701     1.0  167.0   1.0     1.0   
      000119101  1  2019.0        000119101     1.0  191.0   1.0     1.0   
      000203001  2  2019.0        000203001     2.0   30.0   2.0     2.0   
      000204001  3  2019.0        000204001     2.0   40.0   3.0     2.0   
...                    ...              ...     ...    ...   ...     ...   
      324202401  2  2019.0        324202401  3242.0   24.0   2.0  3242.0   
      324202501  3  2019.0        324202501  3242.0   25.0   3.0  3242.0   
      324203901  1  2019.0        324203901  3242.0   39.0   1.0  3242.0   
      324204501  2  2019.0        324204501  3242.0   45.0   2.0  3242.0   
      324206901  3  2019.0        324206901  3242.0   69.0   3.0  3242.0   

                      V007    V008  V009    V010  ...  QD333_4  QD333_5  \
CASEID                                            ...                     
      000104801  2  2019.0  1434.0   5.0  1991.0  ...       No       No   
      000116701  1  2019.0  1434.0   6.0  2001.0  ...       No       No   
      000119101  1  2019.0  1434.0   9.0  1995.0  ...       No       No   
      000203001  2  2019.0  1432.0   5.0  1990.0  ...       No       No   
      000204001  3  2019.0  1432.0   9.0  1998.0  ...       No       No   
...                    ...     ...   ...     ...  ...      ...      ...   
      324202401  2  2019.0  1436.0   2.0  1990.0  ...       No       No   
      324202501  3  2019.0  1436.0   5.0  1999.0  ...       No       No   
      324203901  1  2019.0  1436.0   8.0  1992.0  ...       No       No   
      324204501  2  2019.0  1436.0   5.0  1993.0  ...       No       No   
      324206901  3  2019.0  1436.0  10.0  2002.0  ...       No       No   

                   QD333_6  UBIGEO   V022      V005          V190      V191  \
CASEID                                                                        
      000104801  2      No  010101    3.0  154803.0        Pobrer -0.256431   
      000116701  1      No  010101    3.0  154803.0      Más rico  1.672440   
      000119101  1      No  010101    3.0  154803.0        Pobrer  0.234148   
      000203001  2      No  010101    2.0   65298.0        Pobrer -0.196449   
      000204001  3      No  010101    2.0   65298.0         Medio  0.560448   
...                    ...     ...    ...       ...           ...       ...   
      324202401  2      No  250302  248.0  203603.0        Pobrer -0.463931   
      324202501  3      No  250302  248.0  567613.0        Pobrer -0.576118   
      324203901  1      No  250302  248.0  567613.0  El más pobre -0.940013   
      324204501  2      No  250302  248.0  203603.0  El más pobre -0.656011   
      324206901  3      No  250302  248.0  567613.0        Pobrer -0.574662   

                                       mujeres12a49 NCONGLOME  
CASEID                                                         
      000104801  2  Mujeres de 15 a 49 años de edad    7065.0  
      000116701  1  Mujeres de 15 a 49 años de edad    7065.0  
      000119101  1  Mujeres de 15 a 49 años de edad    7065.0  
      000203001  2  Mujeres de 15 a 49 años de edad    7068.0  
      000204001  3  Mujeres de 15 a 49 años de edad    7068.0  
...                                             ...       ...  
      324202401  2  Mujeres de 15 a 49 años de edad   45556.0  
      324202501  3  Mujeres de 15 a 49 años de edad   45556.0  
      324203901  1  Mujeres de 15 a 49 años de edad   45556.0  
      324204501  2  Mujeres de 15 a 49 años de edad   45556.0  
      324206901  3  Mujeres de 15 a 49 años de edad   45556.0  

[10606 rows x 104 columns]

In [37]:
###4.Generate a new column with the month of born. Just use the first three letters. Use the English names of the months.
rec1["M_O_B"]= pd.to_datetime(rec1['V009'], format='%m').dt.month_name().str.slice(stop=3)
rec1

ID1             HHID              CASEID    V001  V002  V003  \
0      2019.0        000100201        000100201  2     1.0   2.0   2.0   
1      2019.0        000100201        000100201  3     1.0   2.0   3.0   
2      2019.0        000102801        000102801  2     1.0  28.0   2.0   
3      2019.0        000102801        000102801  6     1.0  28.0   6.0   
4      2019.0        000104801        000104801  2     1.0  48.0   2.0   
...       ...              ...                 ...     ...   ...   ...   
38330  2019.0        325406201        325406201  2  3254.0  62.0   2.0   
38331  2019.0        325406301        325406301  2  3254.0  63.0   2.0   
38332  2019.0        325407001        325407001  2  3254.0  70.0   2.0   
38333  2019.0        325407201        325407201  2  3254.0  72.0   2.0   
38334  2019.0        325407401        325407401  2  3254.0  74.0   2.0   

         V004    V007    V008  V009  ...  QD333_5  QD333_6  UBIGEO   V022  \
0         1.0  2019.0  1434.0   4.0  ...       No       No  010101    3.0   
1         1.0  2019.0  1434.0   1.0  ...       No       No  010101    3.0   
2         1.0  2019.0  1434.0   6.0  ...       No       No  010101    3.0   
3         1.0  2019.0  1434.0   3.0  ...       No       No  010101    3.0   
4         1.0  2019.0  1434.0   5.0  ...       No       No  010101    3.0   
...       ...     ...     ...   ...  ...      ...      ...     ...    ...   
38330  3254.0  2019.0  1440.0  12.0  ...       No       No  250401  249.0   
38331  3254.0  2019.0  1440.0   6.0  ...       No       No  250401  249.0   
38332  3254.0  2019.0  1440.0   7.0  ...       No       No  250401  249.0   
38333  3254.0  2019.0  1440.0  12.0  ...       No       No  250401  249.0   
38334  3254.0  2019.0  1440.0  10.0  ...       No       No  250401  249.0   

           V005          V190      V191  \
0      154803.0          Rico  1.234450   
1      154803.0          Rico  1.234450   
2      154803.0          Rico  1.295611   
3      154803.0          Rico  1.295611   
4      154803.0        Pobrer -0.256431   
...         ...           ...       ...   
38330  244995.0  El más pobre -1.750187   
38331  244995.0  El más pobre -1.676861   
38332  459792.0  El más pobre -1.585333   
38333  459792.0  El más pobre -1.650159   
38334  244995.0  El más pobre -1.644720   

                                        mujeres12a49 NCONGLOME  M_O_B  
0                    Mujeres de 15 a 49 años de edad    7065.0    Apr  
1      Mujeres de 12 a 14 de edad, nunca embarazadas    7065.0    Jan  
2                    Mujeres de 15 a 49 años de edad    7065.0    Jun  
3                    Mujeres de 15 a 49 años de edad    7065.0    Mar  
4                    Mujeres de 15 a 49 años de edad    7065.0    May  
...                                              ...       ...    ...  
38330                Mujeres de 15 a 49 años de edad   15783.0    Dec  
38331                Mujeres de 15 a 49 años de edad   15783.0    Jun  
38332                Mujeres de 15 a 49 años de edad   15783.0    Jul  
38333                Mujeres de 15 a 49 años de edad   15783.0    Dec  
38334                Mujeres de 15 a 49 años de edad   15783.0    Oct  

[38335 rows x 106 columns]