# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Dictionaries
1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>
2. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>
3. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>
4. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries](https://stackoverflow.com/questions/25836376/how-to-get-the-inner-indexes-of-a-nested-dictionary-in-python).** <br><br>
5. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists. **Hint: Use `zip` function adn [this link](https://stackoverflow.com/questions/1024847/how-can-i-add-new-keys-to-a-dictionary).** <br><br>

In [1]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

In [2]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

## 1.2 Numpy
1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>
2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>
3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use `np.arange` and `np.concatenate`** <br><br>

In [4]:
import numpy as np
np1 = np.arange( 200, 750)
np2 = np.random.normal( 50 , 4, 300)

4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>

In [8]:
import numpy as np
#usamos la funcion np.random.random y definimos el orden de la matriz
arr1 = np.random.random((3,3,3))
arr1

array([[[0.89274968, 0.4258702 , 0.42953311],
        [0.50839762, 0.14437517, 0.44549199],
        [0.61455397, 0.45911233, 0.78872795]],

       [[0.05101569, 0.92952369, 0.43271195],
        [0.84500462, 0.77735326, 0.81504528],
        [0.85048333, 0.48581586, 0.95209914]],

       [[0.85049642, 0.39912547, 0.08835908],
        [0.40698599, 0.00399582, 0.35069702],
        [0.1448155 , 0.84346871, 0.06052501]]])

5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>

In [20]:
a=np.nan
b=np.nan
a==b

False

La expresión es falsa puesto que de ser lo contrario generaría problemas de cálculo. Por ejemplo a/b me resultaría igual a 1, lo cual no es cierto.

6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [27]:
import numpy as np
np2 = np.random.normal( 50 , 4, 300)
media = np.mean(np2)
desvest = np.sqrt(np.var(np2))
print(f"La media del array np2  es {media} y su desviación estándar es {desvest}")

La media del array np2  es 49.82295314106145 y su desviación estándar es 3.9840498967628224


## Restricted Least Squares

Given the following equation:


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$


1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>
2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

## Solution RLS - 1

In [5]:
import numpy as np

In [7]:
import pandas as pd
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

In [23]:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

In [24]:
#Estimamos logaritmos del array ct
Y = np.log(ct)
Y 

array([-1.54646311,  1.11274528,  2.24133715, -0.27364768,  0.81478943,
        0.29431006, -0.48467067, -0.71600647,  0.13749851,  2.0214416 ,
        0.71939955, -0.45208513,  1.14752943,  2.33346341,  1.76623651,
        1.50518789,  1.72224861,  1.31520107,  1.79284222,  2.54811616,
        1.89030683,  2.26622189,  2.16162043,  2.15607846,  2.41964787,
        1.89041254,  2.39484517,  2.61205312,  2.00680364,  2.28077906,
        3.03817376,  2.98108553,  2.64213117,  2.32142647,  2.78355339,
        3.74363749,  3.11623162,  3.49703772,  2.93896614,  2.58534758,
        3.07016234,  3.57038585,  3.39454531,  3.43002129,  3.19279875,
        2.86106881,  2.99075993,  3.35989263,  3.29891361,  3.11093866,
        3.40806375,  3.40677513,  3.48382137,  3.85833527,  3.19007709,
        3.44336887,  3.46537334,  3.73532401,  4.06243069,  3.70199556,
        3.61271629,  3.22559719,  3.81071427,  4.01053533,  3.71794784,
        4.38650783,  4.22654173,  4.57868144,  3.96581777,  3.65

In [23]:
# Conformamos la matriz X
X = np.column_stack([np.log(q),np.log(np.power(q,2)/2), np.log(q)*np.log(p1),np.log(q)*np.log(p2),np.log(q)*np.log(p3),
                     np.log(p1),np.log(p2),np.log(p3),np.power(np.log(p1),2)/2,np.power(np.log(p2),2)/2,
                     np.power(np.log(p3),2)/2, np.log(p1)*np.log(p2)/2,np.log(p1)*np.log(p3)/2,np.log(p2)*np.log(p3)/2])
X

array([[ 2.07944154,  3.4657359 , 18.37153796, ..., 12.76798924,
        18.43628708,  6.03154217],
       [ 6.76734313, 12.84153907, 61.12780486, ..., 13.7646109 ,
        19.07195764,  6.43499186],
       [ 7.25276242, 13.81237766, 65.14646856, ..., 16.73588852,
        16.6443385 ,  6.90510767],
       ...,
       [ 5.96870756, 11.24426794, 51.74924846, ..., 16.46655886,
        18.90251177,  8.28142116],
       [ 8.57866451, 16.46418185, 78.65026601, ..., 17.11621413,
        19.97189503,  8.13384624],
       [ 9.63036563, 18.56758408, 85.2448793 , ..., 14.36189482,
        19.05059047,  6.98391798]])

# Pandas

Run the code bellow uncomment the second line to install savReaderWriter library. The `dict_varlabels` has the labels of the columns of rec1.

1. Check if CASEID identifies each observation uniquely. **[Hint: Use is_unique method.](https://pandas.pydata.org/docs/reference/api/pandas.Series.is_unique.html)**
2. Make the CASEID column the index of your data set. **[Hint: Use set_index](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.set_index.html)**. 
3. Keep women who are 15-30 years old and live in Urban areas. **[Hint: Use query](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html)**.
4. Generate a new column with the month of born. Just use the first three letters.  Use the English names of the months. 

In [ ]:
# read REC0111 data
#!pip install savReaderWriter
import savReaderWriter as sav
rec1 = pd.read_spss( fr"../../_data/endes/2019/REC0111.sav" )

# Get labels from sav file
with sav.SavHeaderReader( fr"../../_data/endes/2019/REC0111.sav", ioUtf8=True) as header:
    metadata = header.all()

dict_varlabels = metadata[3]

In [ ]:
dict_varlabels