In [2]:
import pandas as pd 
import numpy as np

## 1 Tuples

In [2]:
tuple1 = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
tuple2 = (10, 20, 30, 40, 50)

In [3]:
tuple1[0]

'apple'

In [4]:
tuple1[-1]

'mango'

In [5]:
tuple1[3] = 'pink grapeftuit'
# It isn't possible to change the item values of a tuple

TypeError: 'tuple' object does not support item assignment

In [6]:
len(tuple1)

7

In [7]:
tuple2 = tuple2[::-1]
tuple2

(50, 40, 30, 20, 10)

In [8]:
list2 = list(tuple2)
tuple3 = tuple([int(i/2) for i in list2])
tuple3

(25, 20, 15, 10, 5)

## 1.2 Lists

In [15]:
f_list = [np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]

In [53]:
def get_index_positions(list_of_elems, element):
    index_pos_list = []
    index_pos = 0
    while True:
        try:
            index_pos = list_of_elems.index(element, index_pos)
            index_pos_list.append(index_pos)
            index_pos += 1
        except ValueError as e:
            break
    return index_pos_list

nans = get_index_positions(f_list, np.nan)

In [64]:
print('The indices {},{},{},{} have np.nan values'.format(*nans))

The indices 0,1,4,7 have np.nan values


In [65]:
p2_list = [2,3,4,5]
p2_list*4

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]

In [66]:
len(f_list)

8

In [72]:
text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring.']
' '.join(text1)

'My teacher assistant is so boring.'

In [73]:
text1.extend(['but is very funny'])

In [82]:
text1
t = ' '.join(text1).replace('teacher assistant', 'TA').replace('boring.', 'boring,')
t

'My TA is so boring, but is very funny'

In [91]:
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1 ] 
print('The max value of values1 is {} and is located in the {} index.'.format(max(values1), values1.index(max(values1))))
print('The min value of values1 is {} and is located in the {} index.'.format(min(values1), values1.index(min(values1))))

The max value of values1 is 86 and is located in the 0 index.
The min value of values1 is 0 and is located in the 7 index.


## 1.3. Dictionaries

### 1.3.1. Create dictionary from two lists: even numbers and odd numbers

In [9]:
#First create a list for even numbers and another for odd numbers
even_numbers=[*range(0,2001,2)]
odd_numbers=[*range(9001,19000,2)]

#convert the two lists into a dictionary
dict_even_odd = dict( zip( even_numbers , odd_numbers ) )
print( dict_even_odd )

{0: 9001, 2: 9003, 4: 9005, 6: 9007, 8: 9009, 10: 9011, 12: 9013, 14: 9015, 16: 9017, 18: 9019, 20: 9021, 22: 9023, 24: 9025, 26: 9027, 28: 9029, 30: 9031, 32: 9033, 34: 9035, 36: 9037, 38: 9039, 40: 9041, 42: 9043, 44: 9045, 46: 9047, 48: 9049, 50: 9051, 52: 9053, 54: 9055, 56: 9057, 58: 9059, 60: 9061, 62: 9063, 64: 9065, 66: 9067, 68: 9069, 70: 9071, 72: 9073, 74: 9075, 76: 9077, 78: 9079, 80: 9081, 82: 9083, 84: 9085, 86: 9087, 88: 9089, 90: 9091, 92: 9093, 94: 9095, 96: 9097, 98: 9099, 100: 9101, 102: 9103, 104: 9105, 106: 9107, 108: 9109, 110: 9111, 112: 9113, 114: 9115, 116: 9117, 118: 9119, 120: 9121, 122: 9123, 124: 9125, 126: 9127, 128: 9129, 130: 9131, 132: 9133, 134: 9135, 136: 9137, 138: 9139, 140: 9141, 142: 9143, 144: 9145, 146: 9147, 148: 9149, 150: 9151, 152: 9153, 154: 9155, 156: 9157, 158: 9159, 160: 9161, 162: 9163, 164: 9165, 166: 9167, 168: 9169, 170: 9171, 172: 9173, 174: 9175, 176: 9177, 178: 9179, 180: 9181, 182: 9183, 184: 9185, 186: 9187, 188: 9189, 190: 9191

### 1.3.2. Check if TA is a key of the previous dictionary

In [15]:
"TA" in dict_even_odd.keys()
#TA is not part of keys

False

### 1.3.3. Print the value of brand key of car dictionary

In [16]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

hr_sleep = {"january": {"wednesday": 7,
                      "thursday": 8,
                      "friday": [2, 2, 1, 2]},
          "february": {"saturday": 5,
                       "sunday": 10,
                       "monday": 8
          }
}

In [17]:
car.get('brand') #the value for the key 'brand' is 'Ford'

'Ford'

### 1.3.4. Print all the values of brand key of car dictionary

In [27]:
print(car['brand']) #only values for 'brand'

#to get all the values of car dictionary, I will use 'values' method
car.values()

Ford


dict_values(['Ford', 'Mustang', 1964])

### 1.3.5. Print the max value of friday in january of hr_sleep dictionary

In [31]:
print(max(hr_sleep["january"]["friday"]))

2


### 1.3.6. Add march key to the hr_sleep dictionary using week1 and values2 Python lists

In [32]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

In [36]:
# first, convert lists into dictionary
new_add= dict( zip( week1 , values2 ) )

# then add the dictionary into hr_sleep with a new key
hr_sleep['march']=new_add

print(hr_sleep)

{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]}, 'february': {'saturday': 5, 'sunday': 10, 'monday': 8}, 'march': {'monday': [2, 3, 4], 'sunday': 8}}


dict

## 1.4 Numpy 

### 1. Replace all the even_numbers in np1 with 100. Hint: Use indexing in arrys and this filer

In [1]:
import numpy as np

In [2]:
np1 = np.arange(200, 750)

In [3]:
np1[np1 % 2 == 0] = 100

### 2. Create a 3x3 matrix with values ranging from 0 to 8. Hint: Use np.arange and np.reshape method.

In [4]:
np3 = np.arange(0, 9)
np3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
matrix = np3.reshape((3,3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 3. Consider an array Z = [1,2,3,4,5,6,7,8,9,10], generate an array R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]?.Hint: Use np.arange and np.concatenate

In [6]:
Z = np.arange(1, 11,dtype=int)
Z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
R = rolling(Z, 4)
R

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10]])

In [8]:
R = np.concatenate(R)
R

array([ 1,  2,  3,  4,  2,  3,  4,  5,  3,  4,  5,  6,  4,  5,  6,  7,  5,
        6,  7,  8,  6,  7,  8,  9,  7,  8,  9, 10])

### 4 Create a 3x3x3 array with random values. Hint: Use np.random.random.

In [9]:
array = np.random.random((3,3,3))
array

array([[[0.42998866, 0.33111723, 0.09846721],
        [0.59965035, 0.42785002, 0.5387311 ],
        [0.67056783, 0.50129255, 0.84968808]],

       [[0.92359223, 0.77076085, 0.26081529],
        [0.79121297, 0.32740756, 0.66234393],
        [0.73225855, 0.0493063 , 0.55710917]],

       [[0.92186395, 0.4792279 , 0.40260141],
        [0.30958598, 0.46736499, 0.61383046],
        [0.78476367, 0.47958405, 0.23902258]]])

### 5 Comment why this expression np.nan == np.nan is False. Hint: Use stackoverflow.

The expression NaN = NaN is classified as False because NaN (Not a Number) is an undefined value. It is not zero, nor does it mean that it does not exist, only that it is not defined. Therefore, equating two undefined values is not possible. Nor could one say that an undefined value is greater than or equal to another undefined value.

In [ ]:
## 6 Print the mean and standard deviation of np2. Hint: Use f-string, np.mean, and np.var methods.

In [10]:
np2 = np.random.normal( 50 , 4, 300)

In [11]:
# Mean of np2
mean = np2.mean()
print (mean)

49.79347659992302


In [12]:
# Standard deviation of np2
var = np2.var()
var

17.412746398970423

In [13]:
stdev = np.sqrt(var)
stdev

4.172858300849721

In [14]:
f"The mean of np2 is {mean}, and its standard deviation is {stdev}."

'The mean of np2 is 49.79347659992302, and its standard deviation is 4.172858300849721.'

### Restricted Least Squares

### 1. Get  𝜷ˆ(𝑅𝐿𝑆)  vector from the equation bellow. Use the q, p1, p2, p3, CT numpies.

In [64]:
import pandas as pd
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

In [65]:
greene

id  YEAR     COST        Q        PL      SL      PK      SK      PF  \
0      1  1970   0.2130      8.0   6869.47  0.3291  64.945  0.4197  18.000   
1      4  1970   3.0427    869.0   8372.96  0.1030  68.227  0.2913  21.067   
2      5  1970   9.4059   1412.0   7960.90  0.0891  40.692  0.1567  41.530   
3     14  1970   0.7606     65.0   8971.89  0.2802  41.243  0.1282  28.539   
4     15  1970   2.2587    295.0   8218.40  0.1772  71.940  0.1623  39.200   
..   ...   ...      ...      ...       ...     ...     ...     ...     ...   
153  214  1970   6.8293    946.6  10642.16  0.0883  43.600  0.1914  51.463   
154  215  1970   3.7605    377.0   7432.24  0.2117  74.120  0.2274  33.436   
155  216  1970   3.9822    391.0   5826.04  0.1926  78.288  0.0924  44.633   
156  217  1970  30.1880   5317.0   9586.63  0.0845  78.008  0.2009  41.840   
157  218  1970  67.8562  15220.0   6986.09  0.1451  74.025  0.2596  25.662   

        SF   
0    0.2512  
1    0.6057  
2    0.7542  
3    0.5916  
4    0.6606  
..      ...  
153  0.7203  
154  0.5609  
155  0.7151  
156  0.7147  
157  0.5945  

[158 rows x 10 columns]

In [66]:
ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

In [67]:
import statsmodels.api as sm
import numpy as np

In [68]:
lnct = np.log(ct)
lnq = np.log(q)
lnp1 = np.log(p1)
lnp2 = np.log(p2)
lnp3 = np.log(p3)

In [69]:
ln2p1 = np.multiply(lnp1,lnp1)
ln2p2 = np.multiply(lnp2,lnp2)
ln2p3 = np.multiply(lnp3,lnp3)

In [70]:
ln2p1_2 = np.multiply(ln2p1,0.5)
ln2p2_2 = np.multiply(ln2p2,0.5)
ln2p3_2 = np.multiply(ln2p3,0.5)

In [71]:
lnq2=np.multiply(lnq,lnq)
lnq2_2=np.multiply(lnq2,0.5)

In [72]:
lnqlnp1=np.multiply(lnq,lnp1)
lnqlnp2=np.multiply(lnq,lnp2)
lnqlnp3=np.multiply(lnq,lnp3)

In [73]:
lnp1lnp2 = np.multiply (lnp1,lnp2)
lnp1lnp3 = np.multiply (lnp1,lnp3)
lnp2lnp3 = np.multiply (lnp2,lnp3)

In [74]:
lnp1lnp2_2 = np.multiply (lnp1lnp2,0.5)
lnp1lnp3_2 = np.multiply (lnp1lnp3,0.5)
lnp2lnp3_2 = np.multiply (lnp2lnp3,0.5)

In [75]:
beta_q  = lnq
beta_qq = lnq2_2
beta_q1 = lnqlnp1
beta_q2 = lnqlnp2
beta_q3 = lnqlnp3
beta_1  = lnp1
beta_2  = lnp2
beta_3  = lnp3
beta_11 = ln2p1_2
beta_22 = ln2p2_2
beta_33 = ln2p3_2
beta_12 = lnp1lnp2_2
beta_13 = lnp1lnp3_2
beta_23 = lnp2lnp3_2
beta_21 = beta_12
beta_31 = beta_13
beta_32 = beta_23

In [76]:
y_mdl = sm.OLS.from_formula("lnct ~ beta_q + beta_qq + beta_q1 + beta_q2 + beta_q3 + beta_1 + beta_2 + beta_3 + beta_11 + beta_22 + beta_33 + beta_12 + beta_13 + beta_23", 
                            data = greene)
y_mdl_fit = y_mdl.fit()
print(y_mdl_fit.summary().tables[1])

                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -76.2593     38.280     -1.992      0.048    -151.927      -0.591
beta_q        -1.0804      0.376     -2.877      0.005      -1.823      -0.338
beta_qq        0.0530      0.005     11.240      0.000       0.044       0.062
beta_q1        0.1310      0.038      3.423      0.001       0.055       0.207
beta_q2        0.0587      0.026      2.296      0.023       0.008       0.109
beta_q3        0.0401      0.030      1.348      0.180      -0.019       0.099
beta_1        14.7183      7.085      2.077      0.040       0.714      28.723
beta_2        -0.8947      2.842     -0.315      0.753      -6.513       4.724
beta_3         6.3808      4.529      1.409      0.161      -2.572      15.334
beta_11       -1.5385      0.692     -2.222      0.028      -2.907      -0.170
beta_22       -0.0735      0.182     -0.404      0.6

In [77]:
mdl_glm = sm.GLM.from_formula(formula = y_mdl.formula, data = greene)
mdl_glm_fit = mdl_glm.fit()
print(mdl_glm_fit.summary().tables[1])

                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    -76.2593     38.280     -1.992      0.046    -151.287      -1.232
beta_q        -1.0804      0.376     -2.877      0.004      -1.816      -0.344
beta_qq        0.0530      0.005     11.240      0.000       0.044       0.062
beta_q1        0.1310      0.038      3.423      0.001       0.056       0.206
beta_q2        0.0587      0.026      2.296      0.022       0.009       0.109
beta_q3        0.0401      0.030      1.348      0.178      -0.018       0.099
beta_1        14.7183      7.085      2.077      0.038       0.832      28.604
beta_2        -0.8947      2.842     -0.315      0.753      -6.466       4.676
beta_3         6.3808      4.529      1.409      0.159      -2.496      15.258
beta_11       -1.5385      0.692     -2.222      0.026      -2.896      -0.181
beta_22       -0.0735      0.182     -0.404      0.6

In [78]:
mdl_rls = mdl_glm.fit_constrained("beta_1 + beta_2 + beta_3 = 1, beta_q1 + beta_q2 + beta_q3 = 0, beta_11 + beta_12 + beta_13 = 0, beta_12 + beta_22 + beta_23 = 0, beta_13 + beta_23 + beta_33 = 0")
print(mdl_rls.summary().tables[1])

                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -7.1112      2.913     -2.441      0.015     -12.821      -1.402
beta_q         0.4614      0.127      3.646      0.000       0.213       0.709
beta_qq        0.0600      0.004     13.372      0.000       0.051       0.069
beta_q1       -0.0044      0.024     -0.180      0.857      -0.052       0.043
beta_q2        0.0368      0.026      1.438      0.151      -0.013       0.087
beta_q3       -0.0324      0.023     -1.432      0.152      -0.077       0.012
beta_1         0.2156      1.073      0.201      0.841      -1.888       2.319
beta_2         0.4029      0.586      0.688      0.492      -0.745       1.551
beta_3         0.3815      0.562      0.679      0.497      -0.719       1.482
beta_11       -0.0087      0.149     -0.058      0.953      -0.301       0.283
beta_22        0.0052      0.169      0.030      0.9

### 2.Get the covariance matrix  𝕍ar(𝜷ˆ(𝑅𝐿𝑆)) .

In [79]:
x0 = np.ones(158)
X = np.hstack(( beta_q.reshape(-1, 1), beta_qq.reshape(-1,1) , beta_q1.reshape(-1,1) , beta_q2.reshape(-1,1) ,
              beta_q3.reshape(-1,1), beta_1.reshape(-1,1), beta_2.reshape(-1,1), beta_3.reshape(-1,1), beta_11.reshape(-1,1),
              beta_22.reshape(-1,1), beta_33.reshape(-1,1), beta_12.reshape(-1,1), beta_13.reshape(-1,1), beta_23.reshape(-1,1)))

In [80]:
X

array([[ 2.07944154,  2.16203856, 18.37153796, ..., 12.76798924,
        18.43628708,  6.03154217],
       [ 6.76734313, 22.89846649, 61.12780486, ..., 13.7646109 ,
        19.07195764,  6.43499186],
       [ 7.25276242, 26.30128135, 65.14646856, ..., 16.73588852,
        16.6443385 ,  6.90510767],
       ...,
       [ 5.96870756, 17.81273497, 51.74924846, ..., 16.46655886,
        18.90251177,  8.28142116],
       [ 8.57866451, 36.79674242, 78.65026601, ..., 17.11621413,
        19.97189503,  8.13384624],
       [ 9.63036563, 46.3719711 , 85.2448793 , ..., 14.36189482,
        19.05059047,  6.98391798]])

In [81]:
#X_mat=np.asmatrix(X)
#X_mat

In [82]:
#lnct_mat = lnct.reshape(-1,1)

In [83]:
L=np.array (([0,0,0,0,0,0,1,1,1,0,0,0,0,0,0],
             [0,0,0,1,1,1,0,0,0,0,0,0,0,0,0],
             [0,0,0,0,0,0,0,0,0,1,0,0,1,1,0],
             [0,0,0,0,0,0,0,0,0,0,1,0,1,0,1],
             [0,0,0,0,0,0,0,0,0,0,0,1,0,1,1]))
rr = [1,0,0,0,0]

In [84]:
mdl_rls2 = mdl_glm.fit_constrained((L,rr))
print(mdl_rls2.summary().tables[1])

                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     -7.1112      2.913     -2.441      0.015     -12.821      -1.402
beta_q         0.4614      0.127      3.646      0.000       0.213       0.709
beta_qq        0.0600      0.004     13.372      0.000       0.051       0.069
beta_q1       -0.0044      0.024     -0.180      0.857      -0.052       0.043
beta_q2        0.0368      0.026      1.438      0.151      -0.013       0.087
beta_q3       -0.0324      0.023     -1.432      0.152      -0.077       0.012
beta_1         0.2156      1.073      0.201      0.841      -1.888       2.319
beta_2         0.4029      0.586      0.688      0.492      -0.745       1.551
beta_3         0.3815      0.562      0.679      0.497      -0.719       1.482
beta_11       -0.0087      0.149     -0.058      0.953      -0.301       0.283
beta_22        0.0052      0.169      0.030      0.9

In [87]:
X_d = sm.add_constant(X)

In [88]:
xtx_inv  = np.linalg.inv(np.dot(np.transpose(X_d), X_d))
beta_ols = np.dot(xtx_inv, np.dot(np.transpose(X_d), lnct))

In [90]:
RA_1 = np.dot(xtx_inv, np.transpose(L))
RA_2 = np.linalg.inv(np.linalg.multi_dot([L, xtx_inv, np.transpose(L)]))
RA_3 = np.dot(L, beta_ols) - np.array(rr)
RA   = RA_1.dot(RA_2).dot(RA_3)
RA 

array([-6.91480570e+01, -1.54179333e+00, -6.97690070e-03,  1.35394988e-01,
        2.18742238e-02,  7.25679772e-02,  1.45027254e+01, -1.29765594e+00,
        5.99928604e+00, -1.52981504e+00, -7.86612353e-02, -3.12112571e-01,
        3.30438341e-01, -1.15868571e+00, -4.87662759e-02])

In [91]:
beta_rls = beta_ols - RA
beta_rls.shape
beta_rls

array([-7.11120011e+00,  4.61367985e-01,  5.99553934e-02, -4.35440198e-03,
        3.67779793e-02, -3.24235773e-02,  2.15566353e-01,  4.02923024e-01,
        3.81510623e-01, -8.71224206e-03,  5.15567485e-03, -1.53016764e-02,
       -5.87255460e-03,  1.45847967e-02,  7.16879746e-04])

In [92]:
y_fit = np.dot(X_d, beta_rls)
y_fit.shape

(158,)

In [107]:
resid = np.array(lnct) - mdl_rls2.predict()
resid.shape

(158,)

In [108]:
sigma2_rls = np.sum(resid**2) / (len(greene.index) - (len(beta_rls) - len(rr)))

In [109]:
D_mat = np.identity(len(beta_rls)) - RA_1.dot(RA_2).dot(L)
rls_vcov = sigma2_rls * D_mat.dot(xtx_inv)
beta_rls_se = np.sqrt(np.diag(rls_vcov))

In [110]:
rls_vcov

array([[ 8.48589522e+00, -9.61600638e-02,  2.05747327e-04,
         1.56765358e-02, -2.21038019e-02,  6.42726609e-03,
        -3.05050166e+00,  1.61354413e+00,  1.43695752e+00,
         3.96518508e-01, -9.19352072e-02, -8.22144548e-01,
        -5.63363924e-01,  1.66845416e-01,  6.55299132e-01],
       [-9.61600638e-02,  1.60149394e-02, -6.96792552e-05,
        -2.91213527e-03,  2.26965574e-03,  6.42479533e-04,
         1.21925219e-02, -1.47386571e-02,  2.54613521e-03,
         1.59342538e-03, -2.91860121e-03, -1.31690219e-03,
         4.13682235e-06, -1.59756220e-03,  2.91446439e-03],
       [ 2.05747327e-04, -6.96792552e-05,  2.01030000e-05,
        -1.63509023e-05, -2.39709641e-06,  1.87479987e-05,
        -3.76839390e-05,  1.50075217e-04, -1.12391278e-04,
         2.49444200e-05,  6.14974496e-05, -9.65394665e-05,
        -9.14906680e-05,  6.65462480e-05,  2.99932184e-05],
       [ 1.56765358e-02, -2.91213527e-03, -1.63509023e-05,
         5.84940247e-04, -3.63383123e-04, -2.21557124

In [111]:
print(pd.DataFrame(np.column_stack([beta_rls, beta_rls_se]), columns = ["est", "se"],
                   index = ["", "beta_q", "beta_qq", "beta_q1", "beta_q2","beta_q3","beta_1","beta_2","beta_3","beta_11","beta_22","beta_33","beta_12","beta_13","beta_23"]))

              est        se
        -7.111200  2.913056
beta_q   0.461368  0.126550
beta_qq  0.059955  0.004484
beta_q1 -0.004354  0.024186
beta_q2  0.036778  0.025582
beta_q3 -0.032424  0.022641
beta_1   0.215566  1.073111
beta_2   0.402923  0.585771
beta_3   0.381511  0.561622
beta_11 -0.008712  0.149001
beta_22  0.005156  0.169478
beta_33 -0.015302  0.317445
beta_12 -0.005873  0.240722
beta_13  0.014585  0.155727
beta_23  0.000717  0.244646


In [116]:
matriz_var_cov_beta_rls=pd.DataFrame(rls_vcov)
matriz_var_cov_beta_rls

0         1         2         3         4         5         6   \
0   8.485895 -0.096160  0.000206  0.015677 -0.022104  0.006427 -3.050502   
1  -0.096160  0.016015 -0.000070 -0.002912  0.002270  0.000642  0.012193   
2   0.000206 -0.000070  0.000020 -0.000016 -0.000002  0.000019 -0.000038   
3   0.015677 -0.002912 -0.000016  0.000585 -0.000363 -0.000222 -0.001377   
4  -0.022104  0.002270 -0.000002 -0.000363  0.000654 -0.000291  0.005099   
5   0.006427  0.000642  0.000019 -0.000222 -0.000291  0.000513 -0.003722   
6  -3.050502  0.012193 -0.000038 -0.001377  0.005099 -0.003722  1.151568   
7   1.613544 -0.014739  0.000150  0.001701 -0.006121  0.004419 -0.589638   
8   1.436958  0.002546 -0.000112 -0.000324  0.001022 -0.000697 -0.561930   
9   0.396519  0.001593  0.000025 -0.000480 -0.000333  0.000813 -0.156461   
10 -0.091935 -0.002919  0.000061  0.000562  0.000057 -0.000619  0.045596   
11 -0.822145 -0.001317 -0.000097  0.000574  0.000461 -0.001035  0.309679   
12 -0.563364  0.000004 -0.000091  0.000246  0.000368 -0.000614  0.210272   
13  0.166845 -0.001598  0.000067  0.000234 -0.000035 -0.000198 -0.053811   
14  0.655299  0.002914  0.000030 -0.000808 -0.000425  0.001233 -0.255868   

          7         8         9         10        11        12        13  \
0   1.613544  1.436958  0.396519 -0.091935 -0.822145 -0.563364  0.166845   
1  -0.014739  0.002546  0.001593 -0.002919 -0.001317  0.000004 -0.001598   
2   0.000150 -0.000112  0.000025  0.000061 -0.000097 -0.000091  0.000067   
3   0.001701 -0.000324 -0.000480  0.000562  0.000574  0.000246  0.000234   
4  -0.006121  0.001022 -0.000333  0.000057  0.000461  0.000368 -0.000035   
5   0.004419 -0.000697  0.000813 -0.000619 -0.001035 -0.000614 -0.000198   
6  -0.589638 -0.561930 -0.156461  0.045596  0.309679  0.210272 -0.053811   
7   0.343127  0.246511  0.078041 -0.002547 -0.171224 -0.123359  0.045318   
8   0.246511  0.315419  0.078420 -0.043049 -0.138456 -0.086913  0.008493   
9   0.078041  0.078420  0.022201 -0.008255 -0.041951 -0.027949  0.005747   
10 -0.002547 -0.043049 -0.008255  0.028723 -0.006350 -0.013409  0.021664   
11 -0.171224 -0.138456 -0.041951 -0.006350  0.100772  0.074536 -0.032585   
12 -0.123359 -0.086913 -0.027949 -0.013409  0.074536  0.057947 -0.029998   
13  0.045318  0.008493  0.005747  0.021664 -0.032585 -0.029998  0.024251   
14  0.125906  0.129962  0.036204 -0.015314 -0.068186 -0.044538  0.008334   

          14  
0   0.655299  
1   0.002914  
2   0.000030  
3  -0.000808  
4  -0.000425  
5   0.001233  
6  -0.255868  
7   0.125906  
8   0.129962  
9   0.036204  
10 -0.015314  
11 -0.068186  
12 -0.044538  
13  0.008334  
14  0.059852

In [114]:
mdl_rls2.cov_params()

Intercept    beta_q   beta_qq   beta_q1   beta_q2   beta_q3  \
Intercept   8.485895 -0.096160  0.000206  0.015677 -0.022104  0.006427   
beta_q     -0.096160  0.016015 -0.000070 -0.002912  0.002270  0.000642   
beta_qq     0.000206 -0.000070  0.000020 -0.000016 -0.000002  0.000019   
beta_q1     0.015677 -0.002912 -0.000016  0.000585 -0.000363 -0.000222   
beta_q2    -0.022104  0.002270 -0.000002 -0.000363  0.000654 -0.000291   
beta_q3     0.006427  0.000642  0.000019 -0.000222 -0.000291  0.000513   
beta_1     -3.050502  0.012193 -0.000038 -0.001377  0.005099 -0.003722   
beta_2      1.613544 -0.014739  0.000150  0.001701 -0.006121  0.004419   
beta_3      1.436958  0.002546 -0.000112 -0.000324  0.001022 -0.000697   
beta_11     0.396519  0.001593  0.000025 -0.000480 -0.000333  0.000813   
beta_22    -0.091935 -0.002919  0.000061  0.000562  0.000057 -0.000619   
beta_33    -0.822145 -0.001317 -0.000097  0.000574  0.000461 -0.001035   
beta_12    -0.563364  0.000004 -0.000091  0.000246  0.000368 -0.000614   
beta_13     0.166845 -0.001598  0.000067  0.000234 -0.000035 -0.000198   
beta_23     0.655299  0.002914  0.000030 -0.000808 -0.000425  0.001233   

             beta_1    beta_2    beta_3   beta_11   beta_22   beta_33  \
Intercept -3.050502  1.613544  1.436958  0.396519 -0.091935 -0.822145   
beta_q     0.012193 -0.014739  0.002546  0.001593 -0.002919 -0.001317   
beta_qq   -0.000038  0.000150 -0.000112  0.000025  0.000061 -0.000097   
beta_q1   -0.001377  0.001701 -0.000324 -0.000480  0.000562  0.000574   
beta_q2    0.005099 -0.006121  0.001022 -0.000333  0.000057  0.000461   
beta_q3   -0.003722  0.004419 -0.000697  0.000813 -0.000619 -0.001035   
beta_1     1.151568 -0.589638 -0.561930 -0.156461  0.045596  0.309679   
beta_2    -0.589638  0.343127  0.246511  0.078041 -0.002547 -0.171224   
beta_3    -0.561930  0.246511  0.315419  0.078420 -0.043049 -0.138456   
beta_11   -0.156461  0.078041  0.078420  0.022201 -0.008255 -0.041951   
beta_22    0.045596 -0.002547 -0.043049 -0.008255  0.028723 -0.006350   
beta_33    0.309679 -0.171224 -0.138456 -0.041951 -0.006350  0.100772   
beta_12    0.210272 -0.123359 -0.086913 -0.027949 -0.013409  0.074536   
beta_13   -0.053811  0.045318  0.008493  0.005747  0.021664 -0.032585   
beta_23   -0.255868  0.125906  0.129962  0.036204 -0.015314 -0.068186   

            beta_12   beta_13   beta_23  
Intercept -0.563364  0.166845  0.655299  
beta_q     0.000004 -0.001598  0.002914  
beta_qq   -0.000091  0.000067  0.000030  
beta_q1    0.000246  0.000234 -0.000808  
beta_q2    0.000368 -0.000035 -0.000425  
beta_q3   -0.000614 -0.000198  0.001233  
beta_1     0.210272 -0.053811 -0.255868  
beta_2    -0.123359  0.045318  0.125906  
beta_3    -0.086913  0.008493  0.129962  
beta_11   -0.027949  0.005747  0.036204  
beta_22   -0.013409  0.021664 -0.015314  
beta_33    0.074536 -0.032585 -0.068186  
beta_12    0.057947 -0.029998 -0.044538  
beta_13   -0.029998  0.024251  0.008334  
beta_23   -0.044538  0.008334  0.059852