# Assignment 1 – Part 1: Git Workflow (Branch → Pull Request → Merge)

---

## Q1: Difference between working on a branch and working directly on main

- **Main**: This is the central branch of the repository. If you edit directly here, any mistakes or bugs affect the entire project.
- **Branch**: A separate working space where you can make changes without affecting `main`. Once changes are tested and reviewed, they can be merged back into `main`.

**Why is it recommended to always use branches in collaborative projects?**

- Prevents breaking the main codebase.
- Allows multiple people to work independently on different features or files.
- Makes it easier to review and manage contributions before merging.

---

## Q3: Git command for the commit

git add Diplomado_PUCP/Lecture_1/Assignment_1/movies.md

git commit -m "Added my favorite movies"

## Q4: Repository maintainer
- Nicole

## Q5: Pull Request (PR) explanation

- After finishing changes in the branch, we must create a **Pull Request (PR)** to merge `group_06_assignment1_2025` into `main`.  
- The PR allows the maintainer and other collaborators to review the changes before they are merged.  

**A reviewer might reject the PR if:**
- There are **code conflicts** with `main`.  
- The contribution **does not follow instructions** (wrong folder, missing file, incorrect branch name).  
- There are **formatting errors** (Markdown not clean, wrong structure).  
- The submission is **incomplete** (less than 3 movies, missing synopsis, etc.).  

In [18]:
##Parte 2 – Data Types and Data Structures

# Variables de distintos tipos
x_int = 10
x_float = 3.14
x_str = "Hola Python"
x_bool = True

print(type(x_int))
print(type(x_float))
print(type(x_str))
print(type(x_bool))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [19]:
# Lista con varios elementos
my_list = [
    "cadena de texto",
    False,
    42,
    7.5,
    ["Bad Bunny", "Shakira"]
]

# Acceder al primer y último elemento
print("Primer elemento:", my_list[0])
print("Último elemento:", my_list[-1])

# Agregar un nuevo string
my_list.append("Nuevo elemento")
print("Lista con nuevo elemento:", my_list)

# Eliminar el booleano
my_list.remove(False)
print("Lista sin el booleano:", my_list)

Primer elemento: cadena de texto
Último elemento: ['Bad Bunny', 'Shakira']
Lista con nuevo elemento: ['cadena de texto', False, 42, 7.5, ['Bad Bunny', 'Shakira'], 'Nuevo elemento']
Lista sin el booleano: ['cadena de texto', 42, 7.5, ['Bad Bunny', 'Shakira'], 'Nuevo elemento']


In [20]:
# Definición de tupla
my_tuple = (
    "Python",
    True,
    (1, 2, 3)
)

print("Mi tupla:", my_tuple)

# Explicación: una tupla es inmutable (no se puede cambiar después de creada).
# Intentar modificarla dará error:
try:
    my_tuple[0] = "Java"
except TypeError as e:
    print("Error al modificar la tupla:", e)

Mi tupla: ('Python', True, (1, 2, 3))
Error al modificar la tupla: 'tuple' object does not support item assignment


In [22]:
# Función movie_summary
def movie_summary(movies):
    summaries = []
    for title, info in movies.items():
        summaries.append(f"The movie {title} belongs to the {info['genre']} genre and was released in {info['year']}.")
    return summaries

movies = {
  "Inception": {"year": 2010, "genre": "Sci-Fi"},
  "Parasite": {"year": 2019, "genre": "Drama"},
  "Whiplash": {"year": 2014, "genre": "Drama"}
}

movie_summary(movies)

['The movie Inception belongs to the Sci-Fi genre and was released in 2010.',
 'The movie Parasite belongs to the Drama genre and was released in 2019.',
 'The movie Whiplash belongs to the Drama genre and was released in 2014.']

In [23]:
# Numpy: matriz 4x4 con enteros aleatorios
import numpy as np

matrix = np.random.randint(1, 101, size=(4, 4))
print("Matriz:\n", matrix)

# Media por columna
print("Media por columna:", matrix.mean(axis=0))

# Suma de la diagonal principal
print("Suma diagonal:", np.trace(matrix))

Matriz:
 [[52 42 43 14]
 [82  6 79 41]
 [42 23 31 41]
 [65 85  4 30]]
Media por columna: [60.25 39.   39.25 31.5 ]
Suma diagonal: 119


In [24]:
import pandas as pd

grades = [15, 17, 20, 11, 13, 18, 19]
students = ["Ana", "Jorge", "Valeria", "Luis", "María", "Pedro", "Lucía"]

grades_series = pd.Series(grades, index=students)
print(grades_series)

Ana        15
Jorge      17
Valeria    20
Luis       11
María      13
Pedro      18
Lucía      19
dtype: int64


In [25]:
# Promedio de notas
print("Promedio:", grades_series.mean())

# Estudiante con nota más alta
print("Mayor nota:", grades_series.idxmax())

# Estudiante con nota más baja
print("Menor nota:", grades_series.idxmin())


Promedio: 16.142857142857142
Mayor nota: Valeria
Menor nota: Luis


In [26]:
# Serie de países y capitales
countries = {
    "Peru": "Lima",
    "Argentina": "Buenos Aires",
    "Mexico": "Ciudad de Mexico",
    "Chile": "Santiago"
}

capitals_series = pd.Series(countries)
print("Todas las capitales:\n", capitals_series)

# Filtrar capitales con más de 6 letras
print("Capitales con más de 6 letras:\n", capitals_series[capitals_series.str.len() > 6])


Todas las capitales:
 Peru                     Lima
Argentina        Buenos Aires
Mexico       Ciudad de Mexico
Chile                Santiago
dtype: object
Capitales con más de 6 letras:
 Argentina        Buenos Aires
Mexico       Ciudad de Mexico
Chile                Santiago
dtype: object


In [27]:
# Serie con strings y conversión a mayúsculas
text_series = pd.Series(["python", "git", "github", "anaconda"])
print(text_series.apply(str.upper))


0      PYTHON
1         GIT
2      GITHUB
3    ANACONDA
dtype: object
