# Part 2 – Data Types and Data Structures

## 2.6 Declare a variable for each of the following types: int, float, string, and boolean. Then print the type of each variable using the type() function.

In [7]:
int_var = 11
float_var = 11.0
string_var = "GROUP ELEVEN"
boolean_var = 11>10

# Print the type of each variable
print(type(int_var))
print(type(float_var))
print(type(string_var))
print(type(boolean_var))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


## 2.7 Create a list that contains the following elements:
A string, A boolean value, Two numeric values (of any type), A list with two strings representing your favorite music artists


In [8]:
list_1 = [
    "GROUP ELEVEN!",      # A string
    11>10,                # A boolean value
    42,                   # First numeric value (integer)
    11.0,                 # Second numeric value (float)
    ["Enrique Bumbury", "Maykel Blanco"]  # List with two strings (favorite music artists)
]

# Print the list
print(list_1)

['GROUP ELEVEN!', True, 42, 11.0, ['Enrique Bumbury', 'Maykel Blanco']]


*From that list:*
2.2.1 Access the first and the last element

In [9]:
first_element=list_1[0]
last_element=list_1[4]
print(first_element)
print(last_element)

GROUP ELEVEN!
['Enrique Bumbury', 'Maykel Blanco']


2.2.2 Add a new string


In [10]:
list_1.append("Led Zepellin")

2.2.3 Remove the boolean value

In [11]:
list_1.remove(True)

2.2.4 Print the modified list

In [12]:
print("Modified list:", list_1)

Modified list: ['GROUP ELEVEN!', 42, 11.0, ['Enrique Bumbury', 'Maykel Blanco'], 'Led Zepellin']


## 2.8. Define a tuple that contains:
A string,
A boolean,
A tuple with three numeric values (of any type)

In [13]:
# Definimos la tupla
my_tuple = ("Hola", True, (10, 20.5, 30))

# Explicación: las tuplas son inmutables, es decir, no se pueden modificar después de ser creadas.
# Probemos cambiar el primer elemento para demostrarlo:
try:
    my_tuple[0] = "Holi"
except TypeError as e:
    print("Error:", e)  


Error: 'tuple' object does not support item assignment


## 2.9. Write a Python function named movie_summary that takes as argument a dictionary of movies with the following structure:
movies = {
  "Inception": {"year": 2010, "genre": "Sci-Fi"},
  "Parasite": {"year": 2019, "genre": "Drama"},
  "Whiplash": {"year": 2014, "genre": "Drama"}
}

In [14]:
def movie_summary(movies):
    summaries = []
    for title, info in movies.items():
        sentence = f"The movie {title} belongs to the {info['genre']} genre and was released in {info['year']}."
        summaries.append(sentence)
    return summaries

# Diccionario con mis películas favoritas
movies = {
    "Coraline": {"year": 2009, "genre": "Dark Fantasy"},
    "Spirited Away": {"year": 2001, "genre": "Fantasy"},
    "City of God": {"year": 2002, "genre": "Crime Drama"}
}

print(movie_summary(movies))


['The movie Coraline belongs to the Dark Fantasy genre and was released in 2009.', 'The movie Spirited Away belongs to the Fantasy genre and was released in 2001.', 'The movie City of God belongs to the Crime Drama genre and was released in 2002.']


## 2.10. Using NumPy, generate a 4x4 matrix with random integers between 1 and 100.
Then calculate: 
The mean per column, 
The sum of the values in the main diagonal

In [15]:
import numpy as np

# Generamos matriz aleatoria 4x4 con enteros entre 1 y 100
matrix = np.random.randint(1, 101, size=(4, 4))
print("4x4 matrix:\n", matrix)

# Media por columna
mean_per_column = np.mean(matrix, axis=0)
print("mean per column:", mean_per_column)

# Suma de la diagonal principal
sum_diagonal = np.trace(matrix)
print("sum of the values in the main diagonal:", sum_diagonal)


4x4 matrix:
 [[66 89 15 13]
 [16 19 86  4]
 [25 32 23 80]
 [51 42 96 88]]
mean per column: [39.5  45.5  55.   46.25]
sum of the values in the main diagonal: 196


# Part 3 – Pandas Series

In [1]:
import pandas as pd

## 3.11 From the list of grades [15, 17, 20, 11, 13, 18, 19], create a Pandas Series assigning student names as the index (for example: "Ana", "Jorge", "Valeria", etc.).

In [2]:
# Listado de notas
grades = [15, 17, 20, 11, 13, 18, 19]

# Nombre de los estudiantes para los índices
student_names = ["Ana", "Jorge", "Valeria", "Carlos", "Sofia", "Miguel", "Isabella"]

# Crear un Panda Series con los nombres de los estudiantes como índices
student_grades = pd.Series(grades, index=student_names, name="Grades")

# Mostrar las series
print("Student Grades Series:")
print(student_grades)
print(f"\nSeries Info:")
print(f"Data type: {student_grades.dtype}")
print(f"Number of students: {len(student_grades)}")

Student Grades Series:
Ana         15
Jorge       17
Valeria     20
Carlos      11
Sofia       13
Miguel      18
Isabella    19
Name: Grades, dtype: int64

Series Info:
Data type: int64
Number of students: 7


## 3.12 Using the Series created in the previous step, calculate:

The average of the grades.
The student with the highest grade (use .idxmax()).
The student with the lowest grade (use .idxmin()).

In [4]:
# Promedio de las notas
average_grade = student_grades.mean()
print(f"Average grade: {average_grade:.2f}")

# Estudiante con la nota más alta usando .idxmax() 
student_highest = student_grades.idxmax()
highest_grade = student_grades.max()
print(f"Student with highest grade: {student_highest} (Grade: {highest_grade})")

# Estudiante con la nota más baja usando .idxmin()
student_lowest = student_grades.idxmin()
lowest_grade = student_grades.min()
print(f"Student with lowest grade: {student_lowest} (Grade: {lowest_grade})")

Average grade: 16.14
Student with highest grade: Valeria (Grade: 20)
Student with lowest grade: Carlos (Grade: 11)


## 3.13 Create a Series from a dictionary of countries and their capitals.
Filter and display only those countries whose capital has more than 6 letters.

In [7]:
# Crear un diccionario de países con sus capitales
countries_capitals = {
    'USA': 'Washington',
    'France': 'Paris',
    'Germany': 'Berlin',
    'Japan': 'Tokyo',
    'Brazil': 'Brasilia',
    'Australia': 'Canberra',
    'Canada': 'Ottawa',
    'India': 'New Delhi',
    'China': 'Beijing',
    'Russia': 'Moscow',
    'Italy': 'Rome',
    'Spain': 'Madrid',
    'UK': 'London',
    'Mexico': 'Mexico City',
    'Argentina': 'Buenos Aires',
    'Egypt': 'Cairo',
    'South Africa': 'Cape Town',
    'Thailand': 'Bangkok',
    'Norway': 'Oslo',
    'Sweden': 'Stockholm'
}

# Crear un Panda Series desde el diccionario
countries_series = pd.Series(countries_capitals, name='Capital')
countries_series.index.name = 'Country'

print("Original Series:")
print(countries_series)
print("\n" + "="*50 + "\n")

# Filtrar los países cuyas capitales tengan más de 6 letras
filtered_series = countries_series[countries_series.str.len() > 6]

print("Countries with capitals having more than 6 letters:")
print(filtered_series)
print(f"\nTotal countries with capitals > 6 letters: {len(filtered_series)}")

# Mostrar los resultados en un formato más detallado
print("\n" + "="*50)
print("DETAILED RESULTS:")
print("="*50)
for country, capital in filtered_series.items():
    print(f"{country:15} -> {capital} ({len(capital)} letters)")

Original Series:
Country
USA               Washington
France                 Paris
Germany               Berlin
Japan                  Tokyo
Brazil              Brasilia
Australia           Canberra
Canada                Ottawa
India              New Delhi
China                Beijing
Russia                Moscow
Italy                   Rome
Spain                 Madrid
UK                    London
Mexico           Mexico City
Argentina       Buenos Aires
Egypt                  Cairo
South Africa       Cape Town
Thailand             Bangkok
Norway                  Oslo
Sweden             Stockholm
Name: Capital, dtype: object


Countries with capitals having more than 6 letters:
Country
USA               Washington
Brazil              Brasilia
Australia           Canberra
India              New Delhi
China                Beijing
Mexico           Mexico City
Argentina       Buenos Aires
South Africa       Cape Town
Thailand             Bangkok
Sweden             Stockholm
Name: Capital,

## 3.14 Create a Series containing several strings and convert all its elements to uppercase using the .apply(str.upper) method.

In [8]:
# Crear una Serie que contenga varios objetos tipo string
string_data = [
    "geography",
    "economy",
    "data science",
    "machine learning",
    "artificial intelligence",
    "deep learning",
    "spatial analysis",
    "geodatabase"
]

# Crear el Panda Series
original_series = pd.Series(string_data, name="Original_Strings")

print("Original Series (lowercase/mixed case):")
print("=" * 40)
print(original_series)
print()

# Convertir todos los elementos a mayúsculas usando
uppercase_series = original_series.apply(str.upper) .apply(str.upper) 

print("Series converted to UPPERCASE using .apply(str.upper):")
print("=" * 55)
print(uppercase_series)
print()

Original Series (lowercase/mixed case):
0                  geography
1                    economy
2               data science
3           machine learning
4    artificial intelligence
5              deep learning
6           spatial analysis
7                geodatabase
Name: Original_Strings, dtype: object

Series converted to UPPERCASE using .apply(str.upper):
0                  GEOGRAPHY
1                    ECONOMY
2               DATA SCIENCE
3           MACHINE LEARNING
4    ARTIFICIAL INTELLIGENCE
5              DEEP LEARNING
6           SPATIAL ANALYSIS
7                GEODATABASE
Name: Original_Strings, dtype: object

