# Part 2 – Data Types and Data Structures

## 2.6 Declare a variable for each of the following types: int, float, string, and boolean. Then print the type of each variable using the type() function.

In [7]:
int_var = 11
float_var = 11.0
string_var = "GROUP ELEVEN"
boolean_var = 11>10

# Print the type of each variable
print(type(int_var))
print(type(float_var))
print(type(string_var))
print(type(boolean_var))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


## 2.7 Create a list that contains the following elements:
A string, A boolean value, Two numeric values (of any type), A list with two strings representing your favorite music artists


In [8]:
list_1 = [
    "GROUP ELEVEN!",      # A string
    11>10,                # A boolean value
    42,                   # First numeric value (integer)
    11.0,                 # Second numeric value (float)
    ["Enrique Bumbury", "Maykel Blanco"]  # List with two strings (favorite music artists)
]

# Print the list
print(list_1)

['GROUP ELEVEN!', True, 42, 11.0, ['Enrique Bumbury', 'Maykel Blanco']]


*From that list:*
2.2.1 Access the first and the last element

In [9]:
first_element=list_1[0]
last_element=list_1[4]
print(first_element)
print(last_element)

GROUP ELEVEN!
['Enrique Bumbury', 'Maykel Blanco']


2.2.2 Add a new string


In [10]:
list_1.append("Led Zepellin")

2.2.3 Remove the boolean value

In [11]:
list_1.remove(True)

2.2.4 Print the modified list

In [12]:
print("Modified list:", list_1)

Modified list: ['GROUP ELEVEN!', 42, 11.0, ['Enrique Bumbury', 'Maykel Blanco'], 'Led Zepellin']


## 2.8. Define a tuple that contains:
A string,
A boolean,
A tuple with three numeric values (of any type)

In [13]:
# Definimos la tupla
my_tuple = ("Hola", True, (10, 20.5, 30))

# Explicación: las tuplas son inmutables, es decir, no se pueden modificar después de ser creadas.
# Probemos cambiar el primer elemento para demostrarlo:
try:
    my_tuple[0] = "Holi"
except TypeError as e:
    print("Error:", e)  


Error: 'tuple' object does not support item assignment


## 2.9. Write a Python function named movie_summary that takes as argument a dictionary of movies with the following structure:
movies = {
  "Inception": {"year": 2010, "genre": "Sci-Fi"},
  "Parasite": {"year": 2019, "genre": "Drama"},
  "Whiplash": {"year": 2014, "genre": "Drama"}
}

In [14]:
def movie_summary(movies):
    summaries = []
    for title, info in movies.items():
        sentence = f"The movie {title} belongs to the {info['genre']} genre and was released in {info['year']}."
        summaries.append(sentence)
    return summaries

# Diccionario con mis películas favoritas
movies = {
    "Coraline": {"year": 2009, "genre": "Dark Fantasy"},
    "Spirited Away": {"year": 2001, "genre": "Fantasy"},
    "City of God": {"year": 2002, "genre": "Crime Drama"}
}

print(movie_summary(movies))


['The movie Coraline belongs to the Dark Fantasy genre and was released in 2009.', 'The movie Spirited Away belongs to the Fantasy genre and was released in 2001.', 'The movie City of God belongs to the Crime Drama genre and was released in 2002.']


## 2.10. Using NumPy, generate a 4x4 matrix with random integers between 1 and 100.
Then calculate: 
The mean per column, 
The sum of the values in the main diagonal

In [15]:
import numpy as np

# Generamos matriz aleatoria 4x4 con enteros entre 1 y 100
matrix = np.random.randint(1, 101, size=(4, 4))
print("4x4 matrix:\n", matrix)

# Media por columna
mean_per_column = np.mean(matrix, axis=0)
print("mean per column:", mean_per_column)

# Suma de la diagonal principal
sum_diagonal = np.trace(matrix)
print("sum of the values in the main diagonal:", sum_diagonal)


4x4 matrix:
 [[66 89 15 13]
 [16 19 86  4]
 [25 32 23 80]
 [51 42 96 88]]
mean per column: [39.5  45.5  55.   46.25]
sum of the values in the main diagonal: 196


# Part 3 – Pandas Series