# 1 Assignment

It is totally prohibited to use any kind of loop. You can use stackoverflow. If you copy codes from previous answers, explain each step. No explanation is `0 points`.

## 1.1 Tuple



1. Print the first item of the second item of `tuple1` object. **Hint: Use indexing**<br><br>
2. Print the last item of the `tuple1` object.**Hint: Use indexing**<br><br>
3. Change the value "orange" for "pink grapefruit". Comment the output. **Hint: Is it possible?** <br><br>
4. Print the length of `tuple1`. **Hint: Length function**<br><br>
5. Sum all the elements of tuple2 and describe your steps and explain each of them. **Hint: Use `map` function.**<br><br>
6. Generate a new tuple object named as `tuple3` with the half values of `tuple2`. This tuple should be similar as `tuple2`, tuple of lists.  **Hint: Use `map` funciont.**<br><br>

In [ ]:
tuple1 = ("Orange", [10, 20, 30], (5, 15, 25))
tuple2 = ([7, 8], [9, 1], [10, 7])

In [ ]:
## 1.1 Tuple - Resolution

In [ ]:
# 1. Print the first item of the second item of tuple1 object
# We can approach this this problem in two ways:
# I. The long way
pr1 = tuple1[1]     # we extract the second item of the tuple1 object
print(pr1)          # we have a list of 3 elements
print(pr1[0])       # finally, we extract the first item of the pr1 object

[10, 20, 30]
10


In [ ]:
# II. The short way
print(tuple1[1][0]) # we are accessing the requested item in a nested list (tuple1 object)

10


In [ ]:
# 2. Print the last item of the tuple1 object
print(tuple1[-1])   # we can extract the last item indicating -1 as the last element
print(tuple1[2])    # also, we can access to the last item using an index of 2

(5, 15, 25)
(5, 15, 25)


In [ ]:
# 3. Change the value "orange" for "pink grapefruit". Comment the output
# At first it is not possible because tuple1 is a tuple (an inmutable container)
tuple1_list = list(tuple1)      # So, to make any modifications we must first convert it to a list
type(tuple1_list)

list

In [ ]:
# Now we can make the modification
tuple1_list[0] = "pink grapefruit"      # we change the first element of the list for 'pink grapefruit'
tuple1_list

['pink grapefruit', [10, 20, 30], (5, 15, 25)]

In [ ]:
# Additionaly, if we want to return to a tuple object
tuple(tuple1_list)

('pink grapefruit', [10, 20, 30], (5, 15, 25))

In [ ]:
# 4. Print the length of tuple1
print(len(tuple1))

3


In [ ]:
# 5. Sum all the elements of tuple2 and describe your steps and explain each of them
# We must convert tupple2 to a modifiable object. 
# In this case is suitable convert it to an array
# Step 1: we import numpy library to apply array function
import numpy as np

In [ ]:
# Step 2: we apply np.array function and assigned to a variable
tp2_arr = np.array(tuple2)
tp2_arr

array([[ 7,  8],
       [ 9,  1],
       [10,  7]])

In [ ]:
# Step 3: there is a numpy function that allows us to add up all the elements of the array
suma = np.sum(tp2_arr)
suma                    # finally, we can see the sum of all the elements of tuple2

42

In [ ]:
# 6. Generate a new tuple object named as tuple3 with the half values of tuple2. 
# This tuple should be similar as tuple2, tuple of lists
tp2_arr   # we can use the variable (array) created before

array([[ 7,  8],
       [ 9,  1],
       [10,  7]])

In [ ]:
# We can perform calculations with an array, including the division
tp2_div = tp2_arr/2
tp2_div

array([[3.5, 4. ],
       [4.5, 0.5],
       [5. , 3.5]])

In [ ]:
# We have the half values of tuple2. However, the structure of this new object is not similar to tuple2.
# So, we can convert to a tuple 
tuple(tp2_div)      # we have a tuple but with array elements: tuple of arrays


(array([3.5, 4. ]), array([4.5, 0.5]), array([5. , 3.5]))

In [ ]:
# But we want a tupple of list. So, we need to apply list() funtion to each array.
# And we can do this with map() function. 
tp2_fin = tuple(map(list, tp2_div))     # we apply a specific funtion to each element of tp2_div
tp2_fin

([3.5, 4.0], [4.5, 0.5], [5.0, 3.5])

In [ ]:
# we compare both tuples and we verify that both have the same structure
print(tp2_fin)
print(tuple2)

([3.5, 4.0], [4.5, 0.5], [5.0, 3.5])
([7, 8], [9, 1], [10, 7])


## 1.2 Lists
1. Show the indices of the `np.nan` values  in the `f_list` list. We want to see this output: `The indices 0, 1, 4, 7 have np.nan values.` **Hint: Use print function and [f-strings](https://realpython.com/python-f-strings/) to insert the indices values.**<br><br>

2. Replicate 4 times the values of the list `p2_list`. We expect an ouput like this: `[ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]`.  **Hint: Use multiplication function in `lists`and see the output.**<br><br>
3. Print the length of `f_list`. **Hint: Length function**<br><br>
4. Print `My teacher assistant is so boring.` using `text1` list. **Hint: Use the [`join` function](https://stackoverflow.com/questions/493819/why-is-it-string-joinlist-instead-of-list-joinstring)**<br><br>
5. Print `My TA is so boring, but is very funny.` using `text1` list.**Hint: Use the `join` function, and `extend` method.**<br><br>
6. Print <br>
`The max value of values1 is 86 and is located in the 0 index. ` <br>
`The min value of values1 is 0 and is located in the 7 index. ` <br> **Hint: Use the `f-string`, `min`, and `max` functions.**
<br>
7. Get two lists: `names` and `last_names` using `last_and_name` list. **Hint: Use `map` and `split`.**
<br>
8. Give only the last names of students who do not have email. Use the `emails` and `last_names` listt. **Hint: Use `map` and `split`.**
<br>

In [ ]:
import numpy as np

In [ ]:
f_list = [np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]

In [ ]:
text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring.']

In [ ]:
p2_list = [ 2 , 3, 4, 5 ]

In [ ]:
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1 ] 

In [ ]:
# These two lists a
last_and_name = [ "CORNEJO SANCHEZ, CHRISTIAN SANTOS", "ORELLANA QUISPE, CRISTIAN NASSER", "MORALES CHOQUEHUANCA, ANGELICA KARINA", "GUIMARAY RIBEYRO, JOSE ROBERTO", "CAMACHO GAVIDIA, ABEL FERNANDO", "TINTAYA ORIHUELA, MEIR ALVARO", "CHAVEZ MARTINEZ, JOSELIN ALEXANDRA", "FIGUEROA MURO, LEONEL ARTURO", "GOMEZ CRIBILLERO, JOSE FELIPE", "PALOMINO SEGUÍN, AFRANIA", "LUZON CUEVA, BIANCA MARIETTE", "SUAÑA ZEGARRA, ADRIAN ANDRE", "SOTO POMACHAGUA, DORKAS YOMIRA JHERMY", "FIORENTINO MARTINEZ, LADY ALY", "LAMA MAVILA, HECTOR ANDRE", "MEZA HINOJO, GUSTAVO", "LOZADA MURILLO, PERSEO MARCELO", "ZAMBRANO JIMENEZ, MIGUEL ALONZO", "JACOBS LUQUE, NICOLAS", "VIDAL VIDAL, ROCIO GABRIELA", "TORRES ANICAMA, JANE CAMILA", "LOPEZ ESTRADA, MARIA ELISA", "BOYCO ORAMS, ALEJANDRO", "DIAZ BERROSPI, KARLINE ROSMELI", "RIEGA ESCALANTE, STEPHY ROSARIO", "LEVANO TORRES, VALERIA CECILIA", "ESQUIVES BRAVO, SEBASTIAN RENATO", "PEREZ GONZALES, JUAN CARLOS", "OTERO MAGUIÑA, MARIANA", "CLAVO CAMPOS, ANDREA BRIZETH", "AGUILAR GARCIA, ERICK JOSUE", "CALDAS VELASQUEZ, JOSUE DANIEL", "SALAS NUÑEZ BORJA, FABIO MANUEL", "PIZARRO VILLANES, FERNANDA NICOLLE", "QUILLATUPA MORALES, ANGELA ADELINA", "HUANCAYA IDONE, CESAR DANTE", "CALVO PORTOCARRERO, GABRIELA ISABEL", "IBAÑEZ ABANTO, ANGEL MAURICIO", "MELÉNDEZ APONTE, JUAN DIEGO", "CRISTIAN SERRANO, ARONE", "HINOJOSA CAHUANA, PERCY ALBERTH", "ANGLAS GARCÍA, KEVIN ARTURO", "ALDAVE ACOSTA, CESAR ERNESTO", "NÚÑEZ HUAMÁN, CÉSAR AGUSTO", "OBREGON HUAMAN, DIANA EDITH", "SOTO PACHERRES, RODRIGO FRANCO", "INGARUCA RIVERA, GRETTEL ALEXANDRA", "ROJAS HUAMAN, ROSA ANGELA", "NEYRA SALAS, DANTE OMAR", "HUERTA ESPINOZA, YAJAIRA ALEXANDRA", "HUANCA MARTINEZ, JORGE ALBERTO", "FLORES CADILLO, ALEXIS" ]
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe", "", "", "", "", "", "f0873079@pucp.edu.pe", "", "", "", "", "", "", "", "", "", "", "flores.alexis@pucp.edu.pe", ]

52

In [ ]:
## 1.2 List - Resolution

In [ ]:
## 1.2.1 Show the indices of the np.nan values in the f_list list. We want to see this output: 
## The indices 0, 1, 4, 7 have np.nan values. Hint: Use print function and f-strings to insert the indices values.
## Procedure: 

In [ ]:
import pandas as pd

In [ ]:
series = pd.Series(f_list)
series

0         NaN
1         NaN
2     Austria
3     Germany
4         NaN
5    Pakistan
6      np.nan
7         NaN
dtype: object

In [ ]:
indices_Na = series.index[series.isna()]
indices_Na

Index([0, 1, 4, 7], dtype='int64')

In [ ]:
indices = list(indices_Na)
indices

[0, 1, 4, 7]

In [ ]:
## We want to see this output: The indices 0, 1, 4, 7 have np.nan values.

In [ ]:
print(f"The indices {indices[0]}, {indices[1]}, {indices[2]}, {indices[3]} have np.nan values")

The indices 0, 1, 4, 7 have np.nan values


In [ ]:
## 1.2.2 Replicate 4 times the values of the list p2_list. 
## We expect an ouput like this: [ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]. 
## Hint: Use multiplication function in listsand see the output.
## Procedure: To multiply a list by an integer, you simply use the operator *

In [ ]:
p2_list = [ 2 , 3, 4, 5 ]
resultado = p2_list * 4
print(resultado)

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]


In [ ]:
## 1.2.3 Print the length of f_list. Hint: Length function
## Procedure: To be able to obtain the length of a list using the function len

In [ ]:
f_list = [np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]
longitud = len (f_list)
print (longitud)

8


In [ ]:
## 1.2.4 Print My teacher assistant is so boring. using text1 list. Hint: Use the join function
## Procedure: We use " ".join(list) to join the elements of the list into a single string separated by a space " ".

In [ ]:
text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring.']
resultado = " ".join(text1)
print (resultado)

My teacher assistant is so boring.


In [ ]:
## 1.2.5 Print My TA is so boring, but is very funny. using text1 list.Hint: Use the join function, and extend method.
## Procedure: We have used to add multiple items to the end of the list, with extend

In [ ]:
text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring.']
resultado = " ".join(text1)
print (resultado)
text1 = [resultado]
extension = ['My', 'TA is so boring' , "," , 'but is very funny.']
resultado = " ".join(extension)
print (resultado)
extension = [resultado]

text1.extend(extension)
print(text1)

My teacher assistant is so boring.
My TA is so boring , but is very funny.
['My teacher assistant is so boring.', 'My TA is so boring , but is very funny.']


## 1.3 Strings


1. Drop the duplicated blank spaces in `str1`. Do not use the regular expresions. Do not use the code shown in class. Explain your steps.**Hint: Use `split` method and `join` function.**

2. Get the number of letters in the string .**Hint: Use `len`function.**

3. Get the number of blank spaces (all of them) in the string .**Hint: Use `len`function.**

4. Get the position of `@` in each string in the emails list. **Hint: Use `map`function and `find` method.**

5. Identifies if exists `.edu.`  in each string in the `emails` list. Get a list of Booleans. **Hint: Use `map`function and `find` method.**

6. Get all the strings before the first dot `.`in each string in the `emails` list. Identifies how many of them has `@`. **Hint: Use `map`function and `find` method.**

In [ ]:
str1 = 'I am                            too                                                        old'

In [18]:
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe"]

1.3.3 Get the number of blank spaces (all of them) in the string .Hint: Use lenfunction.

In [ ]:
str1 = 'I am                            too                                                        old'
#we calculate the length of str1 using the len function
print(len(str1))
#we use replace to replace blank spaces with no characters so that all characters come together, and we save the new string without blank spaces.
str1_without_espacios = str1.replace(" ", "")
#the characters being together allows counting their number using the len function
print(len(str1_without_espacios))
#the number of blank spaces is the difference between the number of characters in the original string and the number of characters in the new string
blank_spaces = len(str1) - len(str1_without_espacios)
print(f"The number of blank spaces is {blank_spaces}")

1.3.4. Get the position of @ in each string in the emails list. Hint: Use mapfunction and find method.

In [ ]:
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe"]
#the find function allows finding the position of a character in its first occurrence
#define a function positions using find to find the position of '@'.
def positions(email):
    return email.find("@")

#the map function allows applying the find function to each email and obtaining a list of positions.
positions_list = list(map(positions, emails))

print(f"The list of positions of @ is {positions_list}")

1.3.5. Identifies if exists .edu. in each string in the emails list. Get a list of Booleans. Hint: Use mapfunction and find method.

In [ ]:
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe"]
#we define a function edu to determine if .edu exists
def edu(email):
    return ".edu" in email #in allows you to obtain a boolean result, true if .edu is in the string or false if it is not found.

#map allows applying the edu function to each email and obtaining a list of booleans
list_booleans = list(map(edu, emails))

print(f"The list of booleans is {list_booleans}")

1.3.6. Get all the strings before the first dot .in each string in the emails list. Identifies how many of them has @. Hint: Use mapfunction and find method.

In [ ]:
emails = ["cscornejo@pucp.edu.pe", "orellana.cn@pucp.edu.pe", "karina.morales@pucp.edu.pe", "a20083223@pucp.pe", "abel.camacho@pucp.pe", "mtintaya@pucp.edu.pe", "joselin.chavez@pucp.edu.pe", "a20105737@pucp.pe", "jfgomezc@pucp.pe", "afrania.palomino@pucp.pe", "luzon.bianca@pucp.pe", "adrian.suanaz@pucp.pe", "soto.y@pucp.edu.pe", "a20132766@pucp.pe", "andre.lama@pucp.edu.pe", "gustavo.meza@pucp.edu.pe", "pmlozada@pucp.edu.pe", "m.zambranoj@pucp.edu.pe", "nicolas.jacobs@pucp.edu.pe", "gvidal@pucp.edu.pe", "jane.torres@pucp.edu.pe", "m.lopez@pucp.edu.pe", "alejandro.boyco@pucp.edu.pe", "a20167070@pucp.edu.pe", "riega.stephy@pucp.edu.pe", "vlevanot@pucp.edu.pe", "sesquives@pucp.edu.pe", "perez.juanc@pucp.edu.pe", "mariana.otero@pucp.edu.pe", "aclavo@pucp.edu.pe", "a20182474@pucp.edu.pe", "josue.caldas@pucp.edu.pe", "fabio.salas@pucp.edu.pe", "fernanda.pizarro@pucp.edu.pe", "aquillatupa@pucp.pe"]
#we define the function string_dot to find the first dot in the string.
def string_dot(email):
    index_dot = email.find(".")
    return email[:index_dot] #when it finds the first dot, it returns the characters from the initial position up to before the position of the dot

#the map function allows applying the function to each email and obtaining a list of results
list_strings = list(map(string_dot, emails))

#to count how many strings have @, we define the function arroba using the count function
def arroba(email):
    return email.count("@")

#with the map function, we apply the function arroba to each string in list_strings and obtain a list with the count in each string
strings_arroba = list(map(arroba, list_strings))

#with the sum function, we sum all the elements to find out how many strings have an '@' (considering that each string has at most one '@')
final_count = sum(strings_arroba)

print(f"The list of strings before the first dot in each email is {list_strings}")
print(f"The number of strings that have '@' is {final_count}")

## 1.4 Pandas

1. Import this dataset new_up_data_sysdif_block_lvl_ver2.csv located in the `_data` folder.
2. Import this dataset ESA_CLIMATE_CHANGE_tree_layers.csv located in the `_data` folder.
3. Merge both datasets using the key variables `pc11_s_id`,	`pc11_d_id,`	`pc11_sd_id`, `year`. 
4. Generate a descriptive statistics for `per_TREES-BD`, `per_TREES-BE`, `per_TREES-ND`, `per_TREES-NE`.
5. Sum these 4 columns and name the new column as `sum_tree` and get a histogram.
6. Generate the histogram of these 4 columns `per_TREES-BD`, `per_TREES-BE`, `per_TREES-ND`, `per_TREES-NE` for the above and below median dataset filtered by the sum_tree variable.

Do not forget to use relative paths.

##Solution

1.4.1. Import this dataset new_up_data_sysdif_block_lvl_ver2.csv located in the `_data` folder.


In [ ]:
#first, we import pandas
import pandas as pd

#then we use the read_csv function to read a csv file and convert it into a dataframe 
dataset1 = pd.read_csv(r"../_data/new_up_data_sysdif_block_lvl_ver2.csv")