In [1]:
import numpy as np

In [31]:
np.random.seed(123)
students = np.arange( 1, 50 )

In [32]:
original = np.arange( 0 , 49 ).tolist()
results = []

In [33]:
for i in range(10):
    try:
        values = np.random.choice( original, size=5, replace=False)
    except:
        values = np.random.choice( original, size=4, replace=False)
    original = list(set(original).difference(values))
    results.append( values )

In [24]:
import random

def chunks(l, n):
    """Yield successive n-sized chunks from l."""
    for i in range(0, len(l), n):
        yield l[i:i + n]


In [32]:
grupos = list(chunks( np.arange(0, 50), 5))

In [33]:
import pandas as pd

In [34]:
data1 = pd.read_excel( r"C:\Users\Anzony\Downloads\ListaParticipantes_2022 Curso de Capac (1).xls" )

In [35]:
data1['Grupos'] = "" 

i = 1
for gr in grupos:
    data1.iloc[ gr, -1 ] = f"Grupo {i}"
    i = i + 1

In [37]:
data1.iloc[ 50, -1 ] = "Grupo 1"
data1.iloc[ 51, -1 ] = "Grupo 2"

In [67]:
groups = data1.loc[:, [ 'Apellidos y nombres', 'Grupos' ]] \
                .assign(order= data1.groupby(['Grupos']).cumcount()) \
                .pivot( index = ['order'] , columns = ['Grupos']) \
                .replace( np.nan, "") \
                .iloc[:, [0, 2,  3, 4, 5, 6, 7, 8, 9, 1] ]


In [70]:
col1, col2 = zip(*groups.columns)

In [72]:
groups.columns = list(col2)

In [80]:
groups.iloc[:, 0:5].to_html( r"..\_data/groups2022_2_pt1.html", index = False )

In [83]:
groups.iloc[:, 5:10].to_html( r"..\_data/groups2022_2_pt2.html", index = False )

In [23]:
results

[array([13,  9, 22, 18, 42]),
 array([12, 17, 35, 47,  4]),
 array([30, 16, 32,  5, 11]),
 array([20,  2, 19, 43,  3]),
 array([28, 44, 33,  8, 39]),
 array([29, 45, 14, 23,  6]),
 array([38,  1, 27,  7, 48]),
 array([40, 25, 46, 41, 15]),
 array([ 0, 31, 21, 24, 26]),
 array([36, 37, 10, 34])]