In [1]:
import numpy as np

In [31]:
np.random.seed(123)
students = np.arange( 1, 50 )

In [32]:
original = np.arange( 0 , 49 ).tolist()
results = []

In [33]:
for i in range(10):
    try:
        values = np.random.choice( original, size=5, replace=False)
    except:
        values = np.random.choice( original, size=4, replace=False)
    original = list(set(original).difference(values))
    results.append( values )

In [34]:
import pandas as pd

In [35]:
data1 = pd.read_excel( r"C:\Users\Anzony\Downloads\diplomado_pucp.xlsx" )

In [36]:
data1.iloc[results[9] , 2 ]

14    GASTAÑADUY FIESTAS, JESUS EDUARDO
20        VILLENA TAGLE, CLAUDIA ARIANA
34     DE LA CRUZ ORIUNDO, JOSE EDUARDO
1              BALBIN INGA, NOE AUGUSTO
Name: name_last_name, dtype: object

In [23]:
results

[array([13,  9, 22, 18, 42]),
 array([12, 17, 35, 47,  4]),
 array([30, 16, 32,  5, 11]),
 array([20,  2, 19, 43,  3]),
 array([28, 44, 33,  8, 39]),
 array([29, 45, 14, 23,  6]),
 array([38,  1, 27,  7, 48]),
 array([40, 25, 46, 41, 15]),
 array([ 0, 31, 21, 24, 26]),
 array([36, 37, 10, 34])]