In [1]:
import numpy as np

In [3]:
np.random.seed(123)
students = np.arange( 1, 25 )

In [4]:
original = np.arange( 0 , 24 ).tolist()
results = []

In [ ]:
for i in range(10):
    try:
        values = np.random.choice( original, size=5, replace=False)
    except:
        values = np.random.choice( original, size=4, replace=False)
    original = list(set(original).difference(values))
    results.append( values )

In [6]:
import random

def chunks(l, n):
    """Yield successive n-sized chunks from l."""
    for i in range(0, len(l), n):
        yield l[i:i + n]


In [7]:
grupos = list(chunks( np.arange(0, 24), 4))

In [8]:
import pandas as pd

In [9]:
data1 = pd.read_excel( r"C:\Users\Anzony\Downloads\ListaParticipantes_2023 Curso de Capac (2).xls" )

In [14]:
df2 = data1.loc[:, ['Código', 'Apellidos y nombres']].copy()

In [17]:
s = pd.Series([None,None],index=['Código', 'Apellidos y nombres'])

# Appending empty series to df
data1 = df2.append(s,ignore_index=True)

<ipython-input-17-3dfd324ba68f>:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data1 = df2.append(s,ignore_index=True)


In [18]:
data1['Grupos'] = "" 

i = 1
for gr in grupos:
    data1.iloc[ gr, -1 ] = f"Grupo {i}"
    i = i + 1

In [21]:
groups = data1.loc[:, [ 'Apellidos y nombres', 'Grupos' ]] \
                .assign(order= data1.groupby(['Grupos']).cumcount()) \
                .pivot( index = ['order'] , columns = ['Grupos']) \
                .replace( np.nan, "") 


In [22]:
groups

Apellidos y nombres                               \
Grupos                           Grupo 1                      Grupo 2   
order                                                                   
0       ORELLANA QUISPE, CRISTIAN NASSER  SUAÑA ZEGARRA, ADRIAN ANDRE   
1         CAMACHO GAVIDIA, ABEL FERNANDO    LAMA MAVILA, HECTOR ANDRE   
2          TINTAYA ORIHUELA, MEIR ALVARO         MEZA HINOJO, GUSTAVO   
3               PALOMINO SEGUÍN, AFRANIA        JACOBS LUQUE, NICOLAS   

                                                                              \
Grupos                          Grupo 3                              Grupo 4   
order                                                                          
0           VIDAL VIDAL, ROCIO GABRIELA       CALDAS VELASQUEZ, JOSUE DANIEL   
1                BOYCO ORAMS, ALEJANDRO      SALAS NUÑEZ BORJA, FABIO MANUEL   
2       RIEGA ESCALANTE, STEPHY ROSARIO  CALVO PORTOCARRERO, GABRIELA ISABEL   
3           PEREZ GONZALES, JUAN CARLOS        IBAÑEZ ABANTO, ANGEL MAURICIO   

                                                                            
Grupos                         Grupo 5                             Grupo 6  
order                                                                       
0          MELÉNDEZ APONTE, JUAN DIEGO  INGARUCA RIVERA, GRETTEL ALEXANDRA  
1              CRISTIAN SERRANO, ARONE  HUERTA ESPINOZA, YAJAIRA ALEXANDRA  
2           NÚÑEZ HUAMÁN, CÉSAR AGUSTO      HUANCA MARTINEZ, JORGE ALBERTO  
3       SOTO PACHERRES, RODRIGO FRANCO

In [23]:
col1, col2 = zip(*groups.columns)

In [24]:
groups.columns = list(col2)

In [25]:
data1.columns

Index(['Código', 'Apellidos y nombres', 'Grupos'], dtype='object')

In [26]:
data1.loc[:, : ].to_excel(r"C:\Users\Anzony\Downloads/alumnos_diplomado.xlsx", index = False )

In [80]:
groups.iloc[:, 0:5].to_html( r"..\_data/groups2022_2_pt1.html", index = False )

In [27]:
groups.iloc[:, :].to_html( r"C:\Users\Anzony\Documents\GitHub\Diplomado_PUCP/groups2022_2_pt2.html", index = False )

In [23]:
results

[array([13,  9, 22, 18, 42]),
 array([12, 17, 35, 47,  4]),
 array([30, 16, 32,  5, 11]),
 array([20,  2, 19, 43,  3]),
 array([28, 44, 33,  8, 39]),
 array([29, 45, 14, 23,  6]),
 array([38,  1, 27,  7, 48]),
 array([40, 25, 46, 41, 15]),
 array([ 0, 31, 21, 24, 26]),
 array([36, 37, 10, 34])]