## Python
This is a course in python
* Alex
* Maria

In [1]:
15*15

225

In [2]:
print("alex")

alex


# This is python
## This is Diplomado
#### This is PUCP
HI THIS IS MY COURS.S.S.S.S.

# This is the second lecture
## This is the second lecture
#### This is the second lecture

This is the second lecture!

# Titulo 1
## Subtitulo 1 
### Sub3 

# Introduction to Python: Tuples, Lists, Dictionaries, Arrays

## Variables
Containers for store data values. This variable has a label or name. This variable is an object in memory.

### Python Types

There are three key python types: int, float, string and boolean.
Los objetos creados se quedan en la memoria de python.

In [14]:
a = 50 

In [15]:
b = 30.0

In [17]:
a

50

In [18]:
b

30.0

In [19]:
print(a)

50


In [20]:
type(a)

int

In [21]:
b = 30
type(b)

int

In [9]:
c = 30.3
type(c)

float

In [10]:
d = "30"
type(d)

str

In [184]:
a = False
type(a)

bool

### [String](https://www.w3schools.com/python/python_ref_string.asp)
A string is a sequence of characters.

In [13]:
my_string = 'hello15%'
print(my_string)

hello15%


In [15]:
# defining strings in Python
# all of the following are equivalent
my_string = ' ""Hello"" '
print(my_string)

 ""Hello"" 


In [16]:
my_string = "Hello%15#$"
print(my_string , "\n")

Hello%15#$ 



In [18]:
my_string = ''' Hello$%&15 '''
print(my_string , "\n")

 Hello$%&15  



In [29]:
name = "afrania"
name

'afrania'

In [28]:
address_rest = ''' la casa rosada "SBA" ''' 
print(address_rest)

 la casa rosada "SBA" 


In [33]:
my_string = """ Hello, welcome to 
                the world of Python """
print(my_string)

 Hello, welcome to 
                the world of Python 


In [30]:
# triple quotes string can extend multiple lines
my_string = """ Hello, welcome to
the world of Python """
print(my_string)

 Hello, welcome to
the world of Python 


In [39]:
# triple quotes string can extend multiple lines
my_string = '''  Hello, welcome to
           the world of "Python" '''
print(my_string)

  Hello, welcome to
           the world of "Python" 


In [35]:
len(my_string)

48

In [43]:
# import re
# re.sub(' +', ' ', 'The     quick brown    fox')

In [44]:
name = "Jose Felipe"
len(name)

11

In [45]:
"jose gomez             &          empresa manugfacutra"

'jose gomez             &          empresa manugfacutra'

In [47]:
print("the name of the student is Raul")

the name of the student is Raul


In [48]:
# Accessing string characters in Python
## Indexing
str_2 = 'Introduction to Python'

print( "pregunta de heidi" , str_2 , "Luciana pregunta" )

pregunta de heidi Introduction to Python Luciana pregunta


In [49]:
str_1 = "The name"
str_2 = "of the course"
str_3 = "is python"
print(str_1, str_2, str_3)

The name of the course is python


In [51]:
course_name = str_1 + str_2 + str_3
course_name

'The nameof the courseis python'

In [57]:
# Accessing string characters in Python
## Indexing
str = 'Introduction to Python'
print( "pregunta de heidi" + str + "Luciana pregunta" )

pregunta de heidiIntroduction to PythonLuciana pregunta


In [54]:
dir = "C:/Users/Alexander/Dropbox/Pakistan_ID_DIME/Data/Data_requests/"
dir + "data_1"

'C:/Users/Alexander/Dropbox/Pakistan_ID_DIME/Data/Data_requests/data_1'

In [55]:
dir + "data_2"

'C:/Users/Alexander/Dropbox/Pakistan_ID_DIME/Data/Data_requests/data_2'

In [56]:
# C:/Users/Alexander/Dropbox/Pakistan ID DIME/Data/Data requests/data_1
# C:/Users/Alexander/Dropbox/Pakistan ID DIME/Data/Data requests/data_2
# C:/Users/Alexander/Dropbox/Pakistan ID DIME/Data/Data requests/data_3    

In [59]:
str = "Introduction to Python"
str

'Introduction to Python'

In [64]:
str[10]

'o'

In [195]:
str[0]

'I'

In [65]:
#first character
print('str[0] = ', str[0])

str[0] =  I


In [197]:
str = 'Introduction to Python'

In [68]:
str[-2]

'o'

In [69]:
str[-6]

'P'

In [198]:
#last character
print(str[-2])

o


In [71]:
str = 'Introduction to Python'

In [72]:
#slicing 2nd to 5th character
print(str[1:5])

ntro


In [73]:
#slicing 6th to 2nd last character
print(str[5:-2])

duction to Pyth


### [Bool](https://www.w3schools.com/python/python_booleans.asp)

The Python Boolean type is one of Python’s built-in data types. It’s used to represent the truth value of an expression. For example, the expression 1 <= 2 is True, while the expression 0 == 1 is False. 

In [75]:
response = print(10 > 9)
response

True


In [76]:
print(10 == 9)

False


In [77]:
print(10 < 9)

False


In [86]:
name = "alexander"
name

'alexander'

In [89]:
True == 1

True

In [83]:
True == 1

True

In [79]:
False == 0

True

In [80]:
False == 1

False

In [84]:
True + (False / True)

1.0

## [Tuple](https://www.datacamp.com/community/tutorials/python-tuples-tutorial?utm_source=adwords_ppc&utm_medium=cpc&utm_campaignid=1455363063&utm_adgroupid=65083631748&utm_device=c&utm_keyword=&utm_matchtype=b&utm_network=g&utm_adpostion=&utm_creative=278443377092&utm_targetid=dsa-429603003980&utm_loc_interest_ms=&utm_loc_physical_ms=9060932&gclid=CjwKCAiAvriMBhAuEiwA8Cs5lSzvIp9Hmu0C0HearAmYt_xmqCwjL-nbi0j1e-WlDcBcm2owtmfvGBoCjhEQAvD_BwE)
It is an ordered and unchangeable Python container. We cannot change, add or remove items after the tuple has been created. Tuple items are ordered, unchangeable, and allow duplicate values.

In [92]:
# tuple1 = (1, 2, 5, 9, 10, 10)
# tuple1

(1, 2, 5, 9, 10, 10)

In [4]:
# name_st = "Adriana Sierra"
# name_st[1]

'd'

In [8]:
tuple_0 = (1, 10.5, "alex", True, False)

In [9]:
tuple_0[3]

True

In [ ]:
# (25, 10.5, "alex", True, False)

In [7]:
# tuple_0[0] = 25

TypeError: 'tuple' object does not support item assignment

In [96]:
tuple1 = (1, 3, 3, 5, 10)
tuple1[3]

5

In [97]:
tuple1[0] = 15

TypeError: 'tuple' object does not support item assignment

| Method 	| Definition 	|
|---	|---	|
| count() | Returns the number of times <br> a specified value occurs in a tuple 	|
| index() |	Searches the tuple for a specified value <br> and returns the position of where it was found 	|


In [12]:
tuple1 = (1, 3, 3, 5, 10, 5, 5)

In [16]:
tuple1.count(10)

1

In [14]:
tuple1.count(3)

2

In [106]:
# count
#print( tuple1 )
tuple1.count( 5 )

3

In [17]:
# index
print( tuple1 )
tuple1.index( 3 )

(1, 3, 3, 5, 10, 5, 5)


1

In [108]:
tuple1.index( 3 )

1

| Function 	| Definition 	|
| --- 	| --- 	|
| type(tuple) 	| It returns the class type of an object. 	|
| max(tuple) 	| It returns an item from the tuple with max value. 	|
| min(tuple) 	| It returns an item from the tuple with min value. 	|
| len(tuple) 	| It gives the total length of the tuple. 	|
| tuple( list ) 	| Converts a list into a tuple. 	|

In [51]:
tuple_p3 = (1, 8, 18, 28, 39, 8)
print( type(tuple_p3) )
print( max(tuple_p3) )
print( min(tuple_p3) )
print( len(tuple_p3) )

<class 'tuple'>
39
1
6


In [53]:
# tuple_p3.sort()

In [25]:
tuple_p3.index(8)

1

In [110]:
tuple1 = ( 1, 3, 3, 5, 10, (5, 6, 7) )
print(tuple1)

(1, 3, 3, 5, 10, (5, 6, 7))


In [111]:
tuple1 = ("alex", 5, True)
tuple1

('alex', 5, True)

In [113]:
len(tuple1[0])

4

In [117]:
tuple1 = ( 1, 2, 3, 4, 5, 10 )

In [118]:
# Max value
print( max(tuple1) )

10


In [119]:
print( min(tuple1) )

1


In [120]:
# Length
print( len(tuple1) )

6


In [ ]:
# # Min value
# print( min(tuple1) )

In [ ]:
# a = [2 , 3, 4]
# print( type( a ) )

In [ ]:
# b = tuple(a)
# print( type( b ) )
# print( b )

In [ ]:
# c = list(b)
# c

## [Lists](https://www.freecodecamp.org/news/lists-in-python-comprehensive-guide/)
It is an ordered and mutable Python container. Its itmes are orderd, changeable, and allow duplicate values and different type of objects. Finally, every item has index because lists have a defined order.

| Method 	| Definition 	|
|---	|---	|
| sort() 	| Sorts the list in ascending order. 	|
| append() 	| Adds a single element to a list. <br> This element will be located at the end of the list. 	|
| extend() 	| Adds multiple elements to a list. 	|
| index() 	| Returns the first appearance of the specified value. 	|


In [43]:
sort(stud_list)

In [44]:
stud_list.

In [58]:
stud_list_str = ["manuel", "julian", "jenny", "roy"]
print(stud_list_str)

['manuel', 'julian', 'jenny', 'roy']


In [59]:
stud_list_str.sort()
print(stud_list_str)

['jenny', 'julian', 'manuel', 'roy']


In [64]:
stud_list_age = [30, 45, 28, 32]
print(stud_list_age)
stud_list_age.sort()
print(stud_list_age)

[30, 45, 28, 32]
[28, 30, 32, 45]


In [40]:
person_1 = ["manuel", 30, True, 5.4, "Soto"]
person_1[-1]

'Soto'

In [121]:
a_0 = [18, 1.36, "alex", False]
a_0 

[18, 1.36, 'alex', False]

In [122]:
# We use brackets to create a list
a = [ 18, 20 , 30, "alex" ]

print( type( a ) )

<class 'list'>


In [126]:
a[-1]

'alex'

In [123]:
print(  a[-1] )

alex


In [127]:
# b_sort = b
# b_sort2 = b.copy()

AttributeError: 'int' object has no attribute 'copy'

In [ ]:
# id(b_sort)

In [ ]:
# id(b_sort2)

In [129]:
b = [ 3, 13, 2, 56, 76, 16]
b

[3, 13, 2, 56, 76, 16]

In [130]:
b_sort = b.copy()
b_sort

[3, 13, 2, 56, 76, 16]

In [131]:
# b = [ 3, 13, 2, 56, 76, 16]
# b_sort = b.copy()
# b

In [134]:
b_sort.sort()
b_sort

[2, 3, 13, 16, 56, 76]

In [140]:
grades= [15, 20, 16, 5, 8 ]
grades

[15, 20, 16, 5, 8]

In [143]:
grades.sort()
grades

[5, 8, 15, 16, 20]

In [ ]:
print(b)

In [ ]:
print(b_sort)

In [ ]:
b_sort = b
b_sort

In [65]:
b = [ 3, 13, 2, 56, 76, 16]
b

[3, 13, 2, 56, 76, 16]

In [81]:
b = [ 3, 13, 2, 56, 76, 16]
b.append( 80 )
b

[3, 13, 2, 56, 76, 16, 80]

In [78]:
a = [ 19, 25, 76 ]
a

[19, 25, 76]

In [79]:
a.extend(b)

In [80]:
a

[19, 25, 76, 3, 13, 2, 56, 76, 16, 'Armando']

In [148]:
a.extend( b )

In [149]:
a

[19, 25, 76, 3, 13, 2, 56, 76, 16, 87]

In [154]:
print(a.index(76))

2


In [150]:
b = [ 3, 13, 2, 56, 76, 16]
a = [ 19, 25, 76 ] 

In [151]:
b.extend( a )
b

[3, 13, 2, 56, 76, 16, 19, 25, 76]

In [153]:
# Python uses 0-based indexing
print( b.index( 76 ) )

4


| Function 	| Definition 	|
| --- 	| --- 	|
| type(list) 	| It returns the class type of an object. 	|
| max(list) 	| It returns an item from the list with max value. 	|
| min(list) 	| It returns an item from the list with min value. 	|
| len(list) 	| It gives the total length of the list. 	|
| list(seq) 	| Converts a tuple into a list. 	|

In [92]:
b

[3, 13, 2, 56, 76, 16, 80]

In [90]:
print(max(b))
print(min(b))
print(len(b))

80
2
7


In [86]:
print( max(b) )
print( min(b) )
print( len(b) )

80
2
7


In [155]:
# type of object
print( b )
print( type( b ) )

[3, 13, 2, 56, 76, 16, 19, 25, 76]
<class 'list'>


In [158]:
# max
print( b )
print( max( b ) )

[3, 13, 2, 56, 76, 16, 19, 25, 76]
76


In [159]:
# min
print( b )
print( min( b ) )

[3, 13, 2, 56, 76, 16, 19, 25, 76]
2


In [160]:
# length of a list
print( b )
print( len( b ) )

[3, 13, 2, 56, 76, 16, 19, 25, 76]
9


In [ ]:
# # length of a list
# a = ( 4 , 6 )
# print( a )
# print( type( a ) )

In [ ]:
# c = list( a )
# print( c )
# print( type( c ) )

In [ ]:
# id(c)

In [ ]:
# id(a)

## [Dictionaries](https://realpython.com/python-dicts/)

It is a ordered (Python >= 3.7) and mutable Python container. It does not allow duplicate key. They must be unique.

| Method 	| Definition 	|
| --- 	| --- 	|
|clear()|	Removes all the elements from the dictionary|
|copy() |	Returns a copy of the dictionary|
|fromkeys() |	Returns a dictionary with the specified keys and value|
|get() |	Returns the value of the specified key|
|items() |	Returns a list containing a tuple for each key value pair|
|keys() | Returns a list containing the dictionary's keys|
|pop() | Removes the element with the specified key|
|popitem() | Removes the last inserted key-value pair|
|setdefault() | Returns the value of the specified key. <br> If the key does not exist: insert the key, with the specified value|
|update() |	Updates the dictionary with the specified key-value pairs |
|values() | Returns a list of all the values in the dictionary|

In [105]:
# samuel = { "Samuel", "Rivero", 25 }
# samuel.keys()

In [104]:
samuel = { "name":"Samuel", "lastname": "Rivero", "age":25, "birth_place":"chimbote", "male":True }
samuel

{'name': 'Samuel',
 'lastname': 'Rivero',
 'age': 25,
 'birth_place': 'chimbote',
 'male': True}

In [108]:
samuel.keys()

dict_keys(['name', 'lastname', 'age', 'birth_place', 'male'])

In [112]:
samuel["birth_place"]

'chimbote'

In [11]:
alexander = { 'lastname': "Quispe,", 'age': 28, 'birth_place': "SJL", 'male' : True}
maria = { 'lastname': "rojas", 'age': 27, 'birth_place': "SMP", 'male' : False}

alexander

{'lastname': 'Quispe', 'age': 28, 'birth_place': 'SJL', 'male': True}

In [30]:
lastanme = ["Quispe", "Rojas", "Rodriguez"]
ages = [28, 29, 30]

In [39]:
list_1 = { "lastname" : ["Quispe", "Rojas", "Rodriguez"],
          "ages":[28, 29, 30], "birth_place": "SJL", 'male' : True}
list_1["lastname"]

['Quispe', 'Rojas', 'Rodriguez']

In [12]:
alexander["male"]

True

In [124]:
# dictionary containing the population of the 5 largest german cities
population = {'Berlin': 3748148, 'Hamburg': 1822445, 
              'Munich': 1471508, 'Cologne': 1085664, 
              'Frankfurt': 753056 }

In [125]:
# clear
print( population )
type( population )

{'Berlin': 3748148, 'Hamburg': 1822445, 'Munich': 1471508, 'Cologne': 1085664, 'Frankfurt': 753056}


dict

In [126]:
print("this is pre clear : ", population)
population.clear()
print("this is after clear : ", population)

this is pre clear :  {'Berlin': 3748148, 'Hamburg': 1822445, 'Munich': 1471508, 'Cologne': 1085664, 'Frankfurt': 753056}
this is after clear :  {}


In [118]:
print(population)

{}


In [ ]:
population.clear()
print( population )

In [137]:
population = {'Berlin': 3748148, 'Hamburg': 1822445, 
              'Munich': 1471508, 'Cologne': 1085664, 
              'Frankfurt': 753056}
population

{'Berlin': 3748148,
 'Hamburg': 1822445,
 'Munich': 1471508,
 'Cologne': 1085664,
 'Frankfurt': 753056}

In [131]:
pop_2 = population.copy()
pop_2

{'Berlin': 3748148,
 'Hamburg': 1822445,
 'Munich': 1471508,
 'Cologne': 1085664,
 'Frankfurt': 753056}

In [138]:
# population.clear()
# population

In [139]:
population["Berlin"]

3748148

In [141]:
# Get information from key
population.get('Berlin')

3748148

In [143]:
population

{'Berlin': 3748148,
 'Hamburg': 1822445,
 'Munich': 1471508,
 'Cologne': 1085664,
 'Frankfurt': 753056}

In [142]:
# Get information from key
population.items()

dict_items([('Berlin', 3748148), ('Hamburg', 1822445), ('Munich', 1471508), ('Cologne', 1085664), ('Frankfurt', 753056)])

In [144]:
population.keys()

dict_keys(['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt'])

In [145]:
population.pop("Frankfurt")

753056

In [147]:
population.pop("Hamburg")

1822445

In [148]:
population

{'Berlin': 3748148, 'Munich': 1471508, 'Cologne': 1085664}

In [151]:
stadiums = { "munich":"Alianz Arena","dormundt": "SIP", "ulm": "VFLULM", "shalke": "GAZPROM"}
print(stadiums)
stadiums.pop("munich")
print(stadiums)

{'munich': 'Alianz Arena', 'dormundt': 'SIP', 'ulm': 'VFLULM', 'shalke': 'GAZPROM'}
{'dormundt': 'SIP', 'ulm': 'VFLULM', 'shalke': 'GAZPROM'}


In [67]:
population.update( {"stadiums": stadiums} )
type(population["stadiums"])

dict

In [68]:
population

{'Berlin': 3748148,
 'Hamburg': 1822445,
 'Munich': 1471508,
 'Cologne': 1085664,
 'stadiums': {'munich': 'Alianz Arena',
  'dormundt': 'SIP',
  'ulm': 'VFLULM',
  'shalke': 'GAZPROM'}}

In [ ]:
# Drop a key
print( population )
population.pop( 'Hamburg' )
print( population )

In [ ]:
population

In [ ]:
# Drop an item
population.popitem( )
print( population )

In [ ]:
population

In [69]:
population.update( { "Bonn" :  327258 } )
population.update( { "Ulm" : 100000  } )
population

{'Berlin': 3748148,
 'Hamburg': 1822445,
 'Munich': 1471508,
 'Cologne': 1085664,
 'stadiums': {'munich': 'Alianz Arena',
  'dormundt': 'SIP',
  'ulm': 'VFLULM',
  'shalke': 'GAZPROM'},
 'Bonn': 327258,
 'Ulm': 100000}

In [70]:
# Add new items
print( population )
population.update( { "Bonn" :  {"population":100 , "km2" : 500, "president" : "Anzony"} } )
print( population )

{'Berlin': 3748148, 'Hamburg': 1822445, 'Munich': 1471508, 'Cologne': 1085664, 'stadiums': {'munich': 'Alianz Arena', 'dormundt': 'SIP', 'ulm': 'VFLULM', 'shalke': 'GAZPROM'}, 'Bonn': 327258, 'Ulm': 100000}
{'Berlin': 3748148, 'Hamburg': 1822445, 'Munich': 1471508, 'Cologne': 1085664, 'stadiums': {'munich': 'Alianz Arena', 'dormundt': 'SIP', 'ulm': 'VFLULM', 'shalke': 'GAZPROM'}, 'Bonn': {'population': 100, 'km2': 500, 'president': 'Anzony'}, 'Ulm': 100000}


In [71]:
population.keys()

dict_keys(['Berlin', 'Hamburg', 'Munich', 'Cologne', 'stadiums', 'Bonn', 'Ulm'])

In [74]:
# Get all values from all keys
population.values()

dict_values([3748148, 1822445, 1471508, 1085664, {'munich': 'Alianz Arena', 'dormundt': 'SIP', 'ulm': 'VFLULM', 'shalke': 'GAZPROM'}, {'population': 100, 'km2': 500, 'president': 'Anzony'}, 100000])

In [78]:
population["stadiums"].get("shalke")

'GAZPROM'

#### From lists to dictionaries

In [152]:
# postal_code

In [153]:
# list_2 = list(set(postal_code))

In [158]:
cities_postal = {"Fray Martin":15001, 'Santa Rosa de Puquio':15003}
cities_postal["Santa Rosa de Puquio"]

15003

In [160]:
# keys
cities = ['Fray Martin','Santa Rosa de Puquio','Cuchicorral','Santiago de Punchauca',
          'La Cruz (11 Amigos)','Cerro Cañon','Cabaña Suche','San Lorenzo',
          'Jose Carlos Mariategui','Pascal','La Esperanza','Fundo Pancha Paula','Olfa',
          'Rio Seco','Paraiso','El Rosario','Cerro Puquio','La Campana','Las Animas',
          'Vetancio','Roma Alta','San Jose','San Pedro de Carabayllo','Huacoy',
          'Fundo Pampa Libre','Ex Fundo Santa Ines','Reposo','Carmelito','Santa Elena',
          'Don Luis','Santa Ines Parcela','Asociacion Santa Ines','Roma Baja',
          'Residencial Santa Lucia','San Francisco','Santa Margarita - Molinos',
          'Sipan Peru','Fundo Cuadros','Bello Horizonte','El Hueco','Ex Fundo Mariategui',
          'Naranjito','Vista Hermosa','El Sabroso de Jose Carlos Mariategui','Granja Carabayllo',
          'Agropecuario Valle el Chillon','Camino Real','Copacabana','El Trebol','Tablada la Virgen',
          'San Fernando de Carabayllo','San Fernando de Copacabana','La Manzana','Chacra Grande',
          'Torres de Copacabana','San Pedro de Carabayllo','San Lorenzo','Chaclacayo','Chorrillos',
          'Cieneguilla','Lindero','Pichicato','San Isidro','San Vicente','Piedra Liza',
          'Santa Rosa de Chontay (Chontay)','La Libertad','El Agustino','Independencia',
          'Jesus Maria','La Molina','La Victoria','Lince','Las Palmeras','Chosica','Lurin',
          'Los Almacigos','Rinconada del Puruhuay','Fundo Santa Genoveva','Los Maderos','Casco Viejo',
          'Vista Alegre','Buena Vista Alta','Lomas Pucara','Fundo la Querencia','Magdalena del Mar','Pueblo Libre','Miraflores','Pachacamac','Puente Manchay','Tambo Inga','Pampa Flores','Manchay Alto Lote B','Invasion Cementerio','Manchay Bajo','Santa Rosa de Mal Paso','Cardal','Jatosisa','Tomina','Pucusana','Honda','Quipa','Los Pelicanos','Playa Puerto Bello','Ñaves','Granja Santa Elena','Alvatroz II','Poseidon - Lobo Varado','Playa Minka Mar','Playa Acantilado','Puente Piedra','Punta Hermosa','Capilla Lucumo','Cucuya','Pampapacta','Avicola San Cirilo de Loma Negra - 03','Avicola San Cirilo de Loma Negra - 02','Avicola San Cirilo de Loma Negra - 01','Pampa Mamay','Cerro Botija','Agricultores y Ganaderos','Pampa Malanche Avicola Puma','Punta Negra','Chancheria','Rimac','San Bartolo','Plantel 41','Granja 4','Granja 5','Granja 07','Granja 44','Granja 47','Santa Maria I','Las Torres Santa Fe','San Francisco de Borja','San Isidro','San Juan de Lurigancho','Ciudad de Dios','San Luis','Barrio Obrero Industrial','San Miguel','Santa Anita - los Ficus','Santa Maria del Mar','Don Bruno','Santa Rosa','Santiago de Surco','Surquillo','Villa el Salvador','Villa Maria del Triunfo', 'Pueblo libre']
# values
postal_code = [15001,15003,15004,15006,15018,15019,15046,15072,15079,15081,15082,15083,15088,15123,15004,15011,15012,15019,15022,15023,15026,15476,15479,15483,15487,15491,15494,15498,15047,15049,15063,15082,15083,15121,15122,15313,15316,15318,15319,15320,15321,15324,15320,15320,15320,15320,15320,15320,15121,15320,15320,15121,15320,15320,15121,15121,15122,15122,15121,15121,15121,15320,15320,15320,15320,15320,15320,15121,15121,15121,15320,15121,15319,15121,15121,15121,15320,15320,15121,15121,15121,15121,15320,15320,15320,15122,15122,15122,15122,15122,15122,15122,15122,15121,15121,15122,15122,15121,15121,15122,15122,15121,15122,15122,15122,15472,15476,15054,15056,15057,15058,15063,15064,15066,15067,15593,15594,15593,15593,15593,15593,15593,15593,15593,15311,15312,15313,15314,15316,15324,15326,15327,15328,15332,15003,15004,15006,15007,15008,15009,15011,15018,15022,15311,15328,15331,15332,15333,15046, 15001]

In [187]:
len(cities)

150

In [162]:
len(postal_code)

150

In [180]:
# list()

In [198]:
list_cities =  list(zip(cities, postal_code))
fr_mar =  list_cities[0]
fr_mar[0] = "Callao"

TypeError: 'tuple' object does not support item assignment

In [194]:
list_cities[0] = "Mauricio"
list_cities

['Mauricio',
 ('Santa Rosa de Puquio', 15003),
 ('Cuchicorral', 15004),
 ('Santiago de Punchauca', 15006),
 ('La Cruz (11 Amigos)', 15018),
 ('Cerro Cañon', 15019),
 ('Cabaña Suche', 15046),
 ('San Lorenzo', 15072),
 ('Jose Carlos Mariategui', 15079),
 ('Pascal', 15081),
 ('La Esperanza', 15082),
 ('Fundo Pancha Paula', 15083),
 ('Olfa', 15088),
 ('Rio Seco', 15123),
 ('Paraiso', 15004),
 ('El Rosario', 15011),
 ('Cerro Puquio', 15012),
 ('La Campana', 15019),
 ('Las Animas', 15022),
 ('Vetancio', 15023),
 ('Roma Alta', 15026),
 ('San Jose', 15476),
 ('San Pedro de Carabayllo', 15479),
 ('Huacoy', 15483),
 ('Fundo Pampa Libre', 15487),
 ('Ex Fundo Santa Ines', 15491),
 ('Reposo', 15494),
 ('Carmelito', 15498),
 ('Santa Elena', 15047),
 ('Don Luis', 15049),
 ('Santa Ines Parcela', 15063),
 ('Asociacion Santa Ines', 15082),
 ('Roma Baja', 15083),
 ('Residencial Santa Lucia', 15121),
 ('San Francisco', 15122),
 ('Santa Margarita - Molinos', 15313),
 ('Sipan Peru', 15316),
 ('Fundo Cuadros

In [182]:
list(zip( cities , postal_code ))

[('Fray Martin', 15001),
 ('Santa Rosa de Puquio', 15003),
 ('Cuchicorral', 15004),
 ('Santiago de Punchauca', 15006),
 ('La Cruz (11 Amigos)', 15018),
 ('Cerro Cañon', 15019),
 ('Cabaña Suche', 15046),
 ('San Lorenzo', 15072),
 ('Jose Carlos Mariategui', 15079),
 ('Pascal', 15081),
 ('La Esperanza', 15082),
 ('Fundo Pancha Paula', 15083),
 ('Olfa', 15088),
 ('Rio Seco', 15123),
 ('Paraiso', 15004),
 ('El Rosario', 15011),
 ('Cerro Puquio', 15012),
 ('La Campana', 15019),
 ('Las Animas', 15022),
 ('Vetancio', 15023),
 ('Roma Alta', 15026),
 ('San Jose', 15476),
 ('San Pedro de Carabayllo', 15479),
 ('Huacoy', 15483),
 ('Fundo Pampa Libre', 15487),
 ('Ex Fundo Santa Ines', 15491),
 ('Reposo', 15494),
 ('Carmelito', 15498),
 ('Santa Elena', 15047),
 ('Don Luis', 15049),
 ('Santa Ines Parcela', 15063),
 ('Asociacion Santa Ines', 15082),
 ('Roma Baja', 15083),
 ('Residencial Santa Lucia', 15121),
 ('San Francisco', 15122),
 ('Santa Margarita - Molinos', 15313),
 ('Sipan Peru', 15316),
 ('F

In [183]:
cities_postal = dict(zip( cities , postal_code ))
cities_postal

{'Fray Martin': 15001,
 'Santa Rosa de Puquio': 15003,
 'Cuchicorral': 15004,
 'Santiago de Punchauca': 15006,
 'La Cruz (11 Amigos)': 15018,
 'Cerro Cañon': 15019,
 'Cabaña Suche': 15046,
 'San Lorenzo': 15122,
 'Jose Carlos Mariategui': 15079,
 'Pascal': 15081,
 'La Esperanza': 15082,
 'Fundo Pancha Paula': 15083,
 'Olfa': 15088,
 'Rio Seco': 15123,
 'Paraiso': 15004,
 'El Rosario': 15011,
 'Cerro Puquio': 15012,
 'La Campana': 15019,
 'Las Animas': 15022,
 'Vetancio': 15023,
 'Roma Alta': 15026,
 'San Jose': 15476,
 'San Pedro de Carabayllo': 15121,
 'Huacoy': 15483,
 'Fundo Pampa Libre': 15487,
 'Ex Fundo Santa Ines': 15491,
 'Reposo': 15494,
 'Carmelito': 15498,
 'Santa Elena': 15047,
 'Don Luis': 15049,
 'Santa Ines Parcela': 15063,
 'Asociacion Santa Ines': 15082,
 'Roma Baja': 15083,
 'Residencial Santa Lucia': 15121,
 'San Francisco': 15122,
 'Santa Margarita - Molinos': 15313,
 'Sipan Peru': 15316,
 'Fundo Cuadros': 15318,
 'Bello Horizonte': 15319,
 'El Hueco': 15320,
 'Ex F

In [184]:
cities_postal["Camino Real"]

15320

In [185]:
# Return a dictionarie
ct_pc = dict( zip( cities , postal_code ) )

In [199]:
ct_pc

{'Fray Martin': 15001,
 'Santa Rosa de Puquio': 15003,
 'Cuchicorral': 15004,
 'Santiago de Punchauca': 15006,
 'La Cruz (11 Amigos)': 15018,
 'Cerro Cañon': 15019,
 'Cabaña Suche': 15046,
 'San Lorenzo': 15122,
 'Jose Carlos Mariategui': 15079,
 'Pascal': 15081,
 'La Esperanza': 15082,
 'Fundo Pancha Paula': 15083,
 'Olfa': 15088,
 'Rio Seco': 15123,
 'Paraiso': 15004,
 'El Rosario': 15011,
 'Cerro Puquio': 15012,
 'La Campana': 15019,
 'Las Animas': 15022,
 'Vetancio': 15023,
 'Roma Alta': 15026,
 'San Jose': 15476,
 'San Pedro de Carabayllo': 15121,
 'Huacoy': 15483,
 'Fundo Pampa Libre': 15487,
 'Ex Fundo Santa Ines': 15491,
 'Reposo': 15494,
 'Carmelito': 15498,
 'Santa Elena': 15047,
 'Don Luis': 15049,
 'Santa Ines Parcela': 15063,
 'Asociacion Santa Ines': 15082,
 'Roma Baja': 15083,
 'Residencial Santa Lucia': 15121,
 'San Francisco': 15122,
 'Santa Margarita - Molinos': 15313,
 'Sipan Peru': 15316,
 'Fundo Cuadros': 15318,
 'Bello Horizonte': 15319,
 'El Hueco': 15320,
 'Ex F

In [200]:
ct_pc["Fray Martin"] = 2000

In [201]:
ct_pc

{'Fray Martin': 2000,
 'Santa Rosa de Puquio': 15003,
 'Cuchicorral': 15004,
 'Santiago de Punchauca': 15006,
 'La Cruz (11 Amigos)': 15018,
 'Cerro Cañon': 15019,
 'Cabaña Suche': 15046,
 'San Lorenzo': 15122,
 'Jose Carlos Mariategui': 15079,
 'Pascal': 15081,
 'La Esperanza': 15082,
 'Fundo Pancha Paula': 15083,
 'Olfa': 15088,
 'Rio Seco': 15123,
 'Paraiso': 15004,
 'El Rosario': 15011,
 'Cerro Puquio': 15012,
 'La Campana': 15019,
 'Las Animas': 15022,
 'Vetancio': 15023,
 'Roma Alta': 15026,
 'San Jose': 15476,
 'San Pedro de Carabayllo': 15121,
 'Huacoy': 15483,
 'Fundo Pampa Libre': 15487,
 'Ex Fundo Santa Ines': 15491,
 'Reposo': 15494,
 'Carmelito': 15498,
 'Santa Elena': 15047,
 'Don Luis': 15049,
 'Santa Ines Parcela': 15063,
 'Asociacion Santa Ines': 15082,
 'Roma Baja': 15083,
 'Residencial Santa Lucia': 15121,
 'San Francisco': 15122,
 'Santa Margarita - Molinos': 15313,
 'Sipan Peru': 15316,
 'Fundo Cuadros': 15318,
 'Bello Horizonte': 15319,
 'El Hueco': 15320,
 'Ex Fu

### Excersises
1. Write a Python script to check whether Lima is a key of ct_pc.
2. Write a Python script to join two Python dictionaries.
3. Write a Python script to add a key to a dictionary.

## [Numpy](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

### Arrays
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [202]:
import numpy as np

In [211]:
# [1, 2, 3, 4, 5]

In [212]:
a = np.array( [1, 2, 3, 4, 5] )

In [214]:
a

array([1, 2, 3, 4, 5])

In [207]:
# 1D array
a = np.array( [1, 2, 3, 4, 5] )
print(a)

[1 2 3 4 5]


In [243]:
# 2D array
M = np.array( [ [1, 2, 3, 5], [4, 5, 6, 10], [4, 5, 6, 10] ] )

print(M)

[[ 1  2  3  5]
 [ 4  5  6 10]
 [ 4  5  6 10]]


In [245]:
X = np.array( [ [1, 2, 3], [4, 5, 7] ] )
X.shape

(2, 3)

|Function|	Description|
| --- |--- |
|np.array(a) |	Create -dimensional np array from sequence a|
|np.linspace(a,b,N) |	Create 1D np array with N equally spaced values <br> from a to b (inclusively)|
|np.arange(a,b,step) |	Create 1D np array with values from a to b (exclusively) <br> incremented by step|
|np.zeros(N)	| Create 1D np array of zeros of length |
|np.zeros((n,m)) |	Create 2D np array of zeros with  rows and  columns|
|np.ones(N) |	Create 1D np array of ones of length |
|np.ones((n,m))|	Create 2D np array of ones with  rows and  columns|
|np.eye(N)	| Create 2D np array with  rows and  columns  <br> with ones on the diagonal  (ie. the identity matrix of size )|
|np.concatenate( )|Join a sequence of arrays along an existing axis|
|np.hstack( )|Stack arrays in sequence horizontally(column wise)|
|np.vstack( )|Stack arrays in sequence vertically(row wise)|
|np.column_stack( )|Stack 1-D arrays as columns into a 2-D array|
|np.random.normal() | Draw random samples from a normal (Gaussian) distribution. |
|np.linalg.inv() | Compute the (multiplicative) inverse of a matrix. |
|np.dot() / @  | Matrix Multiplication. |

In [220]:
# Create a 1D NumPy array with 11 equally spaced values from 0 to 1:
x = np.linspace( 0, 100, 11 )
print(x)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [224]:
# Create a 1D NumPy array with values from 0 to 20 (exclusively) incremented by 5:
y = np.arange( 0, 20, 1 )
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [226]:
# Create a 1D NumPy array of zeros of length 5:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [228]:
# Create a 2D NumPy array of zeros of shape ( 5, 10 ) :
M = np.zeros( (5, 10) )
print(M)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [236]:
M.shape

(5, 10)

In [230]:
# Create a 1D NumPy array of ones of length 7:
w = np.ones(10)
print(w)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [231]:
# Create a 2D NumPy array of ones with 35ows and 25 columns:
N = np.ones( (5, 5) )
print(N)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [234]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [235]:
# Create the identity matrix of size 10:
I = np.eye(10)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [250]:
print(I.shape)
print(I.size)

(10, 10)
100


In [114]:
# Shape
print( I.shape )

(10, 10)


In [116]:
# Size
print(I.size)

100


In [251]:
# Concateante
g = np.array([[5,6],[7,8]])
g

array([[5, 6],
       [7, 8]])

In [253]:
h = np.array([[1,2]])
h

array([[1, 2]])

In [254]:
print(g, "\n")
print(h , "\n")

[[5 6]
 [7 8]] 

[[1 2]] 



In [257]:
g.shape

(2, 2)

In [258]:
h.shape

(1, 2)

In [262]:
g_h_0 = np.concatenate( (g, h), axis = 0)
g_h_0

array([[5, 6],
       [7, 8],
       [1, 2]])

In [264]:
h_resh =  h.reshape(2, 1)

In [265]:
g_h_1 = np.concatenate( (g, h_resh), axis = 1)
g_h_1

array([[5, 6, 1],
       [7, 8, 2]])

In [266]:
wage_1 = np.array( [[10,12],[7,8]] )
wage_2 = np.array( [[12,15]] )

In [267]:
wage_1.shape

(2, 2)

In [268]:
wage_2.shape

(1, 2)

In [269]:
wages_0 = np.concatenate( (wage_1, wage_2) , axis=0)
wages_0

array([[10, 12],
       [ 7,  8],
       [12, 15]])

In [273]:
wage_2_re =  wage_2.reshape(2, 1)
wage_2_re

array([[12],
       [15]])

In [274]:
wages_1 = np.concatenate( (wage_1, wage_2_re) , axis=1)
wages_1

array([[10, 12, 12],
       [ 7,  8, 15]])

In [128]:
h_2 = h.reshape(2, 1)
h_2

array([[1],
       [2]])

In [130]:
g

array([[5, 6],
       [7, 8]])

In [131]:
g_h = np.concatenate((g, h_2), axis = 1)
g_h

array([[5, 6, 1],
       [7, 8, 2]])

In [ ]:
h_2 = h.reshape(2, 1)
h_2

In [132]:
jesus = np.hstack((g,h_2))
jesus

array([[5, 6, 1],
       [7, 8, 2]])

In [133]:
# vstack 
x = np.array([1,1,1])
y = np.array([2,2,2])
z = np.array([3,3,3])

array([3, 3, 3])

In [137]:
vstacked = np.vstack( (x, y, z) )
vstacked

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [138]:
vstacked = np.vstack((x,y,z))
print(vstacked)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [139]:
# hstack 
hstacked = np.hstack((x,y,z))
print(hstacked)

[1 1 1 2 2 2 3 3 3]


### OLS with Numpy

In [ ]:
x0.reshape(-1, 1).shape

In [ ]:
# X data generation
n_data = 200
x1 = np.linspace(200, 500, n_data)
x0 = np.ones(n_data)
X = np.hstack(( x0.reshape(-1, 1 ) , x1.reshape(-1, 1 ) ))
X.shape

In [ ]:
# select parameters
beta = np.array([5, -2]).reshape(-1, 1 )
beta.shape

In [ ]:
# y ture
y_true = X @ beta
y_true.shape

In [ ]:
y_true

In [ ]:
y_true + (np.random.normal(0, 1, n_data) * 20).reshape(-1, 1)

In [ ]:
#   add random normal noise
sigma = 20
y_actual = y_true + (np.random.normal(0, 1, n_data) * sigma).reshape(-1, 1)
print(y_actual[0:4, :])

The matrix equation for the estimated linear parameters is as below:
$${\hat {\beta }}=(X^{T}X)^{-1}X^{T}y.$$

In [ ]:
# estimations
beta_estimated = np.linalg.inv(X.T @ X) @ X.T @ y_actual

In [ ]:
import matplotlib.pyplot as plt

plt.plot(x1, y_actual, 'o')
plt.plot(x1, y_true, 'g-', c = 'black')

Calculate the sum of squared residual errors
$$
RSS=y^{T}y-y^{T}X(X^{T}X)^{{-1}}X^{T}y
$$

In [ ]:
y_actual

In [ ]:
RSS = ( y_actual.T @ y_actual - y_actual.T @ X @ np.linalg.inv(X.T @ X) @ X.T @ y_actual )

Calculated the Total Sum of Squares of the spread of the actual (noisy) values around their mean
$$
TSS=(y-{\bar  y})^{T}(y-{\bar  y})=y^{T}y-2y^{T}{\bar  y}+{\bar  y}^{T}{\bar  y}
$$

In [ ]:
y_mean = ( np.ones(n_data) * np.mean(y_actual) ).reshape( -1 , 1 )
TSS = (y_actual - y_mean).T @ (y_actual - y_mean)
TSS

In [ ]:
# get predictions
y_pred = X @ beta_estimated

Calculate the Sum of Squares of the spread of the predictions around their mean.
$$
ESS=({\hat  y}-{\bar  y})^{T}({\hat  y}-{\bar  y})={\hat  y}^{T}{\hat  y}-2{\hat  y}^{T}{\bar  y}+{\bar  y}^{T}{\bar  y}
$$

In [ ]:
ESS = (y_pred - y_mean).T @ (y_pred - y_mean)

ESS

In [ ]:
TSS, ESS + RSS

Get $R^2$
$$
1 - RSS / TSS
$$

In [ ]:
1 - RSS / TSS

###  Standard error of regression
Calculate the standard error of the regression. We divide by `(n-2)`, because the Expectation of the sum of squares is `(n-2)*sigma^2`.

In [ ]:
sr2 = ( (1 / (n_data - 2)) * (y_pred - y_actual).T  @ (y_pred - y_actual))
sr = np.sqrt(sr2)
sr

### Get variance and covariance Matrix
In order to get the standard errors for our linear parameters, we use the matrix formula below:
$$
Var(β^)=σ^2(X′X)^{-1}
$$

In [ ]:
var_beta = sr2 * np.linalg.inv(X.T @ X)
var_beta

In [ ]:
print(
    f'Std Error for b0 {np.sqrt(var_beta[0, 0])}, \nStd Error for b1 {np.sqrt(var_beta[1, 1])}'
)

In [ ]:
pwd