# 1 Assignment - Group 4

## 1.1 Tuple

In [17]:
tuple1 = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")

#### 1. Print the first item of the `tuple1` object. **Hint: Use indexing**<br><br>

In [18]:
print (tuple1 [0])
index1 = tuple1.index( "apple" )
print('The index of "apple" is:', index1)

apple
The index of "apple" is: 0


#### 2. Print the last item of the `tuple1` object.**Hint: Use indexing**<br><br>

In [19]:
print (tuple1 [6])
index2 = tuple1.index( "mango" )
print('The index of "mango" is:', index2)

mango
The index of "mango" is: 6


#### 3. Change the value "orange" for "pink grapefruit". Comment the output. **Hint: Is it possible?** <br><br>

In [20]:
tuple1["orange"] = "pink grapefruit"
#It's not possible because, you can't modify a tuple

TypeError: 'tuple' object does not support item assignment

#### 4. Print the length of `tuple1`. **Hint: Length function**<br><br>

In [21]:
print('The length of the tuple1 is:', len(tuple1))

The length of the tuple1 is: 7


#### 5. Sort `tuple2` in descending order. **Hint: [Try this code](https://stackoverflow.com/questions/3453085/what-is-double-colon-in-python-when-subscripting-sequences)**<br><br>

In [22]:
tuple2 = (10, 20, 30, 40, 50)
tuple2_ra = tuple2[::-1]
print(tuple2_ra)

(50, 40, 30, 20, 10)


#### 6. Generate a new tuple object named as `tuple3` with the half values of `tuple2`. **Hint: Use auxiliary variables.**<br><br>

In [23]:
tuple2 = (10, 20, 30, 40, 50)
tuple3 = tuple(tuple2i/2 for tuple2i in tuple2)
print( tuple3 )

(5.0, 10.0, 15.0, 20.0, 25.0)


## 1.2 List

In [24]:
import numpy as np
f_list = [np.nan , np.nan, "Austria", "Germany", np.nan, "Pakistan", "np.nan", np.nan ]

#### 1. Show the indices of the `np.nan` values  in the `f_list` list. We want to see this output: `The indices 0, 1, 4, 7 have np.nan values.` **Hint: Use print function and [f-strings](https://realpython.com/python-f-strings/) to insert the indices values.**<br><br>

In [25]:
ind = [i for i, v in enumerate(f_list) if v is np.nan]

ind2 = str(ind)[1:-1] 

In [26]:
print('The indices', ind2 ,"have np.nan values")

The indices 0, 1, 4, 7 have np.nan values


#### 2. Replicate 4 times the values of the list `p2_list`. We expect an ouput like this: `[ 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5, 2 , 3, 4, 5]`.  **Hint: Use multiplication function in `lists`and see the output.**<br><br>

In [27]:
p2_list = [2 ,3, 4, 5]

output = p2_list *4

In [28]:
print(output)

[2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5, 2, 3, 4, 5]


#### 3. Print the length of `f_list`. **Hint: Length function**<br><br>

In [29]:
len(f_list)

8

#### 4. Print `My teacher assistant is so boring.` using `text1` list. **Hint: Use the [`join` function](https://stackoverflow.com/questions/493819/why-is-it-string-joinlist-instead-of-list-joinstring)**<br><br>

In [30]:
text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring.']

In [31]:
print(*text1, sep=" ") 

My teacher assistant is so boring.


In [32]:
#or
print(' '.join(text1))

My teacher assistant is so boring.


#### 5. Print `My TA is so boring, but is very funny.` using `text1` list.**Hint: Use the `join` function, and `extend` method.**<br><br>

In [33]:
text1 = ['My', 'teacher', 'assistant', 'is', 'so', 'boring']
text2 = [',','but', 'is', 'very', 'funny.']
text1.extend(text2)

print(' '.join(text1))

My teacher assistant is so boring , but is very funny.


#### 6. Print <br>
`The max value of values1 is 86 and is located in the 0 index. ` <br>
`The min value of values1 is 0 and is located in the 7 index. ` <br> **Hint: Use the `f-string`, `min`, and `max` functions.**

In [34]:
values1 = [ 86, 86, 85, 85, 85, 83, 23, 0, 84, 1 ] 

In [35]:
max1 = 'max'
valor1 =  max(values1)
ubicacion1 = values1.index(max(values1))

min1 = 'min'
valor2 =  min(values1)
ubicacion2 = values1.index(min(values1))

print(f'The {max1} value of values1 is {valor1} and is located in the {ubicacion1} index.\n',
    f'The {min1} value of values1 is {valor2} and is located in the {ubicacion2} index.')

The max value of values1 is 86 and is located in the 0 index.
 The min value of values1 is 0 and is located in the 7 index.


## 1.3 Dictionaries

In [36]:
car = { "brand": "Ford",  "model": "Mustang",  "year": 1964}
hr_sleep = {"january": {"wednesday": 7, "thursday": 8, "friday": [2, 2, 1, 2]}, "february": {"saturday": 5, "sunday": 10, "monday": 8 }}

In [37]:
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

####  1. Create a dictionary with two keys: `even_numbers` and `odd_numbers`. The first key should have all the even numbers in this range `[0, 2000]`, and the second key must have all the odd numbers in this range `[9000, 19000]`. The values should be stored in a `list`. **Hint: Use the `np.arange`, `zip`, and `np.tolist()` functions.** <br><br>

In [38]:
import numpy as np

In [39]:
even_numbers = np.arange(2,2001,2)
len(even_numbers)

1000

In [40]:
even_numbers.tolist()

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,
 35

In [41]:
odd_numbers = np.arange( 9001,19000, 2 )
len( odd_numbers )

5000

In [42]:
odd_numbers.tolist()

[9001,
 9003,
 9005,
 9007,
 9009,
 9011,
 9013,
 9015,
 9017,
 9019,
 9021,
 9023,
 9025,
 9027,
 9029,
 9031,
 9033,
 9035,
 9037,
 9039,
 9041,
 9043,
 9045,
 9047,
 9049,
 9051,
 9053,
 9055,
 9057,
 9059,
 9061,
 9063,
 9065,
 9067,
 9069,
 9071,
 9073,
 9075,
 9077,
 9079,
 9081,
 9083,
 9085,
 9087,
 9089,
 9091,
 9093,
 9095,
 9097,
 9099,
 9101,
 9103,
 9105,
 9107,
 9109,
 9111,
 9113,
 9115,
 9117,
 9119,
 9121,
 9123,
 9125,
 9127,
 9129,
 9131,
 9133,
 9135,
 9137,
 9139,
 9141,
 9143,
 9145,
 9147,
 9149,
 9151,
 9153,
 9155,
 9157,
 9159,
 9161,
 9163,
 9165,
 9167,
 9169,
 9171,
 9173,
 9175,
 9177,
 9179,
 9181,
 9183,
 9185,
 9187,
 9189,
 9191,
 9193,
 9195,
 9197,
 9199,
 9201,
 9203,
 9205,
 9207,
 9209,
 9211,
 9213,
 9215,
 9217,
 9219,
 9221,
 9223,
 9225,
 9227,
 9229,
 9231,
 9233,
 9235,
 9237,
 9239,
 9241,
 9243,
 9245,
 9247,
 9249,
 9251,
 9253,
 9255,
 9257,
 9259,
 9261,
 9263,
 9265,
 9267,
 9269,
 9271,
 9273,
 9275,
 9277,
 9279,
 9281,
 9283,
 9285,

In [43]:
dictionary_even_odd = dict( zip( even_numbers, odd_numbers ) )

In [44]:
dictionary_even_odd

{2: 9001,
 4: 9003,
 6: 9005,
 8: 9007,
 10: 9009,
 12: 9011,
 14: 9013,
 16: 9015,
 18: 9017,
 20: 9019,
 22: 9021,
 24: 9023,
 26: 9025,
 28: 9027,
 30: 9029,
 32: 9031,
 34: 9033,
 36: 9035,
 38: 9037,
 40: 9039,
 42: 9041,
 44: 9043,
 46: 9045,
 48: 9047,
 50: 9049,
 52: 9051,
 54: 9053,
 56: 9055,
 58: 9057,
 60: 9059,
 62: 9061,
 64: 9063,
 66: 9065,
 68: 9067,
 70: 9069,
 72: 9071,
 74: 9073,
 76: 9075,
 78: 9077,
 80: 9079,
 82: 9081,
 84: 9083,
 86: 9085,
 88: 9087,
 90: 9089,
 92: 9091,
 94: 9093,
 96: 9095,
 98: 9097,
 100: 9099,
 102: 9101,
 104: 9103,
 106: 9105,
 108: 9107,
 110: 9109,
 112: 9111,
 114: 9113,
 116: 9115,
 118: 9117,
 120: 9119,
 122: 9121,
 124: 9123,
 126: 9125,
 128: 9127,
 130: 9129,
 132: 9131,
 134: 9133,
 136: 9135,
 138: 9137,
 140: 9139,
 142: 9141,
 144: 9143,
 146: 9145,
 148: 9147,
 150: 9149,
 152: 9151,
 154: 9153,
 156: 9155,
 158: 9157,
 160: 9159,
 162: 9161,
 164: 9163,
 166: 9165,
 168: 9167,
 170: 9169,
 172: 9171,
 174: 9173,
 176: 917

####  2. Check if `TA` is a key of your object created in exercise 1. **Hint: Generate an object with the keys of your dictionary and check the statement using [`in` function](https://stackoverflow.com/questions/1602934/check-if-a-given-key-already-exists-in-a-dictionary). Do not use `if` function. Use `print` function.** <br><br>

In [45]:
key_dic_numb = dictionary_even_odd.keys()
judge = 'TA' in key_dic_numb 
print ( "It's", judge, "that TA is a key of the dictionary_even_odd" )

It's False that TA is a key of the dictionary_even_odd


####  3. Print the value of `brand` key of `car` dictionary. **Hint: Use the `get` method.** <br><br>

In [46]:
car = { "brand": "Ford",  "model": "Mustang",  "year": 1964}

In [47]:
print( "The value of the brand key of car is", car.get( 'brand' ))

The value of the brand key of car is Ford


####  4. Print all the the values of `brand` key of `car` dictionary. **Hint: Use the `values` method.** <br><br>

In [48]:
car.values()
print(car["brand"])

Ford


####  5. Print the max value  of `friday` in `january` of `hr_sleep` dictionary. **Hint: [Indexing in nested dictioanries](https://stackoverflow.com/questions/25836376/how-to-get-the-inner-indexes-of-a-nested-dictionary-in-python).** <br><br>

In [49]:
hr_sleep = {"january": { "wednesday": 7, "thursday": 8, "friday": [2, 2, 1, 2] },
            "february": { "saturday": 5, "sunday": 10, "monday": 8 } }
friday = hr_sleep[ "january" ][ "friday" ]

In [50]:
print (max(friday))

2


####  6. Add `march` key to the `hr_sleep` dictionary using `week1` and `values2` Python lists. **Hint: Use `zip` function adn [this link](https://stackoverflow.com/questions/1024847/how-can-i-add-new-keys-to-a-dictionary).** <br><br>

In [51]:
hr_sleep = {"january": { "wednesday": 7, "thursday": 8, "friday": [2, 2, 1, 2] },
            "february": { "saturday": 5, "sunday": 10, "monday": 8 } }
friday = hr_sleep[ "january" ][ "friday" ]
week1 = ['monday', 'sunday']
values2 = [ [2, 3, 4 ] , 8, ]

In [52]:
march = { "march": { "monday": [ 2, 3, 4 ], "sunday": 8 } }

In [53]:
hr_sleep2 = hr_sleep.copy()
hr_sleep2.update(march)
print(hr_sleep2)

{'january': {'wednesday': 7, 'thursday': 8, 'friday': [2, 2, 1, 2]}, 'february': {'saturday': 5, 'sunday': 10, 'monday': 8}, 'march': {'monday': [2, 3, 4], 'sunday': 8}}


## 1.4 Numpy

#### 1. Replace all the `even_numbers` in `np1` with 100. **Hint: Use `indexing` in arrys and [this filer](https://stackoverflow.com/questions/41638751/filtering-even-numbers-in-python).** <br><br>

In [54]:
import numpy as np
np1 = np.arange(200, 750)
np1[np1%2 == 1] = 100
print( np1 )

[200 100 202 100 204 100 206 100 208 100 210 100 212 100 214 100 216 100
 218 100 220 100 222 100 224 100 226 100 228 100 230 100 232 100 234 100
 236 100 238 100 240 100 242 100 244 100 246 100 248 100 250 100 252 100
 254 100 256 100 258 100 260 100 262 100 264 100 266 100 268 100 270 100
 272 100 274 100 276 100 278 100 280 100 282 100 284 100 286 100 288 100
 290 100 292 100 294 100 296 100 298 100 300 100 302 100 304 100 306 100
 308 100 310 100 312 100 314 100 316 100 318 100 320 100 322 100 324 100
 326 100 328 100 330 100 332 100 334 100 336 100 338 100 340 100 342 100
 344 100 346 100 348 100 350 100 352 100 354 100 356 100 358 100 360 100
 362 100 364 100 366 100 368 100 370 100 372 100 374 100 376 100 378 100
 380 100 382 100 384 100 386 100 388 100 390 100 392 100 394 100 396 100
 398 100 400 100 402 100 404 100 406 100 408 100 410 100 412 100 414 100
 416 100 418 100 420 100 422 100 424 100 426 100 428 100 430 100 432 100
 434 100 436 100 438 100 440 100 442 100 444 100 44

#### 2. Create a 3x3 matrix with values ranging from 0 to 8. **Hint: Use `np.arange` and `np.reshape` method.** <br><br>

In [55]:
matrix1 =  np.arange(0, 9).reshape(3,3)
print(matrix1)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 3. Consider an array `Z = [1,2,3,4,5,6,7,8,9,10]`, generate an array `R = [ [ 1, 2, 3, 4], [ 2, 3, 4, 5 ], [ 3, 4, 5, 6 ], ..., [ 7, 8, 9, 10 ] ]`?.**Hint: Use np.arange and np.concatenate** <br><br>

In [56]:
z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) 
r = np.lib.stride_tricks.as_strided(x = z, shape = (7,4), strides = (4,4))
r1 = r.tolist()
print ("Array = ", r1 )

Array =  [[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9], [7, 8, 9, 10]]


#### 4. Create a 3x3x3 array with random values. **Hint: Use [`np.random.random`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.random.html).** <br><br>

In [6]:
import numpy as np

In [5]:
np.random.random( (3,3,3) )

array([[[0.35601387, 0.39814325, 0.14939593],
        [0.55064891, 0.2306386 , 0.13171769],
        [0.04879761, 0.22523558, 0.01187044]],

       [[0.77447657, 0.51013315, 0.27367861],
        [0.81883835, 0.32314785, 0.46563658],
        [0.05391091, 0.35361607, 0.65203452]],

       [[0.87119572, 0.32185935, 0.14018493],
        [0.29967178, 0.17509995, 0.16217845],
        [0.33981868, 0.51134669, 0.78959422]]])

#### 5. Comment why this expression `np.nan == np.nan` is False. **Hint: Use stackoverflow.** <br><br>

In [58]:
#Because equivalence between missing or invalid values is not well defined

#### 6. Print the `mean` and `standard deviation` of `np2`. **Hint: Use `f-string`, `np.mean`, and `np.var` methods.**

In [59]:
np2 = np.random.normal( 50, 4, 300)
mean_np2 = np.mean( np2 )
var_np2 = np.var( np2 )

In [60]:
print(f"The mean of np2 is {mean_np2} and it's standard deviation is {var_np2}")

The mean of np2 is 50.176829491877214 and it's standard deviation is 15.750321369269232


## Restricted Least Squares

In [4]:
## Data base and objects
import pandas as pd
import numpy as np
greene = pd.read_csv(r"../../_data/christensen_greene_f4.csv")

ct = greene.COST.values
q = greene.Q.values
p1 = greene.PL.values
p2 = greene.PF.values
p3 = greene.PK.values

#### Given the following equation:


$$
\begin{aligned} 
lnCT &= \beta_{0}+\beta_{q}lnq+ \frac{1}{2}\beta_{qq} lnq^2+\beta_{q1}lnqlnp_1+\beta_{q2}lnqlnp_2+ \beta_{q3}lnqlnp_{3} +\beta_{1}lnp_1+\beta_{2}lnp_2+ \beta_{3}lnp_3 \\
& + \frac{1}{2}\beta_{11}ln^{2}p_1+ \frac{1}{2}\beta_{22}ln^{2}p_{2}+ \frac{1}{2}\beta_{33}ln^{2}p_{3} + \frac{1}{2}\beta_{12}lnp_{1}lnp_{2}+ \frac{1}{2}\beta_{13}lnp_{1}lnp_{3}+\frac{1}{2}\beta_{23}lnp_{2}lnp_{3} 
\end{aligned}
$$


ST: 

<br>
$$
\begin{aligned} 
\beta_{1} + \beta_{2} + \beta_{3} &= 1 \\
\beta_{q1} + \beta_{q2} + \beta_{q3} &= 0 \\
\beta_{11} + \beta_{12} + \beta_{13} &= 0 \\
\beta_{21} + \beta_{22} + \beta_{23} &= 0 \\
\beta_{31} + \beta_{32} + \beta_{33} &= 0 \\
\beta_{ij} = \beta_{ji}
\end{aligned}
$$

1. Get $\widehat{\boldsymbol{\beta}}^{(RLS)}$ vector from the equation bellow. Use the `q`, `p1`, `p2`, `p3`, `CT` numpies. <br><br>

In [5]:
# vector of dependent variable
y_actual = np.log(ct)

In [6]:
# independent variables or covariates matrix

constant = x0 = np.ones(ct.shape)
lnq = np.log(q) 
lnq_2 = (1/2)*np.log(np.sqrt(q))
lnp1 = np.log(p1)
lnp2 = np.log(p2)
lnp3 = np.log(p3)
lnq_lnp1 = lnq*lnp1 
lnq_lnp2 = lnq*lnp2
lnq_lnp3 = lnq*lnp3
ln_2_p1 = (1/2)*np.sqrt(lnp1)
ln_2_p2 = (1/2)*np.sqrt(lnp2)
ln_2_p3 = (1/2)*np.sqrt(lnp3)
lnp1_lnp2 = (1/2)*lnp1*lnp2
lnp1_lnp3 = (1/2)*lnp1*lnp3
lnp2_lnp3 = (1/2)*lnp2*lnp3

X = np.hstack(( constant.reshape(-1, 1 ), lnq.reshape(-1, 1 ), lnq_2.reshape(-1, 1 ), lnq_lnp1.reshape(-1, 1 ), lnq_lnp2.reshape(-1, 1 ), 
                lnq_lnp3.reshape(-1, 1 ), lnp1.reshape(-1, 1 ), lnp2.reshape(-1, 1 ), lnp3.reshape(-1, 1 ), ln_2_p1.reshape(-1, 1 ), ln_2_p2.reshape(-1, 1 ), 
                ln_2_p3.reshape(-1, 1 ), lnp1_lnp2.reshape(-1, 1 ), lnp1_lnp3.reshape(-1, 1 ), lnp2_lnp3.reshape(-1, 1 ) ))

In [7]:
# Restriction matrix and vector 

rest_1 = np.array([0,0,0,0,0,0,1,1,1,0,0,0,0,0,0])
rest_2 = np.array([0,0,0,1,1,1,0,0,0,0,0,0,0,0,0])
rest_3 = np.array([0,0,0,0,0,0,0,0,0,1,0,0,1,1,0])
rest_4 = np.array([0,0,0,0,0,0,0,0,0,0,1,0,1,0,1])
rest_5 = np.array([0,0,0,0,0,0,0,0,0,0,0,1,0,1,1])

L = np.vstack(( rest_1, rest_2, rest_3, rest_4, rest_5 ))
r = np.array([1,0,0,0,0])


In [8]:
L.shape
r.shape

(5,)

In [9]:
# parameters estimates
beta_ols = np.linalg.inv(X.T @ X) @ X.T @ y_actual 
beta_rls = beta_ols - np.linalg.inv(X.T @ X) @ L.T @ np.linalg.inv(L @ (np.linalg.inv(X.T @ X)) @ L.T) @ (L @ beta_ols - r )
beta_rls

array([-3.53568389e+00, -4.78107853e+04,  1.91243620e+05,  4.48574913e-02,
        4.20738001e-02, -8.69312914e-02, -1.34358260e-01, -1.06068124e+00,
        2.19503950e+00,  4.89685664e-02, -3.80822027e-01,  2.53555324e-01,
        2.92704392e-01, -3.41672959e-01,  8.81176344e-02])

#### 2. Get the `covariance matrix` $\mathbb{V}{\rm ar} \left(\widehat{\boldsymbol{\beta}}^{(RLS)} \right)$. <br><br>
**Hint: For more information about Restricted Least Squares [click here](http://web.vu.lt/mif/a.buteikis/wp-content/uploads/PE_Book/4-4-Multiple-RLS.html).**<br>

In [10]:
#### Calculating predicted values
y_pred = X @ beta_rls

In [13]:
#### Calculating the standard error of the regression
dimentions = X.shape
n_data = dimentions[0]
sr2 = ( (1 / (n_data - 2)) * (y_pred - y_actual).T  @ (y_pred - y_actual))
sr2

2.2067170790542874

In [14]:
#### Getting variance and covariance Matrix
var_beta = sr2 * L @ np.linalg.inv(X.T @ X) @ L.T
var_beta

array([[ 1.81822343e+04, -7.76693137e+00, -2.07336640e+05,
        -3.90794771e+01, -8.71584215e+03],
       [-7.76693136e+00,  3.19565988e-01,  8.95440658e+01,
         1.23013442e+00,  7.26358785e+00],
       [-2.07336640e+05,  8.95440660e+01,  2.83501077e+06,
        -1.19735504e+04,  7.13150033e+04],
       [-3.90794752e+01,  1.23013442e+00, -1.19735504e+04,
         7.73005214e+03, -2.83648354e+03],
       [-8.71584221e+03,  7.26358788e+00,  7.13150040e+04,
        -2.83648354e+03,  1.01708299e+05]])