# Assignment 1 – Group 01

This notebook contains answers to Part 1, 2 and 3.

---

## Part 1 – Git Workflow (Branch → Pull Request → Merge)

1. [X] Explain the difference between **working on a branch** and **working directly on `main`**. Why is it recommended to always use branches in collaborative projects?  [1 pts] 

> ### **Trabajar en el main directamente y el branch**
> 
> El **main** es la rama principal y es parte del repositorio; sin embargo, un **branch** es una rama, una línea independiente separada del main y no altera el repositorio.
> 
> Al hacer cambios directamente en el main, cada commit afecta a la base del código; por otro lado, con los branches pueden 
hascerse cambios (e.g. crearse nuevas funcionalidades, corregir errores) sin alterar el versión principal.
> 
> Trabajar directamente en el main representa muchos riesgos: los errores o funciones pueden poner en riesgo el proyecto; 
se dificulta la revisión, aprobación de los cambios y se pueden generar conflicto de código. En contraposición, el branch es versátil y mantiene estable el proyecto; facilita la revisión de código, se reducen los conflictos y errores; permite varias tareas en simultáneo....

2. [X] Create a branch with the following naming format: `group_##_assignment1_2025` *(Example: group_01_assignment1_2025)*. All group results must be saved inside this [folder](https://github.com/alexanderquispe/Diplomado_PUCP/tree/main/Lecture_1/Assigment_1).  

> Se creó una carpeta con el nombre *group_01_assignment1_2025* dentro de la ruta señalada *Diplomado_PUCP/Lecture_1/Assigment_1/*

3. [X] Within that branch, create a file called **movies.md** where you include at least **3 favorite movies**. For each movie, you must include: Title, Release year and Synopsis (max. 3 lines). Use Markdown to format (titles, subtitles, **bold**, *italics*, bullet points, etc.).

> El archivo movies.md se encuentra disponible en la ruta *Diplomado_PUCP/Lecture_1/Assigment_1/group_01_assignment1_2025/movies.md*

4. [X] Make a commit with the following message: "Added my favorite movies". Write down the corresponding Git command. Choose **one group member** to act as the *repository maintainer*. Their responsibilities will be:  
   - Reviewing all contributions  
   - Managing the group branch  
   - Performing the **final merge** into `main`  

> Se siguieron los pasos.

6. [X] Create a **Pull Request (PR)** on GitHub to merge the group branch into `main`. Explain in which cases a *reviewer* might reject the PR (e.g., code conflicts, formatting errors, failure to follow instructions, etc.).  


> ### **Sobre los PR**
> Para el trabajo colaborativo efectivo debemos crear o generar las ramas (branches) con la finalidad que todos los integrantes del grupo puedan reaizar sus tareas asignadas sin contratiempos y a cargo de un supervisor que al final da la confrmidad y consolida el trabajo grupal.
>
> Un revisor puede rechazar el PR debido en caso haya conflictos con el código entre branches. Otros escenarios incluyen que no se haya producido lo solicitado, no se hayan seguido instrucciones, la propuesta de código nueva no sea suficiente o pertinente, o más bien que esta intente cambiar cosas que no debería.
>
> Después de haber delegado las distintas tareas a los colaboradores a través de los branches (ramas), debemos incluirlas en el Main (o la rama troncal del proyecto). Para ello debemos seguir los siguientes pasos:
1.	Asumimos que se ha han creado varios Branches que deseamos unir al Main
2.	Seleccionamos el Branch de nuestro interés. Hacemos clic en los tres puntos y seleccionamos New pull request.
3.	Recordemos que el New pull request, es solicitar autorización para que se acepte la modificación o que el Branch se una al Mainbranch. La nueva ventana nos solicita agregar un título, una descripción y finalmente Create pull request.
4.	Realizamos el merge pull request
5.	Confirmamos el merg.
6.	Para cerciorarnos de los cambios y visualizarlo vamos a Code.
7.	Finalmente, seleccionamos Main y visualizamos todos los aportes de colaboradores.
8. Enviar el Pull Request (PR) para su revisión.
>
> ¿Cómo resolver conflictos en el proceso del trabajo colaborativo? De existir conflictos en el proceso, el sistema nos arroja el siguiente mensaje: Resolve conflicts.
1.	GitHub nos muestra dónde están los conflictos. En el ejemplo de clase fueron Movies y Actors.
2.	Los conflictos se originan por varios motivos, pero deben ser solucionados por el director del equipo. Es conflictos se corrigen de manera manual. Así por ejemplo, si alguno de ellos no es el correcto se elimina, pero si los dos están bien se eliminan manualmente los signos (igual, mayor y menor). 
3.	A continuación, marcamos como resuelto.
4.	Después, commit merge
5.	Ahora, confirmamos el merge
6.	Como penúltimo paso seleccionamos Code.
7.	Finalmente, el mainbranch está completo.
8. Enviar el Pull Request (PR) para su revisión.
>

---

## Part 2 – Data Types and Data Structures  

6. [X] Declare a variable for each of the following types: **int**, **float**, **string**, and **boolean**.  
   Then print the type of each variable using the `type()` function.  

In [172]:
# 6. Declare a variable for each of the following types: int, float, string, and boolean.
#Then print the type of each variable using the type() function.
my_int = 10
my_float = 3.14
my_string = "Hola"
my_bool = True

# Imprimir el tipo de cada variable
print("my_int:", type(my_int))
print("my_float:", type(my_float))
print("my_string:", type(my_string))
print("my_bool:", type(my_bool))

my_int: <class 'int'>
my_float: <class 'float'>
my_string: <class 'str'>
my_bool: <class 'bool'>


7. [X] Create a list that contains the following elements:  
   - A string  
   - A boolean value  
   - Two numeric values (of any type)  
   - A list with two strings representing your favorite music artists  

- [X] From that list:  
   - Access the **first** and the **last** element  
   - Add a new string  
   - Remove the boolean value  

In [173]:
# 7. Create a list that contains the following elements:
#A string
#A boolean value
#Two numeric values (of any type)
#A list with two strings representing your favorite music artists

my_list = ["Hola", True, 10, 3.14,["Coldplay", "Adele"]]

# Imprimir la lista completa
print('\n7.Created list:')
print(my_list)

# Access first element
print('\n7.a First element:')
print(my_list[0])

# Access last element
print('\n7.b Last element:')
print(my_list[-1])

# Add a new string
my_list.append('this is a new string')
print('\n7.c Updated list:')
print(my_list)

# Remove de boolean value
print('\n7.d Updated list:')
my_list.pop(1)
print(my_list)


7.Created list:
['Hola', True, 10, 3.14, ['Coldplay', 'Adele']]

7.a First element:
Hola

7.b Last element:
['Coldplay', 'Adele']

7.c Updated list:
['Hola', True, 10, 3.14, ['Coldplay', 'Adele'], 'this is a new string']

7.d Updated list:
['Hola', 10, 3.14, ['Coldplay', 'Adele'], 'this is a new string']


8. [X] Define a **tuple** that contains: [1 pts] 
   - A string  
   - A boolean  
   - A tuple with three numeric values (of any type)  

- [X] Explain in your own words why a tuple is **immutable** and try to modify one of its elements to prove it.   


In [174]:
# 8. Define a tuple that contains: [1 pts]
# A string
# A boolean
# A tuple with three numeric values (of any type)

my_tuple = ("Hola", False, (10, 20.5, 3))

# Imprimir la tupla
print(my_tuple)

('Hola', False, (10, 20.5, 3))


> A **tuple** is said to ibe *immutable* because it cannot be changed or transformed once it is created. More specifically, we cannont add o remove values to it after it has been defined and stored in memory. Its nature ensures data safety and helps optimization.
> 
> We will try deleting an item from *my_tuple* to prove it cannot be done.

In [175]:
del my_tuple[1]

TypeError: 'tuple' object doesn't support item deletion

9. [X] Write a Python function named **`movie_summary`** that takes as argument a dictionary of movies with the following structure:  

   ```python
   movies = {
     "Inception": {"year": 2010, "genre": "Sci-Fi"},
     "Parasite": {"year": 2019, "genre": "Drama"},
     "Whiplash": {"year": 2014, "genre": "Drama"}
   }
   ```
   
The function must return a list with sentences in the following format:  

> "The movie Inception belongs to the Sci-Fi genre and was released in 2010."  


In [176]:
# 9. Define function movie_summary
def movie_summary(movies_dict):
    """
    Takes a dictionary of movies and returns a list of formatted summary sentences.
    Args: 
        movies_dict (dict): A dictionary where keys are movie titles and values are dictionaries with "year" and "genre".
    Returns: 
        list: A list of sentences summarizing each movie.
    """
    info = []
    for title, details in movies_dict.items():
        sentence = f"The movie {title} belongs to the {details['genre']} genre and was released in {details['year']}."
        info.append(sentence)
    return info

In [177]:
movies = {"Inception": {"year": 2010, "genre": "Sci-Fi"},
          "Parasite": {"year": 2019, "genre": "Drama"},
          "Whiplash": {"year": 2014, "genre": "Drama"}}
movie_summary(movies)

['The movie Inception belongs to the Sci-Fi genre and was released in 2010.',
 'The movie Parasite belongs to the Drama genre and was released in 2019.',
 'The movie Whiplash belongs to the Drama genre and was released in 2014.']

In [178]:
# 9. ALTERNATIVA: Get info by movie
def movie_summary2(movies_dict, title):
    """
    Takes a dictionary of movies and title of one of then and returns a prints basic information about it.
    Args: 
        movies_dict (dict): A dictionary where keys are movie titles and values are dictionaries with "year" and "genre".
        title (str): A movie title from the dict.
    Returns: 
        info: A str summarizing selected movie.
    """
    if title in movies_dict:
        info = f"The movie {title} belongs to the {movies_dict[title]['genre']} genre and was released in {movies_dict[title]['year']}."
    else:
        info = f"The movie {title} is not in the entered dict."        
    return info

In [179]:
movie_summary2(movies, 'Whiplash')

'The movie Whiplash belongs to the Drama genre and was released in 2014.'

10. [X] Using **NumPy**, generate a **4x4 matrix** with random integers between 1 and 100.  
Then calculate:  
- The **mean per column**  
- The **sum of the values in the main diagonal**  

In [180]:
import numpy as np

In [181]:
# 10.
# Generate a 4x4 matriz with random integers between 1 y 100
matrix = np.random.randint(1, 101, size=(4, 4))

print("\n10. Matrix:")
print(matrix)

# Calculate mean per column
column_means = np.mean(matrix, axis=0)

print("\n10.a Column means:")
print(column_means)

# Calculate sum of the values in the main diagonal
sum_main_diagonal = np.trace(matrix)

print("\n10.b Sum of the values in the main diagonal:")
sum_main_diagonal


10. Matrix:
[[ 81  46 100  25]
 [ 87  95  25   9]
 [ 89  97  74   5]
 [100  34  75  94]]

10.a Column means:
[89.25 68.   68.5  33.25]

10.b Sum of the values in the main diagonal:


344

---

## Part 3 – Pandas Series  

11. [X] From the list of grades `[15, 17, 20, 11, 13, 18, 19]`, create a **Pandas Series** assigning student names as the index (for example: `"Ana"`, `"Jorge"`, `"Valeria"`, etc.).  

In [182]:
import pandas as pd

In [183]:
# 11. This script creates a DataFrame with the grades and students
grades = [15, 17, 20, 11, 13, 18, 19]
students = ['Ana', 'Jorge', 'Valeria', 'David', 'Evelin', 'Franco', 'Grecia']

grades_series = pd.Series(grades, index=students)

grades_series

Ana        15
Jorge      17
Valeria    20
David      11
Evelin     13
Franco     18
Grecia     19
dtype: int64

12. [X] Using the Series created in the previous step, calculate:  
   - The **average of the grades**.  
   - The **student with the highest grade** (use `.idxmax()`).  
   - The **student with the lowest grade** (use `.idxmin()`).  

In [184]:
# 12. This script calculates the average grade, highest and lowest student
average_grade = grades_series.mean()
highest_student = grades_series.idxmax()
lowest_student = grades_series.idxmin()

average_grade, highest_student, lowest_student

(16.142857142857142, 'Valeria', 'David')

13.  [X] Create a Series from a **dictionary of countries and their capitals**.  
    Filter and display only those countries whose capital has more than **6 letters**.

In [185]:
# 13. This script creates a dictionary of countries and their capitals
countries = {
    'Peru': 'Lima',
    'Colombia' : 'Bogotá',
    'Argentina': 'Buenos Aires',
    'Chile': 'Santiago de Chile',
    'Ecuador': 'Quito',
    'Bolivia': 'Sucre',
    'Brazil': 'Brasilia',
    'Venezuela': 'Caracas'
}

countries_series = pd.Series(countries)
countries_filered = countries_series[countries_series.str.len()>6]

countries_filered

Argentina         Buenos Aires
Chile        Santiago de Chile
Brazil                Brasilia
Venezuela              Caracas
dtype: object

14. [X] Create a Series containing several **strings** and convert all its elements to **uppercase** using the `.apply(str.upper)` method.  

In [186]:
# 14. This script creates a Series with text data
text = ['diplomado', 'pucp', 'python', 'data science', 'machine learning', 'artificial intelligence']
text_series = pd.Series(text)
text_series = text_series.apply(str.upper)
text_series

0                  DIPLOMADO
1                       PUCP
2                     PYTHON
3               DATA SCIENCE
4           MACHINE LEARNING
5    ARTIFICIAL INTELLIGENCE
dtype: object