# Part 2

In [ ]:
# Pregunta 6. 

int_var = 5
float_var = 5.5
string_var = "Entropía"
bool_var = True

print(type(int_var))
print(type(float_var))
print(type(string_var))
print(type(bool_var))
			


<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [2]:
# 7.

my_list = ["Batman", True, 5, 5.6, ["Mike Oldfield", "Kendrick Lamar"]]

print(my_list[0], my_list[-1])


my_list.append("Superman")
print(my_list)


my_list.remove(True)
print(my_list)

Batman ['Mike Oldfield', 'Kendrick Lamar']
['Batman', True, 5, 5.6, ['Mike Oldfield', 'Kendrick Lamar'], 'Superman']
['Batman', 5, 5.6, ['Mike Oldfield', 'Kendrick Lamar'], 'Superman']


In [10]:
# 8.

my_tuple = ("Flash", False, (6, 6.5, 7))

my_tuple

# A tuple is immutable because it cannot be changed once is created, that means that you cannot add, delete or change any of its elements.


('Flash', False, (6, 6.5, 7))

In [11]:
# trying to modify a tuple to prove it's immutable

my_tuple.append("Rust is better than C")

AttributeError: 'tuple' object has no attribute 'append'

In [ ]:
# 9. 


movies = {
    "Dune": {"year": 2021, "genre": "Sci-Fi"},
    "Blade Runner 2049": {"year": 2017, "genre": "Sci-Fi"},
    "Alien": {"year": 1979, "genre": "Sci-Fi"}
}

"""
we created a function that takes the year and genre from a movie dictionary then gives as result a short sentence. 

"""

def movie_summary(movies):
    
    summaries = []
    
    for title, details in movies.items():
        year = details["year"]
        genre = details["genre"]
        sentence = f"The movie {title} belongs to the {genre} genre and was released in {year}."
        summaries.append(sentence)
    
    return summaries

result = movie_summary(movies)


for summary in result:
    print(summary)

In [ ]:
# 10.

import numpy as np

matrix = np.random.randint(1, 101, size=(4, 4))
print("Matriz 4x4:\n", matrix)

mean_per_column = np.mean(matrix, axis=0)
print("\nMedia por columna:", mean_per_column)

main_diagonal_sum = np.trace(matrix)
print("\nSuma de la diagonal principal:", main_diagonal_sum)

Matriz 4x4:
 [[100   8  69  13]
 [ 28  96  98   5]
 [ 69  80  60  54]
 [ 81  96  70  64]]

Media por columna: [69.5  70.   74.25 34.  ]

Suma de la diagonal principal: 320


# Part 3

In [37]:
# 11. 

import pandas as pd

grades = [15, 17, 20, 11, 13, 18, 19]

names = ["Ana", "Jorge", "Valeria", "Luis", "María", "Carlos","Sofía"]

df = pd.Series(grades, index = names)

print(df)

Ana        15
Jorge      17
Valeria    20
Luis       11
María      13
Carlos     18
Sofía      19
dtype: int64


In [38]:
# 12.

avg = df.mean()

print(f"The grade average is: {avg}")

h_grade = df.idxmax()

print(f"The student with highest grade is: {h_grade}")

l_grade = df.idxmin()

print(f"The student with the lowest grade is {l_grade}")


The grade average is: 16.142857142857142
The student with highest grade is: Valeria
The student with the lowest grade is Luis


In [47]:
# 13.

# we created a list of south american countries and their capitals

data = {
    "Peru": "Lima",
    "Argentina": "Buenos Aires",
    "Brazil": "Brasilia",
    "Chile": "Santiago",
    "Colombia": "Bogotá",
    "Venezuela": "Caracas",
    "Ecuador": "Quito",
    "Paraguay": "Asuncion",
    "Uruguay": "Montevideo",
    "Bolivia": "La Paz"

}

countries = pd.Series(data)

six_len = countries[countries.str.len() > 6]

print(six_len)

Argentina    Buenos Aires
Brazil           Brasilia
Chile            Santiago
Venezuela         Caracas
Paraguay         Asuncion
Uruguay        Montevideo
dtype: object


In [42]:
# 14.

brand = ["ferrari", "porshe", "maseratti", "bmw"]

brand = pd.Series(brand)

brand.apply(str.upper)

0      FERRARI
1       PORSHE
2    MASERATTI
3          BMW
dtype: object